== Selection from the Journal of John Conran

I have had it on my mind, at various times for years past,
to leave some memorial of the tender and merciful dealings of a
gracious Creator with me (unworthy as I feel of the least of them);
and I trust and hope that my endeavoring to do so at this time
proceeds more from a desire to give the praise to whom it is due,
than to exalt the creature, to whom only belongs "`shame and confusion of face.`"

I am now (1808) in the 69th year of my age,
and though the concerns of my past life may by many
be thought of little consequence to the public,
for whom they are not recorded,
yet they may prove of advantage to some who may be led to
travel in that "`path which the vulture`'s eye has not seen.`"^
footnote:[Job 28:7]
The keen discerning eye of human wisdom has not been able, in any age of the world,
to disclose that mystery which was hidden from the
wise and prudent in all ages and generations.
But the patriarchs, prophets, and apostles, being sojourning men of simple lives,
and not acquainted with that learning which the heathen took so much pride in,
walked in the living experience of the ways and workings
of the divine grace in their own hearts,
following and obeying it,
and were thereby made partakers of that covenant of life which comes only
through the spiritual appearance of Jesus Christ within them.
Such as these (let their outward name as to religion be what it may),
while they obeyed this heavenly light and were followers of it, became children of it,
and the works they did in obedience to it were works of righteousness,
and were accepted at their hands.

It was after this manner,
that many who knew not the law were not only a law to themselves,^
footnote:[Romans 2:14]
but their lives and conduct made them as lights in the world;
the full manifestation of the glorious gospel day being reserved
for the coming and appearance of our Lord and Savior Jesus Christ,
which day Abraham saw in the vision of life and was glad.
In the same life and light the prophets and holy men of old foretold these glad tidings,
as they were inspired by the Holy Spirit.
Man, by his own wisdom,
and aided by all the acquired learning either of himself or others,
was not able to comprehend this revelation.
Indeed, this sort of learning was neither sufficient for men in former ages,
nor is it sufficient in this age or generation to savingly make known Christ within,
the hope of glory, or to enable men to confess (in their life and conduct,
governed by holy fear) that He is the Christ, the Son of the living God.
Truly, flesh and blood cannot reveal this now, any more than it could to Peter;
but only our Father who is heaven.
Believing in this Scripture, Matt.
11:27, that "`no man (as man) knows the Son, but the Father, nor the Father, but the Son,
and those only to whom the Son does reveal Him`"--I make
these few observations in the forepart of this narrative,
because my manner of living, birth and heritage,
was not according to the faith that I profess at this day.
And as my change from the outward and visible signs (representing God`'s grace to man),
to the inward and spiritual grace itself (typified by these shadows),
was not the result of my own wisdom or will, or that of others,
but arose from the secret manifestations of His divine grace in my heart,
I feel desirous to bear my testimony concerning this
inward revelation of light and truth,
which I fully believe comes from Jesus Christ to redeem those who feel
it and are obedient to it from all unrighteousness and worldly lusts,
teaching them to live soberly, righteously, and godly, in this present world, Titus 2:11,12.
And indeed, this grace not only teaches us,
but is also sufficient to help and deliver us in every needful time of trial,
which a belief in outward ordinances, or the observation of times and ceremonies,
never could accomplish for me, as may be seen in the following relation.

I was born in the city of Dublin, Ireland, in the year 1739.
My parents being members of the Church of England, I was raised up in that profession,
and had the advantage of a pretty liberal education under a clergyman of that way.
After I had acquired some acquaintance with the classics, before I was twelve years old,
I was placed under the care of Abraham Shackleton^
footnote:[Abraham Shackleton was a well-known and
highly-respected elder in the Society of Friends.
He opened a boarding school in Ballitore, Ireland, in 1726,
and continued as head-master until 1756 when the administration of the
school was passed down to his able and pious son Richard Shackleton.]
of Ballitore, where I acquired further improvement in my former studies,
as well as an acquaintance with such learning as was necessary to qualify me for business.
I must not omit a circumstance which attended me there when about thirteen years of age,
being an instance of the merciful visitation of Divine grace to me in early youth,
appearing as a spirit of judgment and condemning those things
which His blessed Spirit has a controversy with.
In company with some of my school-fellows,
I drank some sweet liquor (called Shrub) which overcame me.
After I was in bed some time, I felt strong convictions take hold of me,
which made me sorrowful.
These gradually grew upon me,
and were succeeded by great terrors of death and future judgment,
which caused me to cry out for mercy, and promise never to be guilty of the same again.
My old master came up to my bedside and stood by me till this dispensation subsided,
perhaps about fifteen minutes.
These impressions, though deep at the time, were soon erased,
and I thought very little more about it, being more taken up with amusements.

I was placed apprentice in Lisburn, in the county of Antrim, to learn the linen-trade.
In this situation I had more liberty than I had hitherto experienced.
My intimate acquaintance was with young men about my age,
and having been given a pretty good share of money by my relations,
it led me into amusements to which youth are inclined.
I kept a horse, and was very fond of hunting.
I attended balls and assemblies, to which I was much addicted,
and this led to a desire after fine clothes, which I indulged to an expensive degree.
I was also fond of music, and had a strong propensity for singing and whistling,
which the love of music leads to.
I may say with Solomon,
I gave my heart to know pleasure in most of the shapes which
the sons of men are given to--not as the wise man said,
"`to know what was good for the sons of men;`"^
footnote:[Ecclesiastes 2:3]
no, that knowledge was reserved by the good Shepherd for a future day,
when I was made to see in that light which is superior to the written word,
that these things lead to the chambers of death.
For the lovers of pleasure are not, nor can they be, lovers of God,^
footnote:[1 Timothy 5:6]
as there is no concord between Christ and Belial.
I continued pretty much in these practices and habits
till I was about twenty-four years of age,
when I began to feel my mind oftentimes brought into serious reflections,
which gradually wore away that disposition which had long led me into loose company,
and out from hearing the Divine voice,
which is a still small voice in the secret of my heart.
And to the surprise of many,
some of whom were otherwise valuable members of the community,
I left off my involvement in what were generally termed innocent amusements.

I had lodgings in town, and kept very much at home.
My former companions used to come and tempt me to go with them,
but I refused with such a countenance bespeaking a degree of solidity as surprised them,
and I heard it was reported I was taking leave of my senses,
which occasioned others to come and look at me to see if it were so.
I could not tell how,
but my disposition for singing and whistling (which was a favorite amusement) fell away,
and I think I never resumed it;
and although my upbringing never instructed me to
look inward for that which is only to be found within,
yet I was often led into secret recollection and retirement in spirit,
which led me into a belief (and perhaps some sensible experience)
that "`what was to be known of God was made manifest within.`"^
footnote:[Romans 1:19]
My secret breathings began to be after God,
and these led me to the frequent attendance of public worship.
I very rarely missed receiving the bread and wine,
except I apprehended myself disqualified.
The recommendation not to approach the Lord`'s table,
nor to receive the elements unworthily, lest I should eat and drink my own damnation,
had been a block at which I had long stumbled.
But one day, on that occasion,
I thought I felt restrained from leaving as usual
with those who did not participate in communion,
and in much fear I approached the table and received the bread and wine,
which gave me great satisfaction that I had now received this rite of my church,
and I continued this practice for some years.
I believe I was permitted in this seeking state of mind
to try this ceremony and see what it was good for,
for I was an advocate for the religion of my education,
and I was later told by a dignitary in it that he was always glad to see me in church,
as my deportment there was devout, and he was sorry to lose me.

I was intimately acquainted with several of the people called Quakers,
and had an esteem and friendship for them;
but their pretensions to such refinements in religion, their claim to inspiration,
and their silent meetings with the benefit said to arise from them,
I could not well relish, neither did I at all believe it.
I was of the judgment that the New Testament contained
all that was necessary for man`'s salvation,
but it used at times to baffle me,
how I should put its precepts into practice--in it I found the form,
but where was the power to fulfill?
Oftentimes I did groan for deliverance from the power of sin and death,
and like many of my then fellow-communicants,
I believed there was no redemption from it on this side of the grave.
This settled me down in a degree of ease in the outside performances, which,
like the law formerly, "`did not make those who approach perfect;`"^
footnote:[Hebrews 10:1]
yet to me, I believe, they were made useful to bring me unto the better covenant.

While I was seeking after redemption from sin and transgression, I left the town,
and took a farm, where I have now lived about forty-three years.
I believe this removal was in the ordering of the Lord`'s Wisdom,
as it led me away in a great degree from my former acquaintances and habits.
My spare time was taken up with useful, and to me they were agreeable, occupations;
I farmed and followed my linen business.
I attended the public worship rather more constantly than before,
though about three miles from the meetinghouse,
and thought nothing could shake my opinions which were orthodox in relation to it.
I had not any thoughts of making so important a revolution as to
change or alter the religion of my upbringing--here I was at ease.
But from my frequently retiring into a secret communion in my own heart and being still,
I was gradually led to a close reliance and dependence upon Divine instruction,
not considering that any other body of Christians
made this profession more openly than I did.
Divine Mercy saw me at this time,
as He saw Nathanael formerly under the fig-tree when no other saw him,
and He allowed me to try my own strength in endeavoring to establish my own righteousness,
that by finding myself outmatched in the contest with the man of sin,
I might more readily submit when the time would more fully come to ask
for and receive strength from Him "`upon whom our help is laid.`"^
footnote:[Psalm 89:19]

I usually presented my petitions morning and night
that I might be preserved from temptations and sins,
and very frequently read some portions of Scripture before I went to bed.
The week before I received the elements I usually read the service appointed thereto,
and carefully watched over my words and temper,
that I might receive this rite with some degree of acceptance.
But it was often cause of surprise to me that I felt no additional strength to be derived
from my pretty constant attendance of public worship and the sacrament (so called),
having read and heard of the beneficial effects obtained
from receiving the bread and wine.
For on these occasions (which were to me quite solemn,)
when I retired from what was called the Lord`'s table,
and humbly knelt in the pew to return thanks to God
and pray that it might be blessed to my regeneration,
my prayers even then seemed to be dry and unproductive
of the fruits I was taught to expect from them.
All this was performed in my own strength--"`I said I would be wise,
but it was far from me`"^
footnote:[Ecclesiastes 7:23]--the hair that was by
nature black was not hereby made white,
nor that which was crooked made straight.
Instead of the old man being more crucified than before,
the enemies of my own house kept possession; yet I may say their goods were not in peace,
for I longed to get them turned out, and to be set free from the law of sin and death,
under which I groaned and strove to overcome.

I had a natural irritability in my disposition, which I was very desirous to overcome,
as it unsettled my mind from that state of quiet in which I found rest;
but all the care I used was not sufficient at times to subdue it,
and it was cause of great uneasiness to me when it did rise up.
Yet I was enabled through Divine favor to keep up a fair outside appearance with men,
was not guilty of immorality, was reckoned sober and religious,
and upon these grounds I held a pretty good opinion of my own attainments.

Here I was ready to settle down, and to think I had reached the desired haven of rest;
but this state, I believe, is one of the subtle devices of our grand adversary,
and is a false rest, and not that prepared for the people of God.
In this false rest the enemy will not disturb us;
he will allow us to remain there all our lives,
as I fear too many do--and resting in their own labors, their works will not follow them.
But my merciful Redeemer, who knew the integrity of my heart,
and saw that bread did not satisfy my hungry soul (because I hungered and thirsted
after righteousness which these things did not produce) was pleased to visit
me again and again by the secret touches of His Holy Spirit,
gradually drawing my attention thereunto season after season,
making me acquainted with it as a light in my dark heart,
and as a reprover and swift witness against every appearance of evil.
To this light I gave heed, and rejoiced in it,
but I must say I then knew it not as I have since come to know it.
I believed it was divine,
but my mind being so limited by the prejudices of my upbringing
in favor of that religious profession I was taught to believe in,
I did not look for, neither did I expect to feel _in myself,_
the second appearance of our Lord Jesus Christ without sin unto salvation.^
footnote:[Hebrews 9:28]

My views and expectations were outward, my worship was only in the outward court,
which was trodden by the Gentile spirit.^
footnote:[Revelation 11:2]
I sought for Him without,
whom my soul secretly desired to find--a Savior who
was promised to save us _from_ our sins, and not _in_ them.
Sin had become so exceedingly sinful to me, that my cry at times was, "`a Redeemer,
or I perish;`"--but I found Him not--I was seeking the living amongst the dead,
and the outward law could not make perfect those who draw near.
He whom I was seeking had risen,
and the day was coming upon me that these empty forms and shadows were to flee away.
All my endeavors in my own strength, will, and wisdom, proved ineffectual,
but the Sun of Righteousness was now arising with healing in His wings,
in order to bring forth that life in me which is hid with Christ in God.
And when the day of the Lord`'s power came upon all those things I thought so much of--like
my attainments in a religious life and conduct--it burned as an oven,
and consumed everything of that nature,
that the Lord alone might rule and reign in my heart, whose right it is.
My righteousness appeared to be as filthy rags,
and was not sufficient to cover my nakedness.
I could then say with holy Job, "`Naked I came into the world,
and naked I shall go out,`"^
footnote:[Job 1:21]
and unless You, oh Lord, cover me with a new garment,
this fig-leaf covering cannot hide me from your judgments--which
judgments then began to be revealed in my soul.

I had been in the practice of going occasionally
to the meetings of Friends for years past,
but as my spirit began to long after more durable riches than I had already obtained,
I attended them more frequently; yet cannot say I felt myself much benefited thereby.
For, although I knew the people called Quakers made profession
of a more spiritual religion than other people in this land,
I was not then capable of forming a just judgment of that which
I had only heard of by the hearing of the outward ear.
My spiritual eye had not been then anointed,
by which alone I could see the wonders of the new creation of God,
in and through His dear Son, Christ Jesus.
The time had not yet come that the Lord would enter into His temple,
and the earth would be moved at His divine presence,
who indeed is the Lord of the whole earth, and worthy to be feared, honored, and obeyed!

While I was in this seeking frame of mind, I attended a Province Meeting held in Lurgan.
In the first sitting a Friend spoke upon this portion of Scripture, "`Behold,
I stand at the door and knock: if any man hears My voice and opens the door,
I will come in to him, and will dine with him and he with Me.`"^
footnote:[Revelation 3:20]
I did not find this testimony produced any good effect in me,
for I was built up in a good opinion of the religious profession of my education,
and I did not see much in the lives and conducts of many amongst the Quakers
that induced me to give them much preference over my fellow-professors.
Moreover, I did not comprehend the nature or use of silent meetings.
There was a Friend there from Pennsylvania named Robert Willis,
who I think was silent in that sitting.
Upon Friends gathering into the Meeting for Discipline, I went in,
not knowing the impropriety of it;
and though there were doorkeepers they let me pass
on as they observed a solemnity in my countenance.
During the pause of silence Robert Willis spoke.
What he said I could not tell, for my mind was gathered into inward silence;
but such a power broke in upon me that I was greatly broken into tears,
and my whole body was shaken in an extraordinary manner,
attended by a feeling of divine Life to arise within me.
And though it brought a spirit of judgment with it, yet it left a healing virtue,
so that I then thought I would not be ashamed to
confess to the Truth in the public streets,
let the shame be ever so great.
The cross then was nothing to me when compared with
the treasure which I found hidden in my heart.
I was then determined to sell all,
so that I could gain this pearl which I had been
searching for so long in vain among the rubbish.
Oh, I remember that day, how I did rejoice!
A new song was put into my mouth, even praises to my God!

I do not expect any other but that this statement will be called enthusiasm,^
footnote:[_Enthusiasm_ was a word frequently used at this
time to refer to religious fanaticism or emotionalism.]
or the effects of a disturbed or warm imagination,
by those who have never been acquainted in themselves
with the like happy and blessed experience,
which I call (with respect to myself) the beginning
of the new creation of God in Christ Jesus.
The Gospel, in the days of the first messengers,
was termed "`foolishness`" by the worldly-wise and prudent.
An eminent preacher of it was told that "`too much learning had made him mad.`"^
footnote:[Acts 26:24]
Indeed,
their lives were counted as madness because the life they then lived was in Christ Jesus,
while the lives of those who condemned them were after the flesh, fulfilling its lusts.
On the other hand, I fear there are many who make a profession with me of these things,
and yet do not truly comprehend them;
for we have nothing that is good but what is given to us by God,
and if we are not concerned to ask wisdom from Him, we shall not receive it,
for the promise remains to be to those who ask.
Some among us do ask, but they ask amiss,
asking something from the outward form which it cannot give.
To these states I shall not use any reasoning to strive to convince them of their error,
having the experience in myself how hard, no, I may say,
_how impossible_ it would have been to have convinced me of
these truths until Divine Mercy was extended to me.
But by a simple operation of His power (comparable to the clay and the spittle) He opened
my blind eyes so as in measure to enable me to see the light of His glorious countenance,
and to confess Him before men.
But I write these things for the way-faring man and woman who are traveling to Zion,
and who can read me in their own experience,
to encourage them to hold on their way and to let no discouragements
they may meet with in their wilderness travel,
cause them to look back to Egypt;
for it is only those who hold out to the end that will be saved.

I was now very much reduced to silence, and my spirit oftentimes turned inward,
waiting and looking after Him whom my soul loved.
I thought,
having found Him of whom Moses and the prophets did write--whose
blessed day Abraham saw in the vision of life,
and was glad,
and whose blood of sprinkling speaks better things than that of
Abel--that now the Egyptian bondage of sin was at an end;
which perhaps was the case with Israel formerly,
when Moses brought a message to them from the God of their fathers,
commanding Pharaoh to let Israel go and worship their God.
But spiritual Pharaoh was not to be so easily prevailed against as I thought.
When he found I was for moving out from under his government,
and journeying to the promised land,
submitting myself day after day to the guidance of
the cloud by day and the bright flame by night,
I was closely pursued by him, his horsemen and chariots,
as if they were determined I should not escape from them.
The power with which they were permitted to try me was great,
so much so that I thought there was no power so great,
not having as yet experienced the coming of Him who was stronger than they,
clothed with the power of His Father, to spoil the strong man of his goods, turn him out,
and take possession for Himself.
This is the work of regeneration,
so little known by the worldly-minded professors of Christianity.
This is the glad tidings of the gospel (the power of God),
preaching and teaching liberty to the captive,
and the opening of the prison doors to those who
had been bound by the chains of darkness and sin.
This is not the work of a day,
or of a year--perhaps it may be the work of the greatest part of our lives,
going on towards perfection as the apostle Paul declared,
"`Not that we are already perfect;`" though he had been a preacher of the great
and acceptable year of the Lord in Arabia and the nations round about.
Thus the command of our Lord and Master must be remembered in every stage of our journey,
to "`watch and pray.`"

Oh, the terrors that surrounded me by day and by night,
lest the enemy should overpower me and bring me back to the house of bondage,
now that I had been made a partaker (in some measure)
of the glorious liberty of the sons of God!
One temptation after another was presented to me,
some in the wisdom and guile of the serpent,
others in the blasphemous roars of a lion that were spiritually uttered in my hearing.
But I found by experience that my peace and safety
were found in deep retirement of spirit and silence;
and though the subtle adversary came only to kill and to destroy,
yet his waters turned God`'s mill, and drove me home,
to seek for help where help was laid; and in due time I found it to be there.
Deep indeed were my conflicts,
so that I felt willing to exchange conditions with the laboring poor,
if I might find peace with God and remission of past sins.

In Eleventh Month, 1772, I attended the Half-year`'s Meeting in Dublin.
At this time I had not made any alteration in my dress or appearance,
it was pretty much in the usual way of other people.
In one of the meetings for worship I felt my mind drawn into deep
silence--every outward consideration seemed to be withdrawn,
and a deep solemnity was the covering of my spirit, which I very much gave up to,
having found my strength at times renewed by it.
At this time Robert Willis stood up, and what he delivered I believe I did not then know,
nor have I since,
but I felt my lost state and condition so set before me in the secret of my soul,
that with the anguish of it I cried for mercy;
for I thought the pit was open and ready to receive me,
and all the horrors of it surrounded me.
This visitation of judgment, with the terrors attending on it,
brought me very deep and low in my mind,
but I found the Divine fear to operate as a fountain of life,
preserving me more from the snares of sin and death than the many years of will-worship^
footnote:[Will-worship is a term used to refer to
any form of worship that is according to the will,
time, and resources of man.
See Colossians 2:23 KJV]
I had formerly been in the practice of.
I could now say, from a fearful experience, that my Redeemer lived,
and was a God near at hand and not afar off,
and that He was of purer eyes than to behold sin of any kind with any degree of approbation.
I returned home much humbled, was often in retired silence,
and diligently searched the Scriptures to find some relief to my troubled mind;
and I can bear my testimony to them, that they are the Scriptures of the Spirit of Truth,
given forth by holy men of old as they were inspired of the Holy Spirit;
for I found the same Divine Spirit bearing witness to them in my spirit,
and opening to me counsel and instruction, to my edification and comfort.

It was then that the Lord`'s judgments were revealed in my earth,
that I might thereby learn righteousness.^
footnote:[Isaiah 26:9]
All my sins and my transgressions, which were many, were set in order before me;
it appeared that a book of remembrance had been kept on high,
and that nothing was forgotten.
Oh, the terrors of those days,
when the righteous Judge of the living and the dead sat in judgment in my soul,
arrayed in terrible majesty and power,
not only to search out the most hidden things (as
if nothing was to escape His all-seeing eye),
but I was made livingly sensible that He also had the power to cast into hell.
Day after day uttered speech, and night after night declared knowledge,
that there was no repentance in the grave,
and that repentance and remission must be done in these bodies.
For hours I have been on my knees with uplifted hands, asking for mercy,
and sometimes apparently brought to the brink of everlasting
death before I could feel remission of sin.
My duty to my parents was brought under scrutiny, and I had to make a close inquiry,
in great fear; for they both were dead,
and I had now no ability to make recompense for past wrongs.
But in this I had the peaceful answer to make,
that I had not ever willfully disobliged or behaved undutifully to them.
Oh, you children, let me entreat you, in the fear of the Lord,
"`obey your parents in the Lord, for this is well-pleasing`"^
footnote:[Colossians 3:20]
in His holy sight; and you who act in a light or careless manner with your parents,
and trouble them by your disobedient conduct, I am persuaded of it,
you will have to answer for it in this world, or in that which is to come.

Now, to speak on a subject that such great numbers of people (whom I prefer over myself in
acquired knowledge and natural understanding) place so great a dependence upon,
is hard for me;
yet I cannot easily avoid relating my experience
concerning that formal religious profession I made,
when all my deeds of righteousness (so called) and unrighteousness were
brought before the great tribunal that was now set up in my heart.
I saw that when the true church fled into the wilderness,
and the great red dragon cast out his floods of persecution after her,
there was a place prepared for her there for a time, times and half a time.^
footnote:[Revelation 12:1-7]
Then it was that the wisdom of men got into dominion,
and sat as antichrist in the temple of man`'s heart,
where Christ before had sat and ruled as the Head of His church.^
footnote:[2 Thessalonians 2:3-4]
Then they apostatized from the true faith, which was His Divine gift to His church;
and having lost the light in the darkness of the human understanding,
they set up a form of godliness, denying the only power that can produce it.
And instead of the true and living faith "`which was once delivered to the saints,`"^
footnote:[Jude 1:3]
they established creeds and forms of prayer that suited every state and condition,
thereby turning the people from feeling their own states
and conditions as they really were in the sight of God.
And though men perhaps felt secretly judged for these things,
they were taught to trust in prayers and supplications made
ready for them some hundred years before they were born;
even when the Divine Spirit (who wills not the death of
him that dies) was ready to make intercession for them,
not in a set form of words aptly joined together,
but in sighs and groans which none else could utter for them.

With regard to prayers in a set form being presented
at the throne of grace by unregenerate man,
who is in a state of moral depravity--I am persuaded they are an abomination to God,
and will not meet with His acceptance.
"`First make the tree good, and the fruit will be good also;`"^
footnote:[Matthew 12:33]
but it is Christ alone, the good Husbandman, that can make the tree good,
and then He will eat of the fruit.
I was in the practice, night and morning, of saying prayers in a form,
in as humble a manner as I knew how.
This the Lord bore with in the days of my ignorance; but when in the light,
I saw how will-worship was not acceptable in His holy sight, and had forsaken it,
yet I continued for a time in this practice.
One night, as I was on my knees, I felt such a terror take hold of me,
that I quickly rose,
and never dared afterwards proceed in the same formal manner of praying.

When the true church came out of the wilderness (which she has done in these latter days^
footnote:[Referring to a return to the life and purity of primitive
Christianity experienced by many in the early Society of Friends.]),
she came out leaning on the breast of her Beloved--laying
aside all useless forms and ceremonies that do not profit,
and solely depending upon the immediate teachings of the
grace of God and the revelations of His Holy Spirit.
In this way, antichrist was dispossessed of his rule and government in the church,
and Christ took to Himself His own power and authority to rule and govern,
who also appoints His own servants,
and qualifies them for the several uses and purposes
which He (in His holy wisdom) has allotted,
sending them forth, and telling them, "`Freely you have received, freely give.`"
These seek no man`'s silver or gold, or apparel, but supply their own necessities,
and those of others, by the labor of their hands.

Although I had suffered deeply, as I thought, in the hour of judgment and of burning,
yet those things which I had suffered were only as the beginning of sorrows.
The ground of the heart was not to be lightly turned up.
No, the gospel plough needed to be introduced, the fallow ground broken up,
and I was to sow no more among thorns.
The terrors of God`'s judgments were often set before my mind,
and made such deep impressions upon me as I believe will never be erased.
It is a truth past all contradiction with me,
that the Divine Spirit will not dwell in a temple which
He has not previously cleansed in a great degree.
I speak now to you, my beloved brethren and sisters,
who have in your own experience known your measure of the depths of Satan,
and have been brought out of Egypt with a strong hand and an outstretched arm,
and have known Christ`'s baptism to be with fire and the Holy Spirit.
This is the only baptism which affords "`the answer of a good conscience towards God,`"^
footnote:[1 Peter 3:21]
and cleanses both flesh and spirit.

To relate much more of the inscrutable judgments of God,
which are past finding out except by the experience of them,
may not be needful for me to do at present.
I may say that "`day after day uttered speech,
and night after night declared knowledge.`"^
footnote:[Psalm 19:2]
Quietness succeeded these fearful voices uttered from the mount,
which came not through man nor by man; indeed,
in these things man had no share or portion.
Remission of the past sins seemed to be spoken in this quiet frame,
and a voice that said, "`go and do so no more.`"

I was now brought into the school of Christ,
to be instructed by Him in that inward law which
was to be the government of my future life.
The old wine was poured out, the old heavens were rolled up as a scroll,
and I willingly surrendered them to the fire.
I conferred no longer with flesh and blood,
but gave up to the heavenly vision and bowed down my ear to instruction,
for "`He spoke now as never man spoke.`"^
footnote:[John 7:46]
Instead of "`whetting His glittering sword and laying hold of judgment,`"^
footnote:[Deuteronomy 32:41]
He became my shepherd,
and drew me to follow Him in the new way by the shepherd`'s crook of His love,
sometimes leading me into green pastures and refreshing my poor disconsolate mind.
Then I thought I would joyfully run the way of His commandments and never be weary.
And here I would gladly have made my tabernacle, but I had to go down from the mountain,
and pass through the winter season,
and mourn the absence of Him whom my soul was now taught to love,
for the savor of His ointment was delightful unto me.

The same Divine seed of light and life which led me out of the
forms and ceremonies to worship the Father in spirit and in truth,
also led me by its secret teachings into a straight and narrow
way with regard to all superfluities in dress and speech;
and the same power has preserved me in it to this day,
and I trust will do so to the end--for with Him there is no variation or shadow of turning.
Simplicity of dress and speech is fitting for a humble follower of a crucified Savior.
Many find a cross in the practice of these things,
for they openly declare to others whose disciples we are.
Children of the world, in their foolish and vain hearts,
despise the wisdom of God in these little things,
which are intended to crucify us to the spirit of the world,
with all its pomps and vanities.
These are ashamed of the cross,
and would rather enjoy the pleasures of a sinful world (which are only for a
season) than suffer affliction with the people of God by the scoffings of men.
Although I knew that the Quakers held these testimonies,
and that they were outward marks of communion with them,
nevertheless I was desirous to see and know the ground of them in myself,
and not to embrace anything of such great importance except from a clear conviction
that it was from the living Foundation which God had laid in my heart,
and not from man.

The practice and use of the plain language is consistent with the
rules of grammar and the language of holy men of old,
as the Scriptures bear testimony; yet I was desirous to prove all things,
to bring them to the standard of truth in my heart, and if they stood the test,
then to cleave to them.
When in a state of spiritual infancy, I began to use this language sometimes,
but at other times I did not.
My near kinsfolk, I heard, said I was beside myself,
and it was therefore a cross to speak this way in their presence.
But denying the cross brought sorrow and weakness along with it,
and also a fear that if I went down the steps of Jacob`'s ladder I would find it more
difficult to recover the ground I had lost than to ascend to another step.
The prospect of the glorious crown of righteousness that
was set before me as attainable through faithfulness,
encouraged me to press forward; and as I endeavored to do so I grew stronger,
the yoke became easier and the burden light.
And when through inadvertence an omission occurred (for
after this time I never dared willfully to transgress),
I always felt wounded in my spirit.

The change in my dress was a great cross, as I was always given to fashionable clothes,
and at this time had various suits of apparel of this sort.
I felt a solemn covering to come over my spirit early one morning while in bed,
which drew me into deep silence and attention.
I then felt it required of me to conform to the simple appearance of Christ`'s followers.
His garment was all of one piece; so ought mine to be--of one piece with my speech,
my life and my conduct.
This felt to me a severe stroke; no shelter was now left for me,
but I must appear as a fool to the world.
My speech and then my garments would betray me, that I had been with Christ,
and professed myself to be one of His disciples.
I wept bitterly,
and pleaded the cross it would be to me before my friends and acquaintances,
and the loss it would cost me in my present clothes;
but the Lord was silent before my complaints,
and the leaven worked in the lump until the whole man was leavened into submission.
Then I ran the way of His commandments with joy and alacrity of heart,
so much so that I have heard in passing some people
say they would give their oath that I was a Quaker.
"`Oh!`" says my spirit, "`that the whole family of God were so conspicuous,
even on the outside, that thus it might be clearly seen who it is they serve!`"

Another testimony we hold is,
that we cannot with a good conscience contribute in any way to support the ministry
of any church that derives its maintenance from their service at the altar.
For we believe in this day that Christ is the head of the true church militant,
and that His promise made before He ascended to his Father, "`Lo, I am with you always,
even to the end of the world,`" is fulfilled,
His Divine presence being felt wherever two, three,
or more of His living children are met and assembled in His name.
This being a truth that we fully believe,
we are feelingly made aware that He (the Head of this body) still
qualifies and sends forth servants and handmaids to minister,
first preparing them for His work and service by various dispensations,
baptisms and spiritual washings,
and then handing to them the bread which He has broken and blessed,
so that they have bread to give to the multitude, without any addition of their own.
And these, knowing in whom they have believed,
will neither pay nor receive wages from any man as the price of their labor;
for they are persuaded that He whom they serve is faithful and true,
and having received their ministry without fee or reward, they freely give it,
looking to Him who sent them for their recompense,
which is the sheaf of peace in their bosom.

Upon reading this account, some unbelieving person may ask,
how did I know that the subtle adversary had not put on
the appearance of an angel of light and deceived me?
I answer such a one in the words of our blessed Lord, which are the words of truth:
He says, "`My sheep know My voice, and follow Me,
and the voice of a stranger they will not follow.`"
Moreover we are told to follow after those things which make for peace,
and those whereby we may edify one another.
And truly,
I never found anything but peace as the consequence
of unswerving obedience in these particulars.

I have now given a brief recital of the cause I had to unite in religious
fellowship with those with whom I have since continued to walk.
And though I have been subject to many scoffings and mockings from some of my kindred,
as well as from many others,
I was mercifully enabled not to turn my cheek from the smiter,
but to bear them for His sake who suffered more and worse from sinful and perverse men.
I rejoice and give thanks to my merciful Redeemer,
that He has in mercy called me out from customs I had received,
and has given me a portion in His service and fellowship with His people.
And I write these things hoping they may be blessed
to some wayfaring traveller in the same road,
that they may become as way-marks to them,
and thereby show that this is not an unbeaten path,
but others have travelled it before them, and found safety.

In some of those seasons of deep baptism before related,
it used to spread upon my mind that the Lord had a service for me,
to make use of me in His church and family.
This brought a great fear over my mind,
lest Satan (whose power in deceiving I was now measurably acquainted with)
should put on the appearance of an angel of light and deceive me,
and so I should become a vessel marred upon the wheel.
The preparation of the heart in man,
and the answer of the tongue in this arduous concern, must be of the Lord alone.^
footnote:[Proverbs 16:1 KJV]
Man must give up his wisdom,
and his acquired knowledge must be submitted to Divine direction,
and only such abilities be retained as Divine wisdom may see fit to make use of,
although it may make us appear as fools to those who before thought otherwise of us.
Yet this low state is given to us in mercy, to humble us,
that we may depend upon nothing of our own, or upon former knowledge of doctrines,
unless we feel them renewed in the life and Spirit,
that thereby all our fresh springs in and unto service,
may be in Him our Head and holy high-priest.

What humiliations are necessary to bring us to that
standard where God is pleased to teach of His ways!
And how unwilling are too many to come up to this standard or to be measured by it!
But when His righteous judgments are in the earth, it is then, and then only,
that we are willing to learn righteousness.
In this important engagement it may be said, He leads Israel as a flock,
and brings them oftentimes into green pastures,
and causes them therein to lie down as at noon.
This indeed is a great mystery which the worldly-minded professor of religion knows not,
neither can he, because it is only spiritually discerned by them for whom it is prepared.
This was the case with the disciples formerly, when it was said,
"`Unto you it is given to know the mysteries of God`'s kingdom,
but to the rest it is given in parables.`"^
footnote:[Luke 8:10]
The true ministers go forth "`without money bag or knapsack,`"^
footnote:[Luke 22:35]
without depending on anything but the call to present service.
They do not think that their former experiences,
or the simple concurrence of their brethren and sisters (the laying on of the hands
of the elders) are a sufficient qualification for them to officiate in the church.
Instead, they must wait for the fresh anointing; and if it is not afforded,
then they are silent, and must continue waiting upon their Lord and Master girded,
till He is served.^
footnote:[Luke 17:8]
And these baptized servants are so zealous for the honor of their Lord,
that they neither seek nor receive wages from any other hand but His.
Indeed, they are willing to spend their own,
and be spent in health and constitution in His service,
knowing that when He comes His reward of peace is with Him.

After being near two years in this school of religious experience,
in which I thought I had made some proficiency,
and feeling a degree of justification to follow the dispensation
of condemnation (which also had its glory),
I thought the time was near at hand that I should be called upon to invite others to
come and try for themselves how good the Lord is to those that love and fear Him.
In meetings I used at times to feel the Word of Life dwelling in my heart,
with a flow of living language that seemed to be addressed to various states present,
but I dared not venture to utter it in words;
and I do not recollect I felt any condemnation for not doing so at that time.
In managing my outward business, in the garden and fields by myself,
I have sometimes felt a living language in my heart,
as if I were addressing an assembly of people.
It used to begin so imperceptibly to myself,
that it would be moving or flowing in me some minutes
before I would turn my attention to it;
but when I did, it increased so much as to bubble up like a spring,
which then broke me into tears and left a sweet savor of peace and comfort behind.
These, I believe, were only the first-fruits of the Spirit,
and like a ministration of preparation for the important work of the ministry.
Some, I fear, have mistaken this preparation for the work itself,
and so have been born before their time,
and have not come to be of that use and service in
the church that they were designed for.
The prophet Elijah (I believe) was tried with something
of a similar experience on the Mount,
but was mercifully saved from going forth till he heard the "`still
small voice`" distinctly inquiring of him why he was there.
With some the fire is too hot,
and they flinch from the hour of His judgments before the vessel is fully dried.
These cannot contain the new wine, become leaky, and allow it to run out and be spilled,
to the injury of the family of God and to their own great hurt.
Such should return again to the Potter`'s house, be put upon the wheel,
and learn to become as the passive clay,
willing to be formed and fashioned into whatever vessel
the great Potter may see fit for His own use.

These prospects of service in the church then died away,
though I received much encouragement from some Friends
with whom I travelled in their services for Truth,
as well as by letters from others;
but such encouragements never caused me to exercise a gift I had not as yet received.
I was exceedingly careful over myself, that I should not be a vessel marred on the wheel.
Therefore, covering my head with my mantle, I waited for the still small voice,
which came (I believe) a full three years after this,
but in the meantime I was not left comfortless.
The work of regeneration was going forward,
and living experiences often fell to my lot in my travels,
which were very frequent in this nation, but I think I never once declared them publicly.
I kept carefully to meetings, except when sickness prevented me.
This was a duty impressed on my mind at an early period,
and I think I can say I never allowed the cares of the world to stand in the way of it;
and though I gave up many opportunities by which others amassed large property,
yet I was diligent in my business, procured a sufficiency for my family,
and was enabled to entertain strangers who came to my house.

But when the time was approaching that I should publicly
tell to others what the Lord had done for my soul,
it was preceded by a long and dreary wilderness travel, without dew or rain,
so that I was made willing in this encampment to submit to anything,
if the cloud might be removed from the tabernacle,
and the bright flame once more appear as the signal to move on.
Wonderful indeed are all the Lord`'s ways, and past our finding out,
even by our former experiences.
They are known only by standing still to see the salvation of God.
In this depressed frame of mind I went to a neighboring
meeting where there were to be two women Friends from England.
In the afternoon meeting, I felt the burden of the Word as a fire,
and after resisting it a great part of the meeting,
I stood up with these words which our blessed Lord used when He wept over Jerusalem,
"`Oh!
Jerusalem, Jerusalem, you that kill the prophets,`" etc.,
and then sat down in such peace as I think I never felt before,
which continued the rest of the evening, under a solemn covering.
I accompanied the said Friends in their journey northward,
and did not speak again in public for some weeks, till we came to Ballymurry,
where my mouth was again opened in a short testimony,
and in such great weakness that I often thought there
was scarcely ever a child born in so weak a condition.
In fact, I was so long in finding my feet in the work of the ministry,
that for years after this, when I had a concern to go abroad in the service of Truth,
I attached myself to some other traveling minister,
for I thought myself more secure under their wing.
In this weak state I was mercifully dealt with by the Lord,
for what was given me to say would be repeated in my heart
very many times before I could stand up to deliver it,
and the Friends with whom I travelled were made easy with my company,
so as to admit me willingly.
I can say I had a merciful and good Master to serve,
who oftentimes condescended to the low state of His servant,
and bore with my many weaknesses.

I was received a member of Lisburn Monthly Meeting in the year 1773,
from that to the year 1775, my mind was under deep exercises and various probations,
learning the law that is written on the heart.

[.offset]
+++[+++In the year 1774, John Conran accompanied Esther Tuke (of York) to some meetings,
she being then traveling in religious service in Ireland.
Soon after her return home, she wrote him the following letter.]

[.embedded-content-document.letter]
--

[.salutation]
Esteemed Friend,

I have often remembered you since we parted,
with strong desires that stability and faithfulness may be the girdle of your loins,
and pure wisdom your guide in the path which I trust your feet have been turned into,
which leads through the wilderness and the Jordan to a settlement in the land of promise,
which I doubt not you have at times had a sight of.
Various, according to our different dispositions,
are the dispensations which Infinite Wisdom sees necessary
for us to pass through in this journey from Egypt to Canaan,
but all for this great end: to reduce self, and thoroughly purify from all uncleanness,
both of flesh and spirit, to subdue the evil, make all things new and all things of Him.
Great is this work, and many have known it rightly begun, have entered into the way,
and run well for a time, but one thing or another has hindered them.
Some have been like the young man who came to inquire
of Jesus what further good thing he should do,
and turned away sorrowful at the reply, "`Sell all.`"
Here indeed is the trial.
All the treasure we have--be it our own wisdom, righteousness,
or whatever else--must be parted with, and that innocent, sweet, simple,
child-like state must be experienced which desires the sincere milk of the Word,
that their growth may be thereby.
May your growth be this way, from a child`'s state, to man`'s state, etc.,
and then the great end of the Lord in so remarkably calling you will be answered,
to His glory and your own everlasting peace.
For then will you be formed for Himself, and will show forth His praise.
But beware of notions, my dear friend, and feeding on the tree of knowledge;
it remains to be forbidden fruit which a cunning and subtle adversary presents.
The Lord`'s servants are the poor in spirit, the meek, whose joy is increased in Him,
but who have no might of their own--truly, they have nothing, and can do nothing,
except as fresh strength from Him is administered.

[.signed-section-closing]
Your sincere friend,

[.signed-section-signature]
Esther Tuke.

--

About this time, two women friends, Mary Robinson and Barbara Drewry,
came here in the course of their religious service,
and feeling my mind drawn to accompany them to several meetings in Ulster province,
I did so.
I then went with them to Dublin,
and from there through the two provinces of Leinster and Munster.
As we went forward in our journey,
we were at times favored with a sweet and open conversation,
and permitted to relate many things that I believe were advantageous to each other.
I thought I found my dear friend, Barbara Drewry, often had a polishing effect upon me,
and her remarks upon and corrections of my weakness and faults,
were wonderfully refreshing and comforting, which made me not regret my journey,
which was a truly satisfactory one to me.

On our way from Ross to Clonmell, we were accompanied by several Friends,
some of whom I thought seemed like the ox unaccustomed to the yoke; for their behavior,
though innocent, indicated such confusion and lack of regulation,
that it gave me much pain and disquiet,
and though I used some care to keep still at times,
yet I found their conduct was contagious.
On this and other occasions I have found myself very
much weakened by being in the company of mixed persons,
especially with those who have felt or known little of the Lord`'s discipline in themselves.
And I am ready to conclude, with regard to myself,
that the conversation of such people fastens upon me,
and by giving way to it (by degrees,
and that almost insensibly) I become in measure leavened into a like spirit.
This is a cause of pain and disquiet to my mind--to feel disorder instead of that stillness,
which I esteem one of the safest habitations to dwell in.
I hope this observation may be of use to me,
and produce the merciful effect of warning me to abstain from mixed companies,
and from those whose minds have never been regulated by Truth,
and brought into some degree of order.
I have found, when in company,
that my strength in measure consists in always remembering in whose presence I am,
and thus being careful to watch my lips,
that my conversation be only that which is permitted to me.
When this is carefully attended to, I am often in silence,
which I believe gives strength, and when conversation is brought on in this way,
it is edifying, and leaves a savor on the mind that is refreshing.
On the contrary, I have experienced that a free conversation occasioned by
answering every question asked in such mixed companies,
leads the mind insensibly beyond its proper watch,
and into a variety of subjects with which the regulated mind has no reason to meddle.
And after such a conversation, I have felt myself reduced to weakness, confusion,
and disorder, and at times have been almost ready to faint in spirit.

I arrived in Dublin the 8th of eighth month, where I left my dear companions,
and returned home.
In this journey, I said nothing in any of the meetings, either for worship or discipline,
yet I believe it was a profitable time to me, having my spiritual faculties exercised,
and feeling a further degree of strength and experience afforded
to bear the assaults and buffetings of my unwearied enemy.

At the half-year`'s meeting, the summer of this year,
I fell into company with a young woman, Louisa Strangman.
The first time I saw her at a Friend`'s house, I felt, in silence,
a strong draft of love towards her that was more than natural,
and a secret intimation impressed my mind that she would be my wife.
This I hid in my heart,
and it was nearly two years before I felt at liberty to disclose it to anyone,
waiting (as I apprehended) for the Lord`'s time to communicate it.
In this interval there was a Friend closely addressing her,
but my first impressions kept me easy under it.
And, when I at last felt the way open to proceed,
it was still nearly six years after this before we were married.
This was a season in the Lord`'s hand of deep exercise
and great trial of my faith and patience,
as the prospect I had at first was often totally obliterated; and then,
when it was almost gone, it would again revive with a degree of clearness,
to my great consolation.
I held out to the end,
and was crowned with a wife who proved the richest
earthly blessing I was ever favored with,
a true yokefellow in spiritual as well as temporal concerns,
and who never threw any impediment in the way of my going on public services.
I write these few hints, that in this important and weighty engagement,
we should have our eye turned to the Light of Christ`'s Spirit if we expect
that favor from the Lord--a good wife--who is indeed a crown to her husband!

Among the many inward discouragements from Satan to discourage me from embracing
the new and living way which had now been opened in measure to my view,
was the prospect of great sufferings, perhaps death itself;
and in these times of darkness and the shadow of death, human nature recoiled,
and I was at times brought very low, ready to say,
"`How shall I stand if these things befall me?
I fear I shall surely give way and lose all!`"
But Divine mercy was extended to me, by showing me that what appears impossible to man,
is possible with God.
As I sat in the back part of Lisburn meeting, which was held in silence,
I felt the love of God extended to me in so powerful a manner
as to enable me to dedicate my soul and body to His service;
and under such living impressions I was able to say, "`Do with me, O Lord, what you will,
I am willing to suffer death for your name sake;`"
for death then had no terrors in it for me,
the fear of death was swallowed up in victory.
It was then I could understand in measure the noble
stand that many of the martyrs had made, who,
in opposition to the torments which cruel and unreasonable men had subjected them to,
held fast their integrity.
For I felt in my above-mentioned experience, how the Lord,
by His enlivening and comforting presence, was with them,
even as He was with the three men in the burning fiery furnace,
and crowned them with a crown of everlasting righteousness, eternal in the heavens;
and not only them, but all those who love, honor, and obey the Lord, their righteousness.

[.asterism]
'''

[.emphasized]
John Conran continued a humble disciple and a faithful
minister of Jesus Christ until his death in 1827,
in the 88th year of his age.
Throughout his long and useful life,
he was greatly beloved and esteemed by brothers and sisters in Christ,
though he ever retained a low opinion of both his
spiritual attainments and services in church.
On one occasion he wrote: "`My offerings in meetings, though pretty frequent,
yet are very short, sometimes only a few sentences.
Other dear Friends, to whom I am sometimes a companion, can launch out into the deep,
while I can only keep near the shore with very little sail.`"
But to a remnant whose eyes were open,
it was evident that his inward man grew increasingly living and strong,
becoming like a green and fruit-bearing tree in old age.
The last two or three decades of his life were times
of particular inward and outward afflictions,
arising from a variety of sources.
Near the end of the 18th century,
most of what remained of the Society of Friends in Ireland turned from the Truth,
and regrettably embraced deistical principles and the love of this world.
Meetings in Dublin then became increasingly painful to the living members of the Society,
and true fellowship was scarce.
Moreover, he was deeply tried, first by the sudden death of his only daughter,
followed by the loss of his valuable and much beloved wife.
But through all, John Conran`'s feet remained steadfast on the immovable Rock,
and he faithfully finished his race with thanksgiving and resignation.
