== Chapter II

[.chapter-synopsis]
* 1773+++.+++ His Preparation for the Ministry
* Travels as Guide to Esther Tuke also with Mary Robinson and Barbara Drewry
* His First Appearances in the Ministry
* Accompanies Christiana Hustler and Phebe Marshall.

In some of those seasons of deep baptism before related,
it used to spread upon my mind that the Lord had a service for me,
to make use of me in His church and family,
which brought a great fear over my mind lest Satan,
(whose power in deceiving I was now measurably acquainted with)
should put on the appearance of an angel of light and deceive me,
and so I should become a vessel marred upon the wheel.
The preparation of the heart in man,
and the answer of the tongue in this arduous concern, must be of the Lord alone;
man must give up his wisdom,
and his acquired knowledge must be submitted to Divine direction,
and only such parts retained as Divine wisdom may see fit to make use of,
although it may make us appear as fools to those who before thought otherwise of us.
Yet this state is afforded us in mercy, to humble us,
that we may depend upon nothing of our own, or of former knowledge of doctrines,
unless we feel them renewed in the life and Spirit;
that thereby all our fresh springs in and to service,
may be in Him our Head and holy high-priest.
What humiliations are requisite to bring us to that
standard which God is pleased to teach of His ways!
And how unwilling are too many to come up to this standard to be measured by it!
But when His righteous judgments are in the earth, it is then, and then only,
we are willing to learn righteousness.
In this important engagement it may be said, He leads Israel as a flock,
and brings them oftentimes into green pastures,
and causes them therein to lie down as at noon.
This indeed is a great mystery which the worldly-minded professor knows not, neither can,
because it is only spiritually discerned, and by them for whom it is prepared.
This was the case with the disciples formerly, when it was said,
"`Unto you it is given to know the mysteries of God`'s kingdom,
but to the world in parables.`"
The true ministers go forth without script or purse,
without depending on anything but the call to present service;
they do not think former experiences,
nor yet the concurrence of their brethren and sisters,
(the laying on of the hands of the elders,) a
sufficient qualification to officiate in the church;
but have to wait for the fresh anointing if it may be afforded, if not they are silent,
and wait on their Lord and Master girded, till He is served.
And so godly jealous are these baptized servants of the honor of their Lord,
that they neither look for nor receive wages or hire from any other hand but His;
they are willing to spend their own, and be spent in health and constitution,
in His service, knowing that when He comes His reward of peace is with Him.

After being near two years in this school of religious experience,
in which I thought I had made some proficiency,
and feeling a degree of justification to succeed the dispensation of condemnation,
which also had its glory,
I thought the time was near at hand that I should be called upon to invite others
to come and try for themselves how good the Lord is to those that love and fear Him.
In meetings I used at times to feel the Word of Life dwelling in my heart,
and a flow of language living there, as if addressed to sundry states present,
but dared not venture to utter it in words,
and I do not recollect I felt any discouragement for not doing it.
In managing my outward business, in the garden and fields by myself,
I sometimes have felt a living language in my heart as
if I were addressing an assembly of people,
and it used to begin so imperceptibly to me,
that it would be moving some minutes before I would turn my attention to it,
but when I did,
it increased so much as to bubble up like a spring and break me into tears,
and left a sweet savor of peace and comfort behind.
These were I believe only the first-fruits of the Spirit,
and the ministration of preparation for the important work of the ministry,
and which I fear some have mistaken for the work itself,
and so have been born before the time,
and have not been of that use and service to the church they were otherwise designed for.
The prophet Elijah (I believe) was tried with
somewhat of a similar dispensation in the Mount,
but was mercifully saved from going forth,
till he heard the "`still small voice`" distinctly inquiring of him what he did there.
With some the fire is too hot,
and they flinch from the hour of His judgments before the vessel is fully burned;
these cannot contain the new wine, become leaky, and allow it to run out and be spilt,
to the injury of the family, and their own great hurt.
Such should return again to the Potter`'s house,
be put upon the wheel and become as the passive clay,
willing to be formed and fashioned into such vessels as the
great Potter may see fit and fitting for His own use.
These prospects to me of service died away,
though I received much encouragement from some Friends
with whom I travelled in their service for Truth,
as well as by letters from others,
but they never caused me to exercise a gift I had not as yet received;
I was exceedingly jealous over myself, that I should not be a vessel marred on the wheel,
therefore covering my head with my mantle, I waited for the still small voice,
I believe full three years after, but in the meantime was not left comfortless.
The work of regeneration was going forward,
and living experiences often fell to my lot in traveling,
which was very frequent in this nation, but I think I never once declared them publicly.
I kept carefully to meetings, save sickness preventing me,
it was a duty impressed on my mind at an early period,
and I think I can say I never allowed the cares of the world to stand in the way of it;
and though I gave up many opportunities in which others amassed large property,
yet when at liberty to make use of my time, I was diligent in my business,
procured a sufficiency for my family,
and was enabled to entertain strangers who came to my house.

But when the time was approaching that I should publicly tell
to others what the Lord had done for my soul,
it was preceded by a long and dreary wilderness travel, no dew nor rain,
so that I was made willing in this encampment to submit to anything,
if the cloud might be removed from the tabernacle,
and the bright flame once more appear as the signal to move on.
Wonderful indeed are all the Lord`'s ways,
and past our finding out by even former experiences,
only by standing still to see the salvation of God.
In this depressed frame of mind I went to a neighboring
meeting where there were to be two women Friends from England.
In the afternoon meeting, I felt the burden of the Word as a fire,
and after resisting it a great part of the meeting,
I stood up with these words which our blessed Lord used when he wept over Jerusalem,
"`Oh! Jerusalem, Jerusalem, you that kill the prophets,`" etc.,
and sat down in such peace as I think I never felt before,
which continued the rest of the evening, under a solemn covering.
I accompanied the said Friends in their journey northward,
and did not speak again in public for some weeks, till we came to Ballymurry,
where my mouth was again opened in a short testimony,
and in so great weakness that I often thought there was
scarcely ever a child born in so weak a condition;
I was so long in finding my feet to be able to go alone,
that for years after when I had a concern to go abroad,
I attached myself to some traveller, for I thought myself pretty secure under their wing.
In this weak state I was mercifully dealt with,
for what was given me to say would be repeated in my heart
very many times before I could stand up to deliver it,
and the Friends with whom I travelled were made easy with my company,
so as to admit me willingly.
I can say I had a merciful and good Master to serve,
who condescended oftentimes to the low estate of His servant,
and bore with my many infirmities.

I was received a member of Lisburn Monthly Meeting in the year 1773,
from that to the year 1775, my mind was under deep exercise, and various probations,
learning the law written on my heart.

[.offset]
+++[+++In the year 1774, he accompanied Esther Tuke, of York,
then on religious service in Ireland, to some meetings, to good satisfaction,
who soon after her return home, thus writes to him.]

[.embedded-content-document.letter]
--

[.letter-heading]
From Esther Tuke to John Conran.

[.salutation]
Esteemed Friend,

It will, perhaps,
not be unacceptable to be informed of my safe return to my own habitation,
little more than a week ago, rest seems pleasant after the constant fatigue of traveling,
and close exercise to both body and mind;
but though traveling is attended with many difficulties to me,
yet in remembrance of the help that was afforded,
and the many preservations I witnessed in this long journey,
I can say hard things were made easy, and bitter cups sweetened,
and many favors bestowed beyond my deserts by a bountiful Giver,
who is worthy to be obeyed in the smallest and greatest of His requirings.

I have often remembered you since we parted,
with strong desires that stability and faithfulness may be the girdle of your loins,
pure wisdom your guide in the path I trust your feet have been turned into,
which leads through the wilderness and Jordan to a settlement in the land of promise,
which I doubt not you have at times had a sight of.
Various, according to our different dispositions, are the dispensations,
Infinite Wisdom sees necessary for us to pass
through in this journey from Egypt to Canaan,
but all for this great end, to reduce self, and thoroughly purify from all uncleanness,
both of flesh and spirit, subdue the evil, make all things new and all things of Him:
great is the work, and many have known it right begun, have entered into the way,
and run well for a time, but one thing or another has hindered.
Some have been like the young man who came to
inquire what further good thing he should do,
and turned away sorrowful at the information, "`Sell all`"--here is indeed the trial,
all that treasure we have got, be it our own wisdom, righteousness, or whatever else,
it must be parted with, and the innocent, sweet, simple,
child-like state experienced which desires the sincere milk of the word,
that their growth may be thereby.
May your growth be this way, from a child`'s state, to man`'s, etc.,
then will the great end of the Lord in so signally calling you be answered,
to His glory and your own everlasting peace; for then will you be formed for Himself,
and will show forth His praise.
But beware of notions, dear friend, and feeding on the tree of knowledge,
it remains to be forbidden fruit which a cunning subtle adversary presents;
the Lord`'s servants are the poor in spirit, the meek, whose joy is increased in Him,
who have no might of their own, have nothing, and can do nothing,
but as fresh strength from Him is administered.
Your sincere friend,

[.signed-section-signature]
Esther Tuke.

--

Two women friends, Mary Robinson and Barbara Drewry,
came here in the course of their religious service,
and feeling my mind drawn to accompany them to
several meetings in this province +++[+++Ulster,]
I did so; and went with them to Dublin,
and from there through the two provinces of Leinster and Munster,
of which journey the following are some extracts:--

1775--Sixth Month 12th.--I went to meeting at Hillsborough, with my dear friends,
B+++.+++ Drewry and M. R., and unexpectedly during the ministry of B. D.,
apprehended myself called upon to proceed with them, which I did to Stramore, Moyallen,
Lurgan, etc.
+++[+++After speaking of a fear possessing his mind lest by engaging
in this journey he should be running in his own strength,
and incurring the censure of some of his friends,
he relates that on the road these cloudy feelings seemed to be dispelled,
and peace restored to his mind, and says]
I hope I am thankful that I was preserved, willing to give up to the Master`'s requirings,
though I left my business and family unprepared for such a journey,
but I was preserved pretty much in resignation.

20th.--While in Newry I met with some people of business,
with whom I had some conversation, which I thought left me weaker;
upon leaving the town I felt a temptation in myself almost to deny my profession,
and was quite ashamed of the company, plainness, and simplicity of myself and friends,
which I told them of; and a lesson may be read in this to myself and others,
how they or I hold too close a connection with the world, or the things thereof,
which weaken the hands of the sons of Zion.
We went forward in our journey,
and were at times favored with a sweet and open conversation,
and permitted that freedom in it as to relate many
things that I believe were advantageous to each other.
I thought I found my dear friend, B. Drewry, often had a polishing effect upon me,
and her remarks on and corrections of my weakness and faults,
were wonderfully refreshing and comforting, which made me not repine at my journey,
which was a truly satisfactory one to me.

In our way from Ross to Clonmell, we were accompanied by several Friends,
some of whom seemed, I thought like the bullock unused to the yoke; their behavior,
though innocent, indicated such confusion and lack of regularity,
that it gave me much pain and disquiet,
and though I used some care to keep still at times, yet the contagion was catching.
On this and other occasions I have found myself
very much weakened by being in mixed companies,
especially those who have felt or known little of discipline in themselves;
for I am ready to conceive, as it regards myself,
that the conversation of such fastens upon me, and by giving way to it, by degrees,
and that almost insensibly, I become in measure leavened into a like spirit,
which is a cause of pain and disquiet to my mind--to feel disorder instead of stillness,
which I esteem one of the safest habitations to dwell in.
I hope this observation may be of use to me,
and the effect produced a merciful warning to abstain from mixed companies,
and from those whose minds have never been regulated,
and brought into some degree of order,
as my strength in measure consists (when in
company) in remembering in whose presence I am,
and carefully to watch my lips, that my conversation may be known to be permitted to me,
and to attend to the pointings in my mind for that permission.
When this is carefully attended to, I am often in silence which I think gives strength,
and when conversation is brought on in this line, it is edifying,
and leaves a savor on the mind that is refreshing.
On the contrary,
I have experienced that a free conversation promoted by
answering every question asked in such mixed companies,
leads the mind insensibly beyond the proper watch, into such a variety of subjects,
the canvassing of which the regulated mind has not any business with;
after such a conversation, I have felt myself reduced to weakness, confusion,
and disorder, and at times have been almost ready to faint in spirit.

Eighth Month 3rd.--Meeting at Ballinakill.
The same sort of dryness and barrenness, was experienced here as in other places,
which makes me ready almost to conclude the fault to be in myself,
and that I am denied that sense of feeling, which I formerly had,
for some reason which Wisdom can unravel,
not being conscious of any falling away on my side; but the great Master knows best,
therefore may His will be done.
This meeting was held in silence,
and pretty many strangers were at it and behaved themselves well.

6th.--Monthly Meeting at Mountrath.
How shall I be able to express the feelings of the visitation I had last night!
I believe none can conceive it, but those who have experienced the like.
To be admitted to a freedom, if I dare say so, of communing with the Great Master,
the Beloved of my soul, of asking favors and questions;
and the glow of love and favor that surrounded me for about an hour,
I think I cannot express suitably.
Surely I never can do enough for so good and kind a Master,
and hope I shall never be tired of running His errands,
and that He will be pleased to give me strength
to give up all for His great name`'s sake.

+++[+++He describes the meeting as having been one of close and deep exercise,
but that through favor the cloud which seemed to envelope it, was gradually dispelled,
light broke forth, and the testimony of Truth,
rose above the dark spirits of some of the people,
and after relating a part of B. D.`'s weighty communication therein,
goes on to say]--the Friend observed in her testimony,
that a heavy or dark cloud hung over this nation,
and that a sifting day would be afforded to the people,
when the foundations of many would be tried,
and that none would stand but those which were laid on the Rock immovable,
the everlasting Rock, which was Christ.
That whether they would be tried by the sword, by the famine, or the pestilence,
she knew not, but that many would in the day of trial,
find their covers too little for them,
and that the chaff would be separated from the wheat.
These prophetic warnings I have heard more than once,
and have felt them sealed in my mind,
and if I may compare the state of the Lord`'s visited ones,
to the present state of the church and society in this nation,
we often find trying dispensations are afforded to the
visited to cause them to draw nearer to Him,
whom they have always experienced to be a ready help in the day of trouble.
And if the church and people are tried with outward persecution,
it may be a means of making them draw near to Him who is willing to draw near to them,
since they will neither hear the reproofs of instruction inwardly nor instrumentally.
I think Truth was triumphant over darkness in the meeting,
which was a comfortable experience to my hungry and thirsty soul,
which had in many meetings been baptized in the cloud, into death and darkness.

Eighth Month 8th.--Arrived this morning in Dublin, where I left my dear companions,
and returned home.
In this journey, I had not anything to say in any meeting, for worship or discipline,
yet I believe it was a profitable time to me, of improvement,
having my spiritual faculties exercised,
and a further degree of strength and experience afforded to
bear the assaults and buffettings of my unwearied enemy.
Some thought I had better learn this at home;
but we are differing in our spiritual constitutions, as in our natural,
and the treatment for one does not answer for all.
I was drawn forth to this journey I apprehended by the great Physician,
on the approach of the great linen market in Dublin, the profits of which I resigned,
and left my goods at home to the disappointment of my customers who wanted them;
and if I lost that advantage, I had the rich reward of peace in my bosom.

At the half-year`'s meeting, the summer of this year,
I fell into company with a young woman, Louisa Strangman;
the first time I saw her at a Friend`'s house, I felt, in silence,
a strong draft of love more than natural,
and a secret intimation impressed my mind that she would be my wife;
this I hid in my heart,
and it was nearly two years before I felt at liberty to disclose it to any one,
waiting as I apprehended the Lord`'s time to communicate it:
in this interval there was a Friend closely addressing her,
but my first impressions kept me easy under it.
And, when I felt the way open to proceed in it at that time,
it was nearly six years after this before we were married;
this was a season in the Lord`'s hand of deep exercise
and great trial of my faith and patience,
as the prospect I had at first was often totally obliterated,
and when these would be almost gone, it would again revive with a degree of clearness,
to my great consolation.
I held out to the end,
and was crowned with a wife who proved the
richest earthly blessing I was ever favored with,
a true yoke-fellow, in spiritual as well as temporal concerns,
and who never threw any impediment in the way of my going on public services.
I write these few hints, that in this important and weighty engagement,
we should have our eye turned to the Light,
of Christ`'s Spirit if we expect that favor from the Lord, a good wife,
who is indeed a crown to her husband!

In the many discouragements inwardly from Satan,
to discourage me from embracing the new and living way,
which had now been opened in measure to my view, was the prospect of great sufferings,
perhaps death itself, and in these days of darkness, and the shadow of death,
human nature recoiled, and I was at times brought very low,
ready to say "`How shall I stand if these things befall me?
I fear I shall surely give way, and lose all!`"
But Divine mercy was extended to me, by showing me that what appears impossible to man,
is possible with God.
As I sat in the back part of Lisburn meeting, which was held in silence,
I felt the love of God extended to me in so powerful a manner,
as to dedicate my soul and body to His service,
and under the living impressions of it to say,
"`Do with me, O Lord, what you will, I am willing to suffer death for your name sake;`"
for death had then no terrors in it for me,
the fear of death was swallowed up in victory.
It was then I could account for the noble stand the martyrs made, who,
in opposition to the torments which cruel and unreasonable men had subjected them to,
held fast their integrity; and I felt from my experience of the foregoing,
that the Lord by His enlivening and consolating presence was with them,
as He was with the three children in the burning fiery furnace,
and crowned them with a crown of everlasting righteousness, eternal in the heavens;
and not only them, but all those who love, honor, and obey the Lord, their righteousness.

I stayed about home I think in the year 1776,
but was diligent in attending meetings at home, and the national half year`'s meeting.
In 1778 and 1779, I was not much from home on Truth`'s account;
I attended some meetings with Samuel Spavold, Isaac Gray, and Thomas Carrington,
to my satisfaction.
There was a national visit appointed by the Yearly Meeting in London,
to the Monthly Meetings in Ireland, which was pretty fully performed by John Storer,
John Townsend, Thomas Corbyn, Joseph Howe, and James Backhouse,
to pretty good satisfaction.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Greer to John Conran.

[.signed-section-context-open]
Stockton, Fourth Month 17th, 1780.

[.salutation]
Dear John,

As I have passed along from place to place in this country,
I have more than once remembered your request that I would write to you,
and having a little leisure this evening, I sit down for that purpose.
I got safe to Scotland on Third-day evening; next morning I set forward for England,
took a meeting at Sackside, on the First-day following,
and in the course of that week got through the meetings in Northumberland,
and attended their Quarterly Meeting.
In those parts I found a living remnant in our Society,
as well as great openness amongst many of those not in membership with us,
many of whom flocked to meetings, whose appearance at first rather filled me with fear,
but like a much greater instrument formerly, I was soon given to see my mistake,
and that the Lord had a seed amongst them,
to whom the Gospel must be preached in its own unmixed purity.
My heart was indeed humbled from meeting to meeting,
under renewed sensations of the wonderful workings of the God of all grace,
who is able through weak, very weak, instruments,
to carry on His great and glorious work;
may a due sense of His manifold mercies to my soul, ever be the covering of my spirit!

On the 8th of this month, I got to Newcastle, where is a pretty large body of Friends,
and where our worthy friend Mabel Wighani, and three other public Friends live;
but notwithstanding there are several valuable Friends in that place,
I did not fare as well there as among the poor mountains in Northumberland;
yet was favored with an open door amongst them, both in the fore and afternoon meetings;
but experience has taught me, that even in those places,
where the people are favored with a living ministry, by their calling for,
and relying upon help from the servants,
they fall away from the life of religion in themselves,
by forsaking the free Fountain of living waters,
and hewing to themselves cisterns very liable to be broken,
and at best can contain no living water,
but what they immediately receive and scatter at the word of command;
the utmost intention of which is,
to direct the enquiring mind to the Fountain of light, life and wisdom in themselves,
that great mystery hid from ages, but now mercifully revealed,
Christ in His people the hope of their glory.

From Newcastle I proceeded to North Shields, their Monthly meeting being there next day,
from there by Sunderland, Shotton, Durham, Auckland, and Staindrop meetings,
I got to Darlington, and stayed over their two meetings yesterday;
as I mentioned before I have abundant cause to
be thankful that Best Help has not forsaken,
but from meeting to meeting, and also at many other seasons, has been felt near,
to the comfort and strengthening of my mind to pursue the line
of duty which opened in prospect before I left home.
Having now got through this country, I purpose going into Yorkshire tomorrow,
and taking about eighteen meetings in that county, which lie nearest the sea-coast,
and then set my face towards London, if enabled to do so.
I may inform you, I have been poorly in health ever since I got into England,
occasioned by the exceeding cold weather, and high east wind with snow;
but through mercy, I have hitherto been enabled to get along, without any loss of time,
or pain in riding, save when the cough comes on,
and I trust I shall be enabled to get through the rest of the journey in the same manner;
having renewed cause to believe I am under the
care of Him who numbers the hairs of the head,
and without whose notice a sparrow cannot fall to the ground.
And notwithstanding He in His wisdom tries the faith of His depending children,
in order to enlarge their experience,
and thereby further qualifies them for the labor and service of the day,
yet will not forsake those whose dependence is singly fixed on Him,
and have no confidence in anything but the all-sufficient
help of that Arm which brings salvation.

With dear love to yourself,
and any inquiring friends to whom you think it will be acceptable,
I remain your loving friend,

[.signed-section-signature]
Thomas Greer.

--

In the year 1780, I joined Christiana Hustler and Phebe
Marshall in the course of their religious service,
and continued with them throughout from Lurgantill they
took shipping the following Second Month at Dublin;
I passed through many exercising baptisms,
occasioned by weakness and fears in the exercise
of a small gift I had received in the ministry,
in which their company was serviceable to me.
I left home Sixth Month 2nd, to join the Friends at Stramore,
under a full persuasion that it was my duty to do so:
let none think I had not necessary avocations to call me to another line,
for our great linen fair in Dublin was within a few days of commencing,
and though I was assisted by having orders for some of my goods,
yet I had a considerable share left on hand to sell,
and that the most unsaleable part I suppose;
the appearance of these things was troublesome to me,
but I was mercifully helped through this difficulty.
I wish Friends may deal gently with those who may feel these puttings forth,
especially where their conduct in most respects is orderly;
for the exercise the enemy is permitted to raise against these things is very trying,
and if they have also to feel unskillful dealing, it may crush the broken reed,
and lay it aside for a long season under great discouragements, as unfit for service.
I trust I have a degree of thankfulness, and desire a greater share of it,
to my merciful, kind and good Benefactor,
who I believe not only required this offering at my hands, which costs me something,
but also put it into the hearts of His people to make way for me;
for my dear and beloved brethren of our province seemed
willing to trust me out that I might not be lagging behind,
and a tendering time it was to my spirit in mentally
bidding them farewell on my quitting Castle Shane;
though they were not present, yet I had a tendering and affecting feeling of them,
in that one Spirit which I believe unites all those at times who drink of it.
Oh! my beloved friends, I most tenderly saluted you,
and longed for the prosperity of our Zion, and you in particular:
I was concerned for you that none of you might receive hurt or damage,
and in the springings of that ancient fountain, that cannot be drawn dry,
I thought I could have saluted you in an endearing epistle of gospel love:
thus did my spirit drink of the cup of brotherly love while I travelled along,
which was a comfort and consolation to me,
and I could say many things to entice others to come and try for themselves,
how good and kind the Lord is to those who love and fear Him.

The family visit not being quite finished in the
bounds of Moyallen meeting when I arrived,
I had to join the Friends concerned therein in the remainder,
as I had also to do in the greatest part of Lurgan meeting;
I had a few words handed to me, at times, in some of the sittings, as I apprehended,
to drop amongst us, which I did in fear,
and kept as near to the opening as I thought I could,
and was at times favored with the wages of obedience.

30th.--At Ballymurry: after I had sat a short time in the meeting,
I felt a burden on my mind,
which increased to be so weighty as to be difficult to sit under;
I remained in degree still, when I felt some matter to appear before me,
which grew more clear and distinct, and seemed to press for utterance.
I reasoned with it till it passed away, when growing afraid,
remembering the long forbearance of a merciful Creator,
I entreated if it were a requiring that came from Him,
that He would be pleased to renew the same matter afresh on my mind,
and that I would take that as a confirmation.
It was pretty immediately renewed as fresh as I could desire, but the fear got up,
and I had almost reasoned it away again; when I stood up, and before I spoke,
I felt like a little fire to kindle in my breast, and uttered these words,
"`The Lord has lifted up an ensign to the people, and a standard for the nations,
the standard of truth and righteousness-- keep faithful to your testimonies, Friends,
and measure yourselves by this standard,
and let each individual of you come up to his measure:`"
my mind has been favored with rest and comfort since.

Second Month 2nd.--Meeting at Moate.
I went to this meeting which was large, in a good degree of fear,
having been known there formerly, making a different appearance to my present.
After my dear friend Phebe Marshall had sat down the second time, I stood up,
and in great fear declared, "`Oh! that the people were wise,
that they would consider this, and remember their latter end.
Friends, take not up your rest in your earthly possessions,
for it is a false rest--a polluted rest; but turn unto the Lord,
for in the trying day He will be as a staff of support to those who lean upon Him.`"
After I sat down, my beloved friend Christiana Hustler stood up,
and declared that these words which had been repeated in their hearing,
had been the companion of her mind for a considerable time.
"`Oh! that the people were,`" etc., and recommended the advice given.
Then dear P. M. stood up and declared something of a like nature,
which gave me much consolation to find the unity of my beloved friends.
The covering of my spirit was comfortable,
heightened by the fear I was in of taking away with me what I had dropped,
which had tended to my own peace, and was fresh cause of renewed gratitude.

3rd.--Meeting at Birr, which to me was a very hard painful one.
My dear friends had frequently pressed me to sit beside them in these small meetings,
which I was not easy to give up to, and almost always avoided it,
being afraid of offending some one by so doing, which made it a cross to me.
In this meeting I was brought under an exercise on this account that
was distressing to me and under the weight of it I made covenant,
that, if I were forgiven, I would use my best endeavors to come up in that requiring,
though I felt it a very bitter cross, and thought it hard it should be required of me.
I here found I was too neglectful of the advice of my friends,
in these or like small occasions, and that I was preferring my own judgment,
or stiffness, or fear of man, to their feelings.

6th.--Meeting at Mountrath.
+++[+++After alluding to a trying conversation that he
had with a Friend before going to meeting,
relative to his traveling, and which brought him into a very painful situation, he says+++]+++
This journey so far has been of considerable service to me,
as I apprehend I have acquired a greater knowledge of men than I possessed before,
which has already had a good effect on me,
so as measurably to remove that fear of man which I believe too much possessed my mind,
so as to hinder my journeying forward, to my own hurt.
The meeting I can hardly describe,
from my own feelings having been so broken down before it,
but I believe I can say there was a Hand of favor stretched out towards me in it,
having to sit the greatest part of it in a still quiet habitation,
feeling my wounds to be bound up, and wine and oil to be in a small measure poured in,
so as to confess Him to be the tenderest of parents and best of masters.
Yet I believe my dear friends and fellow-laborers had to sit where the people sat,
which I dare venture to say was not in heavenly places in Christ Jesus!
Oh! the threshing-instruments! they were used to thresh the
dry and barren mountains of a long and empty profession;
yet I believe they did not come down,
but rather that they thought they were too hardly treated,
their maladies were not as bad as they were represented,
therefore it was to be feared the cure would not be so readily perfected.
(The meeting held near five hours) and the Friends had I
believe to pass through near three hours of painful silence,
the spring lay so low, and nothing to draw with; the rubbish so great,
and few faithful laborers to lay their shoulders to the burden!
Oh! you faithless generation, what will you do in the end?
Will your being the children of faithful Abraham
work out your salvation? It is sorrowful,
painfully sorrowful, to behold these things,
and I wish I may be mistaken in judging a spirit that I believe would
be ready to cast stones at the servants if they could.

Seventh Month 9th.--Meeting at Limerick.
I was much afraid for some time before I reached this city,
as thinking it to be a large meeting and fearful of having any thing laid on me in it.
After some time of waiting, I thought a little matter arose,
which from the weak state I felt myself in, I believed I could not give up to,
therefore carried it away with me,
which brought me under a considerable weight and burden.
My dear companions had not much service in the forenoon meeting.
The same requiring attended my mind in the evening meeting,
and became so extremely weighty, that after a painful state of waiting,
I gave up to it in a broken stammering manner,
which was more clearly and better explained by one of the friends taking it up,
to my great consolation.

12th.--Meeting at Clonmel.
I am afraid a spirit of earthly-mindedness too much prevails in too many here,
which fetters the mind, and prevents it seeking after better enjoyments:
a state of resistance of the clay in the hands of the great Potter was treated with,
and the danger of standing out compared to rebellion, which is as the sin of witchcraft.

16th.--Waterford meeting.
After we had settled down into silence at +++_______+++'`s in the evening,
a little matter came before me in a very lively manner,
which I reasoned with till it left me,
and I never could see it any more in the light though I earnestly entreated for it,
and in room thereof I was filled with doubtings and fears,
and suffered a good deal of distress of mind.
But after A. B. had opened his mouth my convictions reached me,
that I had been unfaithful in not giving forth that which had been handed to me,
the holding back of which, I believe, stopped the spring in others,
and was the cause of my punishment, which brought me into a sincere repentance,
and I hope will be a warning to me to be more careful for the future.
There is great danger in being too hasty in offering, as well as too slack-handed,
which leads me into fear of erring on either hand;
but I hope for preservation as I remain in the child-like simplicity,
either to move or stand still, as I find faith to believe it is required of me.

Ninth Month 21st.--Meeting at Athy, pretty select with the Friends of that meeting.
When we were here, before, near the close of the meeting,
I found it pretty strong on my mind for some time to request Friends to stop,
as there were some of other societies present, but was backward and did not,
and I thought this was the cause of our return here.
I could have wished at some places Friends would not invite their neighbors,
unless particularly desired;
I was pained at times on that account to see them so indifferent,
giving away to others that bread they had occasion for themselves,
as the course of the testimony, I thought,
frequently turned from the household to those who were without.

[.embedded-content-document.letter]
--

[.letter-heading]
From Esther Tuke to John Conran.

[.signed-section-context-open]
York, Twelfth Month 21st, 1780.

[.salutation]
Dear Friend,

Your great and unexpected kindness in giving me so satisfactory an account
of yourself and my beloved friends Christiana Hustler and Phebe Marshall,
demands my grateful acknowledgment.
I received it a few days ago, when I was about acknowledging some of my transgressions,
or omissions, to my honored friend, Richard Shackleton,
and also inquiring concerning our dear friends,
who have been long the almost constant companions of my mind.
Though writing is now more than ever an irksome task, and what I do very little in,
except to my own family connections, and where duty absolutely requires it; yet,
feeling my heart afresh warmed in the renewal of that love, which, though ancient,
is ever new, I thought I would not let slip this opportunity of saluting you therein,
and wishing you well on your way.
I doubt not but your conflicts have been many, as you well describe,
in a waste howling wilderness in which I trust the carcass is
fallen which cannot inherit the promised land,
new desires and pursuits given, and the kingdom received as a little child;
in that state of simplicity and innocence may you grow up to more advanced age,
be more and more useful in your day, and brightened and strengthened with use,
is my sincere desire.

Though I feel as if my traveling days were near over, yet I may say,
of a truth if ever such a thing should be required as to see your land again,
I should be glad to be sheltered under your roof,
where I well remember I sensibly felt the Son of Peace to be.
I hope several of you will come and make some returns for labors, which,
from year to year,
our friends have to bestow--that going from house to house is trying work indeed,
but the wages will be adequate, which I trust you and your companions have,
and will experience, and that they will be returned to us again,
when the Master has said "`It is enough.`"
If this reach your hand while you are laboring together,
salute them affectionately in my name, it seems all the mite I can cast in,
feeling too much covered with the stuff to be fit to converse with those engaged in war.
I hope to meet you and our worthy friends, Mary Ridgeway and Jane Watson,
at our Quarterly Meeting at Leeds next week; perhaps, I may get my coat brushed,
or get on a better, and be more fit to converse with my friends.
M+++.+++ Ridgeway`'s service is very great, her ministry deep and searching;
they are renewedly united to the living remnant of the Lord`'s people,
who are thankful He still continues thus to visit.
Our worthy friend M. R. seems to have brightened through her recent afflictions,
as if she had fully experienced passing through the refining pot for the silver,
and furnace for the gold, and had come out pure.
We had almost lost hope of seeing that great good man, Samuel Neale,
and his armor-bearer, but it revives a little through your hint concerning them.
I love your companions so well as to desire every help
and comfort for them consistent with the Master`'s will.
My dear companion and sister in the new relationship, C. H., and I,
have been in some degree like bone of one bone, from our youth up,
and I have often been more gratified in her enlargement in spiritual gifts than my own,
and our love and near unity, I believe, will never here have an end.

I have not time for enlargement, such as I have, and the best I have, I give you,
which I could wish better, but as you are now at school, and day unto day utters speech,
and nights teach knowledge, and not only taught by the Master,
but constantly under the eye and nurture of His servants, (your acknowledged mothers),
though I am apt enough to teach, I hope to know my place better than to intermeddle,
for if I had the true oil and poured it forth, it might justly be queried,
"`Why was this waste made?`"
I was glad of your hint concerning James Christy,
though I am far from thinking I merit the name of mother to so honorable a son;
my sentiments concur with your pertinent remark, which felt to revive strength,
to give them a little hint or two of what had long laid upon my mind.
I know not what can excuse my great enlargement,
after a pretended conclusion (contrary to the advices),
but that the worldly spirit +++[+++alluding to an order she gave J. O. for Irish linens, etc.]
which is often first, if not last, with many, and had need be thought of by me,
never came into my mind till I was about to finish; however, if you have no better,
and are still so well disposed as to wish a subject to write to me upon,
I have furnished you with one, perhaps to my own profit as well as pleasure,
as I shall be glad to hear from you at any time and on any occasion,
being with the salutation of love, in which my husband and Henry unite,

[.signed-section-closing]
Your affectionate and obliged friend,

[.signed-section-signature]
Esther Tuke.

--

1781.--Second Month 1st. We arrived at Dublin,
before and since which I have been under a considerable weight of exercise of spirit,
having had a view of visiting the families of this meeting,
which at times brought me very low,
and I got very much discouraged in looking how it might be with me when I got home,
lest I might meet with discouragement from one and another Friend;
and I was led through the appearances that were presented to my view,
to doubt the foundation and almost the whole of my proceedings in the ministry,
which cast a great damp upon my spirit,
so far that I thought I would scarcely again venture to move in that service,
or if I did, that my way might be so blocked up as to shut me up in silence.
I went to bed one night much under these discouraging reflections,
but in the morning I thought a language livingly opened in my mind of this import,
"`To do that, day by day, that appeared to me to do,
and not to be looking too far forward to things that may or
may not happen;`" this dispersed these gloomy clouds,
and my spirit was engaged in the thankful acknowledgment to
the Lord for this His merciful relief from the discourager.

I write these few things that I may remember the Lord`'s gracious dealings,
and that I may be mindful not to be considering what men may say of me or concerning me,
but be watchful and mindful after the work and business of the present hour and day.
I thought, as I lay under this comfortable feeling,
that I felt myself in a good degree set free from this city,
and hope I shall continue so,
and the little view I had of getting home soon seemed
to open before me with considerable satisfaction.
I took a last farewell on the 8th of Second Month of my
very dear and much respected friends and companions,
in whose company I had had many close baptisms,
also many comfortable seasons in which we were favored
to drink together of the same cup of blessing;
it was a time of painful trial to my feelings, through which I was mercifully supported,
and could say on my return home,
that I neither regretted the time nor the expense of this journey,
which was considerable.
I was favored to reach home safe, and to find all things generally well,
after being absent about eight months in the whole.
