== Chapter III

[.chapter-synopsis]
* 1782+++.+++ Attends the Yearly Meeting in London
* Joins Robert Valentine and John Hall in visiting Leinster and Munster provinces
* His marriage
* Visit to the families of Ballyhagen and Ballinderry meetings.

In the year 1782, as I sat in the Half-year`'s Meeting for business at Dublin,
I felt a warm impression on my mind to attend the ensuing Yearly Meeting in London,
and taking the advice of two ministering Friends of our
province they encouraged me to give up to it,
which I did, and was well satisfied with going.
I thought the settling of the Book of Extracts brought
an exercise over the weighty part of the meeting,
which was borne down for some time, by some light and frothy speakers;
but in the end Truth was in dominion, and the meeting ended well, and I may say,
I returned with a sheaf of peace in my bosom.

Soon after I came home I visited most of the meetings in Leinster,
with Thomas Dobson and John Foster;
and in Tenth Month I accompanied Robert Valentine from Pennsylvania,
and John Hall from Cumberland,
in their visits to parts of Leinster and Munster provinces,
having obtained a certificate for that purpose.
I joined them at the Province Meeting at Mountrath, Tenth Month 12th and 13th,
where that doctrine was declared, that the parents had eaten sour grapes,
and the children`'s teeth were set on edge.
The forepart of the meeting next day was cloudy,
but there was a door of utterance afforded,
and I hope a door of entrance to some of the children.
In a select opportunity with the particular meeting,
I had to remind them of the state of Israel when Balaam was hired to curse them--
they were dwelling in their tents-- no divination could prevail against them;
but that now Israel fled before their enemies,
because some had coveted a wedge of gold and the Babylonish garment,
and that they were found in the tent.

16th.--Meeting at Athy:
here I experienced a deep baptizing season in poverty and silence,
in which I received great instruction in reverence of spirit.
Godliness is indeed a very great mystery,
which is to be known only by that revealing power in the heart.
My dear friend, Robert Valentine was well concerned here.

11th.--Meeting at Ballitore:
I felt that way which the apostle called a more excellent way opened in my mind,
and had to recommend it to Friends as that which
recommends all our works to Divine acceptance;
I was followed by Robert Valentine in a lively testimony with
similar remarks--it was a time of some favor.
Since I left my habitation my way in religious meetings has been, I have thought,
much in the cloud; nevertheless, through unmerited regard,
I have been favored to be pretty closely baptized into the states of the meetings,
and sometimes enabled through deep wading and poverty to express a little of my concern,
in that manner which is as foolishness with weak unenlightened man,
yet to a faithful remnant is found to be in the wisdom of God,
and by the power of God subjecting to Himself that in us which would desire to reign.
May I be reverently thankful for this favor also, of seeing myself in this true light,
that without His holy horn of power I could do nothing to His praise or my peace.
I am also favored with the evidence of peace in these mortifying labors.

20th.--Meeting at Kilconner: a low time,
yet through Divine favor ability was given to
set the testimony of Truth over wrong things.
After dinner at a Friend`'s house we had a pretty open opportunity,
in which I was concerned to show the subtle workings of our great enemy,
in the mystery of iniquity, leading the children of men captives at his will,
when they are not found walking in that light in which only he can be discovered;
in some appearing as the king of the locusts ascending from the bottomless pit,
and in the smoke thereof clouding the understanding,
so as to put light for darkness and darkness for light;
raising up the reasoning part in others so as to doubt of,
and reason upon everything Divine and human,
which workings no eye can see or experience,
but that which has been anointed with the eye-salve of God`'s kingdom.

22nd.--Meeting at Ross: the forepart was low,
but through Divine favor a little light sprang up, and I had to express,
that the children who are born from above, of the incorruptible seed of light and life,
in this day may be compared to the cottage in the vineyard,
and to the besieged city-- that there are still to be found one here and another there,
who are measurably engaged to stand for the Lord`'s cause,
and appear as lights in a dark and ignorant world--and that I had to
believe the candle was lighted here and placed on the candle-stick,
to show light to the house and to those among whom their lots were cast,
and exhorted that it should not be hid under a bed of ease, or a bushel,
but to let their lights so shine before men,
that their lives and good works might bring glory to their Father in heaven.

[.offset]
+++[+++From hence he wrote the following letter to his friend Louisa Strangman,
who also received soon after a valuable communication from Sarah R. Grubb.+++]+++

[.embedded-content-document.letter]
--

[.letter-heading]
From John Conran to Louisa Strangman.

[.signed-section-context-open]
Ross, Eleventh Month 25th, 1782.

Hoping a few lines will not prove displeasing to my dear Lucy,
to hear of our safe arrival here, that near and endeared love which I feel towards you,
leads me thus to communicate a little with you.

We came here last night in company with our dear friend Anne Elly, etc.,
in whose company at Kilknock, the evening before,
we were favored together with a measure of the owning of Divine regard,
opening in suitable and tender counsel to the states (I believe) of the youth present,
testifying to them how precious the visitation of Heaven was to some, who,
being favored to find that pearl of great price,
sold all that they had formerly a life in,
and thereby purchased it,--recommending them to buy the Truth also, and sell it not,
and that wisdom, instruction,
and understanding that flows from the living Word of God in their own
hearts,--giving up to the fire that which is for the fire,
and to the sword that which is for the sword, etc.
It was well, I believe, that we were there;
the Father of His family I hope was felt among us, to the help of some present,
who might be ready to faint, after fasting for so long a season,
sitting in our solemn assemblies,
oftentimes as in the valley of Achor and shadow of death.
But as we are concerned to be faithful unto this death,
He will arise in His own time for our assistance,
and when He comes His reward is surely with Him,
and His appearing is at times like the lightning from the east,
unexpectedly coming into His temple, where all things should be ready,
clean and garnished, and we found waiting, as faithful servants,
not knowing the hour in which their Lord comes.

My mind has seemed to me at seasons, for some time past,
to be under a degree of preparation for this journey into
Munster,--a state of circumspection and faithful watchfulness,
to the holy Head of our most holy profession seems to be laid before me,
and to endeavor after faithfulness to His manifestations,
that I may receive a foretaste of that crown of peace and joy in the Holy Ghost,
the fulness of which is to be experienced eternally in the heavens.
I think I feel a state in myself, under this preparation,
of endeared love towards the Friends of this province,
which I believe flows from the Fountain of love, tendering and breaking my spirit,
to my comfort and consolation.

Farewell my much loved friend,
and I humbly hope to be your partner and sharer
in that holy life which never is to have an end,
and to be preserved in that station, through Divine favor,
in all the trials of this life.
My dear love to your mother, etc.

[.signed-section-signature]
John Conran.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Sarah R. Grubb to Louisa Strangman.

[.signed-section-context-open]
Anner Mills, First Month 18th, 1783.

[.salutation]
My Dear Friend,

Your acceptable letter of the 4th instant reached me in due course.
As I felt some of your painful sensations, +++[+++alluding to her prospect of marriage+++]+++
so I could likewise rejoice with you in the
prevalence of that secret but all-powerful voice,
which in seasons of our greatest besetment,
when we prove that all our temporal as well as spiritual
enjoyments depend upon the Sanctifier thereof,
interposes for our help, and commands the waves that they be still.
Every little experience of this sort ought to strengthen our faith,
and add to our patience in times of trial,
knowing that at this word the winds and seas obey;
better is it for us that it is not extended in our time, nor governed by our will,
for that would leave us destitute of means whereby our spiritual
faculties could be exercised and prepared for spiritual services,
for ourselves or in the church militant on earth;
and did we find it permitted in the Divine law that our wills
and inclinations might preside over our religious impressions,
how short would their reign be,
and how little certainty should we find in their fluctuations.
Better, far better is it for us to go under the weight of the cross,
feeling its substantial operations on our minds
by crucifying us to our own carnal wisdom,
and that unto us; that so an immovable kingdom may be established in righteousness in us,
and, from an increasing pure, holy attachment to that Arm which brings deliverance,
we may seek to have our lives supported and conducted by the precious gift of faith,
finding it to be our meat and our drink to do the will of our heavenly Father.
The comfortable aspiration of your mind the night before you wrote me
seems a seal to the belief that your prospect is a right one.

Such are greatly needed as will firmly stand in the life and authority of Truth,
and lift up the standard thereof to the indifferent unwashed professors in this day,
who have the form of godliness, but lack the efficacy and wholesome fruits of the power.
I am convinced, however,
that they who stand and are enough engaged faithfully to keep their ranks,
must suffer persecution and be lightly esteemed of many for
the Truth`'s sake,--not a persecution like that which befell
our predecessors in the rising of the purity of the gospel day,
when their bodies were imprisoned and despised,
and the Spirit of their holy Head triumphed over death, hell, and the grave;
but this day of trial, if I have any sense of it, is a still more evil day and bitter,
because the seed of the kingdom is under oppression,
and few are grieved for its affliction.
Many are dwelling at ease in their ceiled houses,
are consoling themselves with what they find there,
thinking how much safer it is to keep in this habitation than to
venture themselves into the battle of a despised cause in these
perilous times--others who have been appointed and armed for the Lamb`'s
war have flinched when they were called to stand in the front,
for fear of some personal disadvantage,--and
there are those who have lost favor and strength,
by too boldly and precipitately engaging in battle before their armor was prepared,
their earthen pitchers broken,
and by the sound of the trumpet they were commissioned
to cry,--"`the sword of the Lord and of Gideon.`"

From a transient survey of the various openings to error,
and perceiving that there is but one way and one means
to stand in that kingdom which is not of this world,
many discouragements arise,
and sometimes a language that "`one day I shall fall by the hand of the enemy.`"
And yet I may acknowledge,
that in some seasons of trial which I have experienced of late,
exceeding and different to what I ever before knew,
I have been secretly strengthened by the belief,
that as we allow ourselves to be brought to the balance of the sanctuary,
and stand open to every manifestation we may find there,
even when it requires us to be melted down again in order to add to our weight,
that though the enemy may beset and boldly vaunt against us,
pouring as it were his floods out of his mouth,
he will never be able to pluck us out of the Divine hand,
but a hook will be put in his jaws, and deliverance wrought for the pure seed.
As it is only by our being led down in the deeps, purified there, established there,
and there seeing the wonderful mystery of godliness,
that we shall be able to stand the fiery darts of the wicked,
and after having done all to stand with garments unpolluted, hands washed in innocency,
and hearts that have access to the altar of God,--let us not be afraid, beloved friend,
but trust and humbly confide in Him who can
teach our hands to war and our fingers to fight,
and will, as we are faithful to Him, shield us under every assault,
from within or from without.

It is very unexpected to me that I have written thus;
I had no view of it when I took up my pen,
nor has my mind been disposed of late to communicate, but I write what occurs,
without restraint, feeling that love in which there is freedom.
I feel nearly and dearly to love you,
and remain therein with Robert Grubb`'s and sister Sally (John`'s) love,
your poor but affectionate,

[.signed-section-signature]
Sarah Grubb

--

In this visit to the county of Wexford, I believe I was, according to my small measure,
baptized into the states of the people, and made to sit where they sat;
from these feelings I may say, that the life of religion is low in this quarter,
many of the aged and middle-aged having buried their talents in the earth,
and the Divine Seed seems to be pressed as a cart is pressed under sheaves,
to their own great loss.
Yet I apprehended that there was a tender visitation of
Divine love towards the beloved youth,
some of whom were looking to the elders to ask bread, and found few, very few,
to break it unto them; the Great Shepherd of Israel will, I believe,
in His own time arise for the help of these,
and bring them forward into use and service if
they prove faithful in the day of small things.
Though my way herein was in much strippedness,
in which I had to go deeper than heretofore, yet my experience was increased,
and I was made willing to be where the seed was, in a state of suffering in many places.

29th.--At Ballicane we had a very heavy, dull meeting:
it felt to me that many were buried in the earth, they knew not how to dig,
and to beg they were ashamed: they bore the appearance of the Lord`'s people,
but their hearts seemed to be far from Him.
I had to minister here in great poverty and weakness, and was favored with peace.

Eleventh Month 6th.--The National Meeting at Dublin concluded.
The several sittings of this meeting were much clouded,
too many not sufficiently concerned to wrestle for the blessing, waiting in a careless,
lukewarm and unconcerned situation,
like the multitude formerly for the loaves and fishes
to be handed to the servants and so to them,
instead of laboring for themselves to be fed immediately by the Heavenly Hand.
There were many servants present who appeared exercised
for restoring ancient beauty in the church;
in the meeting for business, Robert Valentine was well and zealously engaged on that subject.
I thought the business was conducted in too formal a way,
barely reading and answering the queries,
with little observation on the represented state of the body.
I think I never saw into the state of the Society so clearly as of late,
and that unless our holy Head is pleased to arise and qualify
some suitable well-concerned members in the church,
the blessed cause of Truth will suffer among us;
so many are closely occupied in building up their own houses,
while the Lord`'s house is I fear in many places left desolate.

10th.--Very hard labor at Edenderry meeting,
a deep covering of the earth rendering the precious
seed too much unfruitful among many of the professors.
In an opportunity after dinner,
the state of the elders in the breaking forth of this Gospel day was set forth,
(some of whose descendants were present,) how they were
concerned above all things to do their heavenly Father`'s will,
and that they were made bright, and noble, and valiant for His cause on earth,
by keeping deep in their dwelling, and near the heavenly Spring;
they were men to be wondered at by the people among whom they dwelt,
and from the fulness of their experience had at
times to bless that great Name who lives forever,
and to cry Holy, holy, Lord God of Sabaoth,
the heaven and earth was full of His glory--that the same way was open to us, if we,
as they,
were concerned to have our dwellings where no divination nor enchantment can prevail.

12th.--The select Monthly Meeting was held this morning:
in this opportunity my exercise was so close and trying that I secretly cried, "`Lord,
remember David and all his troubles;`" my mind wandered up and down,
and could not find a resting place, which was a great grief to me.
Robert Valentine, after a considerable time in silence,
described the state of those who were so exercised in spirit
that they could not do any thing for their Master,
and so forsaken that they could not think one
good thought--that this was a profitable season,
purging and purifying the vessel in the laver of regeneration,
so as to fit and prepare it for the Master`'s use, showing us to ourselves,
and what we are without Him.
The queries were answered,
and Robert Valentine was concerned that Friends should be upright in their answers,
and tell the state of things as they really are.
I felt a little matter on my mind,
what the prophet saw--the Lord standing upon a wall made by a plumb-line,
with a plumb-line in His hand--which opened before me
as the wall of discipline which surrounded us,
and would preserve us from the corruptions in the world and ourselves --that this
discipline was founded in the wisdom of Truth--that those who stood on the wall
should build with the plumb-line of truth and righteousness in their hands,
and that the order of Truth and the Gospel led us to
confess ourselves one to another honestly and uprightly,
which might open in concerned minds a word of
counsel and advice for our help and recovery.

13th.--Monthly Meeting at Edenderry,
a hard and laborious time--a dark and heavy cloud seemed to surround us;
Robert Valentine and John Hall appeared with difficulty, there seemed little entrance,
or life raised, in the meeting; I thought to carry away my burden,
but fearing to withhold, stood up in fear and great weakness,
with the remembrance of Israel formerly, when the Divine presence so filled the temple,
that there was scarce room for the priests to minister;
that under this present Gospel dispensation, a like state was experienced,
when the priests and people were so Divinely refreshed in their silent meetings for
worship that there was an unwillingness to enter in and minister,
but they sat each of them refreshed and satisfied, as under their own vine and fig-tree,
where none could make them afraid, and I queried how Friends had felt that day?
For that I could testify for myself that I had been baptized in the cloud,
into death and darkness, and that sin was the partition-wall which separated, etc.
The men`'s meeting was favored: Robert Valentine dropped several weighty suitable remarks;
he is a zealous Friend in discipline.
I have renewed cause for thankfulness,
that I feel the Lord to be my strength in weakness, riches in poverty,
and my all in every time of need.
I have had trying seasons to pass through of late,
more so I think than I ever experienced since my mouth
was first opened in a public testimony for the Truth,
having often to go down into Jordan and to stand there
with somewhat of the weight of the Ark on my shoulder,
and wait for the passing over of the people.
It was a comfort and rejoicing to me, to find myself
dipped into the same states that my companions were,
and to have sometimes like expressions living in my heart; this helped,
through Divine favor,
to strengthen and confirm me in that which I hope and believe is the way of well-doing.

29th.--Week-day meeting at Waterford:
I have experienced a trying state of poverty mostly since I came here,
and in this meeting, which I believe I was the cause of bringing on,
by refusing to appear in a state of weakness the day before in a Friend`'s family;
yet gracious regard was extended to me this evening, in a little opening in this family,
after which I thought I had to see that "`There is one who scatters, yet increases more;
and there is one who withholds more than is right, but it leads to poverty.`"

Twelfth Month 8th.--Meetings at Limerick;
my companions were concerned in testimony in both meetings,
it was my lot to sit in poverty and silence, life did not feel to me to be in dominion.
I fear this world and its pursuits stands as a
partition-wall between many and their soul`'s happiness;
oh! the desolations it brings upon those who set out well, and run well for a season,
but Demas-like, forsake the God that made them,
for the glory and vanity of this present world!
Yet there are some here I trust,
who have in this the day of their youth chosen the Lord for their portion,
and I believe He is at work by His power in their hearts, to draw them near to Himself,
that they may become a people to His praise and glory.
With these my spirit was nearly united,
and in the fresh feelings of that love which flowed in my heart towards them,
I was renewedly engaged to supplicate the Father of mercies secretly on their account,
that He would in His tender mercy and gracious
regard preserve them in His holy life and fear,
that through Him they might bring forth fruits to His praise and glory.

15th.--+++[+++After speaking of several meetings, and opportunities at Cork,
he says+++]+++ in all of these my covering was poverty, strippedness, and silence;
under this dispensation I grew uneasy and restless, which I believe increased it,
till Gracious Condescension was pleased to show me that
a quiet habitation was the safest and best dwelling,
and here I was enabled at this time to seek for and find rest to my wearied spirit.

17th.--As we passed along in this city,
I have felt my mind drawn in dear love to Friends here,
and have been enabled in some families, through Divine favor and ability,
to express some things to my own peace,
and I trust and hope to the edification one of another;
this is renewed cause of thankfulness, when I remember what I had been,
and my present state of weakness, how unworthy I am to be made of any, or the least,
use in my Lord`'s family.
Let His own works praise Him, but unto me belongs shame and confusion of face,
and His mercies, they endure to His unworthy creature to this day.
Amen--so be it!

24th.--Cork week-day meeting.
My stay here was about twelve days, in much weakness and in much fear;
a crumb from the heavenly table was at times mercifully afforded,
which helped to sustain me when I appeared ready to perish.
I think they proved profitable seasons, teaching me to suffer hunger and thirst,
and therewith to be content, and bringing me to know in my own experience, nakedness,
and who it was that should clothe me;
so that I then could render praises and thanksgivings to Him to whom they are due.

We left our dear friend Robert Valentine here,
to recruit under the hospitable roof of our kind friends Samuel Neale and wife,
and set out for Youghal, Clonmel, Mountmellick,
and the Province Meeting at Castle Dermot on the 4th of First Month, 1783.
In the meeting on First-day we sat near two hours in a painful silence,
when I was favored with a little strength to express my sense of the meeting,
which I compared to a spring shut up,
a fountain sealed--that there seemed to be little of
the flowing of that river to be felt among us,
the streams whereof make glad the whole heritage
of God-- that the light of the body is the eye,
if it be single the whole body is full of light; but if it be evil,
the whole body is full of darkness--that it is
for lack of our eye being single enough unto Him,
who is the Light and Life of men,
that we are thus allowed to sit as in the region and shadow of death,
having our eye like the eye of the fool, out after the perishing things of this world,
and wandering in the darkness of it:
and therefore we come to our religious meetings in this dark state, sit in it,
and bring it over our assemblies, and go away, like the door upon its hinges,
moving backwards and forwards, and never coming nearer.
Afterwards dear Mary Ridgway stood up, and expressed a like sense of the meeting:
it was a time of brokenness and contrition to my spirit.
This meeting I thought, was a time of instruction even to the unlearned,
who might see and feel that the ministers of themselves could do nothing; nevertheless,
through Divine regard being extended, we were latterly favored together,
to the comfort and refreshment, I hope of many truly baptized ones present.

7th.--Week-day meeting in Dublin.--I have now concluded this visit,
and though my way has been much in the deeps, often baptized for the dead,
dry and formal professors among us, the lukewarm and indifferent, the earthly-minded,
who bring death and darkness to our assemblies,--and have had to sit as the people sit,
and to go down and visit the precious seed of the kingdom,
which is in bondage in the hearts of the people--though these were very trying,
proving seasons, yet they were made profitable, purifying times, having, I believe,
to wade and go deeper than heretofore to reach
to that life which is hid with Christ in God.
My painful travail in spirit was not in vain,
for the wrestling seed was at times made to prevail, and the living spring to arise,
to the comfort and refreshment of the truly hungry and baptized spirits;
this is an encouragement to persevere and wrestle till
the day dawns and the shadows flee away.
There seems to be too general a declension among those
who should be of the fore-rank of the people,
who, with the riches of this world and the anxious love of it,
have let in a spirit of ease and indifference as
to those things which alone make for true peace.
Yet I believe there are up and down a few substantial living members who love the Truth,
are concerned for the promotion of it in the earth,
and I hope are under a godly concern on their
own accounts to keep their habitations in it,
and their garments unspotted from the world.
May these be increased, and experience a growth from one degree of strength unto another,
that Zion may once more put on her beautiful garments, become as the garden enclosed,
and the desire and beauty of all nations.

There are many beautiful and blooming youth of both sexes in many parts that
seem to be under the lively impressions of the heavenly visitation;
my spirit was at times nearly united to some of these,
and warm desires were begotten in my heart for their preservation.
May these remember their Creator in the days of their youth,
when their offering will be truly of a sweet savor,
and as sweet smelling incense to their God;
for this end has He in His gracious condescension visited them,
that they should be redeemed from the pollutions that are in the world,
and that by giving up faithfully in this the day of their early visitation,
and dwelling under the turnings of His holy hand, they may be fitted, qualified,
and so become vessels of honor in His house, to His praise,
and their own peace and consolation.
But I was jealous over some of them, with a godly jealousy,
lest they were not sufficiently sensible of the blessings bestowed upon them;
they felt the warmth of the Sun of Righteousness shining upon them,
and the precious unity of their living brethren and sisters--they were enjoying,
the comforts of this summer season,
but not enough attending on the work in themselves to which
they were called--were loitering in the market-place,
and permitting the blessed day of God`'s visitation to be passing by unimproved,
and the night stealing upon them in which the work cannot be done.
To such this language is truly applicable,--"`Work while it is called today,
lest darkness come upon you.`"

When the springs of love and dedication to God are dried up,
and the tenderness of spirit lost in the cares of the world,
they lose that dignity and true nobility which this
precious visitation would have crowned them with;
instead of being covered with living zeal as with a cloak,
and being made men and women for God, and testimony-bearers for his Truth,
they become dry and formal professors,
and not receiving their daily food from heaven
which only can keep the soul alive unto God,
they live upon their former experiences when the Lord`'s candle shone upon them,
are little better than burdens to the living, and their lives are without the true honor,
their hearts not being right in the sight of God.
May such as these dear visited ones prize their calling,
and be willing to open to Him who has mercifully knocked at their door,
seeking for entrance,
that He may sup with them and they with Him--then indeed may it be said,
"`Salvation is come to that house.`"

My beloved friend, Louisa Strangman,
and I took each other in marriage on the 9th of Fourth Month, 1783,
in a meeting for worship in Mountmellick,
after an engagement on my mind for her of about eight years`' continuance,
which time had many deep and trying exercises in it,
the prospect at times opening with clearness,
and afterwards closing and shutting the door of hope.
I was favored with her company nearly twenty-three years,
much to my comfort and consolation.
When, under the counsels of Heavenly wisdom, and in the Divine fear,
man and woman are united together and become one in the Lord,
baptized together and drinking of the same cup that their Lord and Master drank of,
being of one heart and one mind, dedicated to the Lord`'s service,
helping one another to obey His holy requirings without
grudging-- these when they are brought together,
it is by a way they know not of,
(neither the outward eye nor judgment of man can comprehend it),
and walking by that faith which is the evidence of what they do not see outwardly,
the end thereof is peace.

[.offset]
+++[+++Previous to his marriage he received the following letter from Thomas Greer:--+++]+++

[.embedded-content-document.letter]
--

[.letter-heading]
From Thomas Greer to John Conran.

[.signed-section-context-open]
Dungannon, Third Month 30th, 1783.

[.salutation]
Dear Friend,

I have repeatedly turned over your request to be at Mountmellick next Fourth-day week,
but do not find that I can make it convenient with regard to matters of duty,
which I see no way of putting by.
Do not, however,
from there conclude it is for lack of affectionate regard either to you or Louisa.
I have long loved her with that love which is pure and unmixed,
and it would I think be a pleasing matter to be
present at the solemnization of your marriage;
I trust you will be favored with the company of the Master,
and then it matters not how few disciples attend,
as the wine will doubtless be good and accompanied with a blessing,
although it may be pronounced in silence.

This roll, which I have at times been eating of for some considerable time past,
begins to grow bitter in the inner parts;
I have pleaded and pleaded again mine unfitness,
and have turned the fleece upon it more frequently than
we are informed Gideon did upon his commission,
yet find no release therefrom; I have therefore in my own mind given up thereunto,
and at times feel a wish to be gone.
I have looked as closely as I am capable of, as to the time and place of taking shipping,
and seem easiest at the thoughts of stealing away through Scotland,
without previous sound of trumpet or other signal of important embassy;
and it looks as if I must turn out all alone, like another scape-goat,
bearing my own burden of infirmities,
as well as those of the people where my lot may be cast: but this I through mercy know,
that He who sends forth into the harvest is faithful,
and will neither beget nor bring to the birth without giving power to bring forth;
and upon this arm of Almighty power I desire that my trust may
forever be for fresh supplies of strength and wisdom.

The dispensation we are under is a glorious one,
but the time and season appears to be very perilous--
this last arises from the present state of the churches;
the great part of the people are children of tradition,
and many of the few that appear to be somewhat,
have either clothed themselves with an outside appearance, or are led away thereby,
insomuch that Rachel`'s voice may everywhere be heard,
by those who have ears to hear and hearts to feel for her.
But what will unprofitable bemoaning avail?
I believe it to be the mind of the great and good Master that
the camp should be searched as with fresh-lighted candles,
that every false covering may be seen,
and every covering short of His Spirit be brought to judgment;
may He in mercy to His church and people yet fit and qualify for this service,
and send forth fishers to fish,
and hunters to hunt the people home in their
minds to that Divine principle of saving grace,
which alone can bring salvation to their houses,
and give them to see in the unerring glass of Truth the
deformity of profession without possession,
and of form without power.
Then would the language of lamentation cease,
and the poor baptized messengers`' sorrows would be turned into gladness of heart.
My pen has run on in some sort unwittingly into some
strokes which I had no view of when I sat down,
but I seem free in thus communing a little with you,
and I may add that of late it is rather rare
that I feel an openness to commune so with any;
notwithstanding my thoughts have been as much (if not more)
engaged about these things as in any part of my life;
but it has been my lot to feel and suffer very much in private,
having been almost cut off (in my own apprehension) from the sympathy of others,
and this I conceive to be for some good purpose, which in the end will be manifested,
and we must learn to wait in patience for the fulness of time in all things.

Our men`'s meeting is to be held next Fourth-day;
if my feelings of duty continue I propose then laying my concern before that meeting,
in order to my obtaining a certificate to be addressed to
friends of such counties in Britain as it may concern.
Although I think I feel heavier than I did any of the former four
times I have been engaged in visiting meetings in that land,
I do not see the extent of my intended visit; but see enough, and clear enough,
to draw me from home,
and feel a wish to take a range of meetings in the
northern counties before the Yearly Meeting comes on,
and then feel my way and follow the pointings of that Wisdom which is
profitable and best able to direct from step to step therein.
At the same time I fully expect my faith will be proved from day to day,
as I pass along in the arduous warfare;
and what but conflicts can the poor messengers expect while in this militant state?
I am certain if we are upon the right foundation it must be the case.
I therefore look for my share of them;
nor should we grow weary of suffering with the Seed,
but with cheerful resignation bear our respective parts of what may remain
for us to fill up of the sufferings of our holy and blessed Helper,
who rejoices in beholding the patient resignation of His tribulated followers,
and whose holy Arm is underneath to support and preserve above the waters.

Farewell: I feel a wish for yours and Louisa`'s present comfort and everlasting welfare,
and that you may be enabled, like Zacharias and Elizabeth,
to walk in all the commandments of the Lord blameless.

[.signed-section-closing]
My dear love to her, and accept the same yourself from your sincere friend,

[.signed-section-signature]
Thomas Greer.

--

After we were married we attended the Half-year`'s Meeting in Dublin;
and in the Seventh Month I engaged in a family visit in Ballyhagen,
and had the company of two valuable elders.
The meeting at Ballyhagen I thought a very low time,
and once or twice I felt as if I should be altogether a
castaway from that Divine grace which had visited me:
yet, through the arising of Divine Life in my heart,
I was mercifully enabled to go forth in a testimony to God`'s goodness,
acquainting them how discouraging the prospect was to me at first,
to visit a people that was peeled and scattered among the people
with whom they dwelt--that I remembered the vision which the holy
apostle formerly had of the sheet which was let down from heaven,
knit at the four corners,
which I compared to their meeting which had been gathered by the wisdom and power of God,
and knit and enclosed by the hedge of his Holy discipline;
but that I saw it was filled with unclean beasts and the creeping
things of the earth--that I was very unwilling to proceed,
and refused to go as long as I dare;
still the marvelous loving-kindness of Divine mercy continued to call, saying, "`Arise,
Peter, slay and eat`"--slay those things with the sword of my Spirit,
or there is no eating for those servants who do not obey the command of their Lord!
We had three sittings with near a hundred who were not in unity,
wherein my service opened beyond my expectation,
having to feel great poverty and weakness,
yet experienced Divine mercy extended to be unto me mouth and wisdom,
tongue and utterance,
to show this class the great loss they have
sustained by going out of the garden enclosed,
and thereby losing the heavenly fellowship of Christ`'s blessed Spirit who called those,
(by His Spirit), that had their spiritual dwellings in this enclosure,
His sister and spouse, etc.
In our proceeding through the families,
the first five of the Quarterly Meeting queries were generally read and answered,
which brought forth some suitable and close remarks,
and I thought was of considerable service.

There appears to be a great deficiency in the attendance of meetings,
and ignorance among too many of the principles they profess,
as well as very great rawness in religion.
They seemed to receive the word of exhortation affectionately and patiently,
and I thought there was a degree of fresh visitation afforded to some,
if they will on their parts abide under it.
As I passed on in this service,
I thought it one of the most useful parts of our religious discipline,
when suitably performed,
waiting in the families upon the opening of that Divine
counsel which is profitable for all things,
and shows to them as it were their natural face in a glass; which,
after they have been favored to see,
too many go away and straightway forget what manner of men they are.
It seemed as if darkness had covered the earth,
and gross darkness the hearts of this high professing people.
I was more enlarged in this visit than I had been before,
and often admired how I was sometimes led to speak,
having close doctrine to drop to the lukewarm, the indifferent, the outside professor,
the negligent, and those who forget that Hand which made them, as it were,
days without number;
and had in gospel love to call to such as were resting in a name to live,
yet were dead as to the life and substance of true religion,
to come home to that true rest which is prepared for the righteous, and them only.

Upon the whole,
I believe the service was owned at times by the Great Master of our assemblies,
who was pleased to help us with a little help under trying painful baptisms,
in which we had to visit the precious holy seed of life,
which was oftentimes to be found in a state of bondage and oppression.
Yet we were favored to feel the Son of peace to be in some of these poor dwellings,
and then we had to salute that house in peace.
I was glad I was there, though I went forth very much in the cross, and in poverty,
having very seldom for three months before opened my mouth in public testimony.
But it is well for that servant whom his Master finds watching when he comes,
He will make him ruler over His household;
and it must be in His authority we rule if we ever are of any real service in His family.
I was favored to return with a sheaf,
and had to look back and believe that I had left
nothing undone which I apprehended I should do:
the praise is to that holy and great Being to whom the work belongs,
and it is His works only which can praise Him!
Amen!

Having felt a concern for some months to pay a religious visit
to Friends`' families in Ballinderry meeting,
and obtaining the approbation of our meeting, and my dear friend, James Christy,
the elder, joining me in it, we set out on the 8th of the Tenth Month, 1783,
and in the course of our visit had two meetings with
between forty and fifty persons not in membership.
We had some very painful baptisms,
some of the most stripping times I had met with of late, among dry formalists;
but we were favored to get through the service in peace.

In this year of my marriage I had thought to get leave to stay
at home and attend all the meetings as they fell in course,
which I think we always did when health permitted,
for my dear wife was as zealously concerned, if not more so than I was;
but I felt an engagement on my mind to visit the
families of Friends in Lurgan and Moyallen meetings,
and afterwards those of Coothill and Oldcastle meetings, which I proceeded in,
accompanied by my friend, James Christy.
I thought this visit was favored with a degree of openness towards some young people,
but it appeared there was not much help to be expected from their elders,
who were too much engaged in their worldly concerns.
At Oldcastle there was more order and regularity preserved; meetings are kept up,
and the testimonies supported; nevertheless,
there appears to be too much of sitting down at ease,
and not enough of making use of the time and talent to the praise of Him who gave it.
I was mercifully favored to reach my own habitation
with the evidence of peace in my bosom,
and found my dear wife well, who soon after gave birth to a son.

I had no more engagements from home during the remainder of this year,
but attended on my outward concerns,
(with meetings as they came in course,) for as Solomon said,
"`there is a time for every purpose under heaven;`" our great
and good Master knows what things we stand in need of,
and leaves us at liberty at times, with his blessing, to procure them;
as the apostle declared his own hands had ministered to his necessities.

In looking over some memorandums of my labors in the ministry,
I must acknowledge I have been only an unprofitable servant,
and have nothing to trust to for the hope of a blessed
immortality but the mercies of God in Christ Jesus,
who was the Author, and I humbly trust and hope will be the Finisher of my faith.

[.embedded-content-document.letter]
--

[.letter-heading]
From Christiana Hustler to John Conran.

[.signed-section-context-open]
Ayton, Ninth Month 18th, 1784.

[.salutation]
Dear Friend,

I have often wished to salute you and your dear Louisa by a few lines,
since you have been united by those outward ties which, I think you both know,
I had beheld in prospect,
as believing them to be in the pointing of Best Wisdom for you both,
and therefore felt myself nearly interested in the completion of.
I have felt thus drawn not only as bound in gratitude
to acknowledge the many evidences received,
both when present with you and since my return from your land,
of your kind attention and remembrance,
but also as expressive of my continued sisterly regard and affection,
which I feel to remain a debt due to you.
I have often with great nearness beheld you comfortably settled,
and I believe in your right allotment,
and where I have no doubt of your mutually strengthening each other`'s hands,
as you stand in that allotment Divine Wisdom has placed you in,
and under the sense of that unmerited mercy and parental care so graciously continued,
still adopting with feeling energy, that becoming and needful language,
"`What shall I render to you for all your mercies, Oh! you Preserver of men?`"

Well, my dear friends,
may you and I ever be enabled to press forward (leaving
the things that are behind) towards the mark,
for the prize set before us, however arduous and tribulated the path;
that neither heights nor depths, principalities nor powers, things present,
nor yet to come,
may ever be able to separate us from that love which we have been
mercifully enabled in days past to prefer to all things visible;
and may we be enough engaged so to run as that we may obtain,
is the principal desire of my mind, I think I may truly say, at this time.

I have often, dear friend, been afraid you should construe my silence,
so long continued, into an unkind return for your part of a correspondence which,
however undeserving I may appear to be of, has been greatly valued by me,
and which nothing but the deep poverty that has
been the almost unvaried clothing of my spirit,
and has hitherto discouraged from prosecuting many attempts already made,
would have hindered your receiving ample testimonials of long before this.
And though at present I can by no means boast of better things,
yet as I am often afresh convinced of the loss I sustain by giving way to these feelings,
I wish to break through by telling you how acceptable a letter from you would be,
to tell me how you are, and how your dear child comes on;
I think if I could convey myself for one hour to your house, to your little room,
to see you together, and to converse and have sweet fellowship, as in days past,
it would feel comfortable.

As to myself, and my own movements, I have little to say,
having seldom to my own feelings been able to keep my head above water:
I am at present with our valuable friend Rebecca Jones,
who came over with Thomas Ross and Mehetabel Jenkins (now in
your land,) and several other Friends,
a little before the last Yearly Meeting, where believing it right for myself to be,
and she willing to accept of my company down into the north,
we came to the Quarterly (or what are called the Yearly) Meetings at Colchester,
Woodbridge, and Norwich, taking the meetings in the way,
and after them most of those in Norfolk, Lincolnshire, and Yorkshire.--And now,
with an earnest request that you will again let me hear from you,
I must for the present bid you dearly farewell,
and with the affectionate salutation of my best love to your whole Self,
remain your assured, though poor friend,

[.signed-section-signature]
Christiana Hustler

[.postscript]
P+++.+++ S. My late companion Phebe Marshall, is married to a Friend of Leeds meeting,
whose name is James Blakes, I hope suitably.

Twelfth Month 6th.--Since writing the above, we attended our autumn Quarterly Meeting,
proceeding pretty directly from there into the counties of Durham, Northumberland,
and through Scotland as far as Old Meldrum,
returning last Seventh-day to this place (Whitehaven,) and hope to
reach our Quarterly Meeting at Leeds the latter end of this month.
Our friend John Hall, at whose house we lodged two nights,
desired to be affectionately remembered to you,
and that I will inform you he received an acceptable letter from you at Birmingham,
which he intends to answer shortly.
He with my companion are both bravely, as was Rebecca Wright,
whom we passed on her way to Scotland, accompanied by Martha Routh.
Patience Brayton is I expect now in or near Cornwall,
Samuel Emlen and George Dillwyn and his wife in London, and by letters received,
our worthy friend Robert Valentine is safely arrived in his own land
before their Yearly Meeting in the Ninth Month which will be,
and has been cause of joy, no doubt to his friends as well as himself.

[.signed-section-closing]
Once more farewell.

[.signed-section-signature]
Christiana Hustler

--

[.offset]
+++[+++It appears that Rebecca Jones visited Ireland in the ensuing year,
no mention is made of her services in that nation by John Conran,
but among his memoranda a remarkable farewell testimony
is noted which she bore in a meeting at Dublin,
in these words: "`The Master said to me,
'`You came poor among this people--you have sat among them in much poverty--
be content to leave them in much poverty--I have taken the crown from off
their heads--let them wear dust and ashes my appointed time,
then shall my light break forth as brightness,
and I will be to them a crown of glory and a diadem of beauty.`"+++]+++

[.offset]
+++[+++It is believed the following is the letter referred to by Christiana Hustler+++]+++

[.embedded-content-document.letter]
--

[.letter-heading]
To John Conran.

[.salutation]
Dear Friend,

You have often been brought near to my mind,
in that love which distance does not wear out,
and I have often felt desires for your preservation, for we serve a good Master,
and I can in humble thankfulness say,
"`that His mercies to us have been more than the hairs of our heads.`"
I have tasted many bitter cups since I saw you,
but have often had to rejoice in humble thankfulness,
that I have been brought to that state of resignation,
wherein I could adopt the language, "`I thank you, oh!
Father! May this cup pass from me,
yet nevertheless not my will but your be done, oh! God!`"
I believe it is good and also profitable for us experimentally
to know and feel His will to be our sanctification;
for we poor creatures have a deal of dross in us,
and it is only by feeling and submitting to the furnace, made hotter and hotter,
that the dross is separated from the pure gold,
which loses nothing of its weight and value by being thus refined,
but has this excellency in it,
that it is more fit to receive the Heavenly image or inscription,
that of "`Holiness unto the Lord.`"
I desire, while I am writing, that I may never forget the wormwood and the gall.

[.signed-section-closing]
In much affection and regard, I am your loving friend,

[.signed-section-signature]
John Hall.

--
