== Chapter IV.

[.chapter-synopsis]
* 1786. Religious Services in Ulster Province
* And in Carlow Meeting
* Death of his Daughter
* Visits the Meetings in Munster Province
* Illness and Death of his Wife Return into Munster.

The 1st of First Month, 1780,
I set out under concern to pay a religious visit again
to the families of Friends in Ballyhagan meeting:
the weather was very severe with frost and snow most of the time,
but as I apprehended I saw no other time open to proceed in it, I went forward,
and had as before besides the sittings in the families,
several meetings with about 180 persons not in membership.
I found the life of religion to be low,--the form, which many rest in,
too much neglected by others,--the plain language not kept to,--and a
very general deficiency of attending week-day meetings,
and First-day meetings by some; the sittings in the families were exercising,
and the spring of the ministry low,
yet at times we were favored with the arising of Life
when least expected--the lost sheep were sought after,
and a renewed call and visitation extended to them,
inviting them to the Father's house where there is bread enough and to spare;
but if they still continued to resist and rebel
against the gracious invitations of Divine Mercy,
that others would be called in, and fill their places at the Lord's table.

In the Eighth Month I paid a religious visit to
the families of Friends in Charlemont meeting,
under feelings of dear and heart-tendering love for them,
and having been helped to perform the same,
returned home with longing desires for their growth and
establishment in the love of God through Christ Jesus.

In 1788,
I felt the drawings of Gospel love in my mind to visit
the families of Friends of Carlow Monthly Meeting,
and was accompanied therein by my friend Richard Shackleton.

In the meeting for discipline of the National Meeting in the Fifth Month this year,
I felt a secret requiring in my mind to consent to my
dear wife going to the ensuing Yearly Meeting in London,
to which I readily yielded, and it was very much to her satisfaction.
She was there afterwards several times, when I accompanied her,
always I may say to my edification and comfort; being at times, on these occasions,
made sensible that the Lord was still with Zion,
and that the shout of a King was heard in her,
which helped to confirm me in the faith in which
I had believed-- blessed be His holy name!

[.asterism]
'''

[.offset]
+++[+++No memoranda occur during the next seventeen years,
in which interval he lost his beloved and only daughter;
soon after this afflicting event he received the following
letter of condolence from his friend Gervase Johnson,
who was then traveling in the work of the ministry in America.]

[.embedded-content-document.letter]
--

[.letter-heading]
From Gervase Johnson to John Conran.

[.signed-section-context-open]
New York, Fifth Month 22nd, 1799.

[.salutation]
Dear Friend,

I received a letter last evening from a beloved friend, of the land that you resides in,
giving an account that your dear and only daughter is deceased,
and as I have thought it to be a great outward trial to you and your beloved wife,
I desire to sympathize with you, my dear friends, in your trouble;
but knowing that the Lord gives and takes away at His own good pleasure,
I hope that you both are reconciled, and contented with His Divine will,
and in your experience in being thus resigned,
to give her up to the disposal of her heavenly Father,
you will feel your bitter trials to be sweetened,
which I doubt not is your comfortable experience.
Oh! my dear friends, knowing that all things will be parted from us, or we from them,
is great teaching to us, that our sure happiness is in the great Giver of all good gifts,
by loving, fearing, and serving Him;
under these considerations I feel the encouraging
language to arise in my heart on your accounts,
that although many are the trials of the righteous,
the Lord in His own time delivers out of them all, and if they faint not,
they will receive an inheritance where all sorrow and tears will be done away.
In my writing to you, my dear friend, in your tried situation,
it is brought to my remembrance,
your sympathizing brotherly regard for me in my deep trials,
when about setting out on this trying journey,
your feeling sympathy on that important occasion, I hope I shall never forget.

Farewell, my beloved friend, my love is to you, and your dear wife, and son,
and to all inquiring friends, and I am your friend,

[.signed-section-signature]
Gervase Johnson.

[.postscript]
P+++.+++ S.--This Yearly Meeting comes on the 28th of this month,
after it is over I have thought of going towards New England.

--

[.offset]
+++[+++The reader is referred to the Memorials of Rebecca Jones, p. 279,
for an interesting allusion to Gervase Johnson.]

[.embedded-content-document.letter]
--

[.letter-heading]
From Sarah Grubb to John Conran.

[.signed-section-context-open]
Aimer Mills, Second Month, 26th, 1801.

[.salutation]
My Dear Cousin,

I am inclined to salute you and my beloved Louisa,
hoping that I am not wholly kept out of your remembrance in love,
for I can aver that I love you,
and often visit you in your affliction with the best desires my feeble mind can aspirate.
I feel renewedly for you on the approaching Quarterly Meeting--oh!
what a time for the most approved! how hard to steer faultless! and
yet under the banners of the Captain of the soul's salvation,
conquest is gained over evil in all its intricacies.
Nothing has yet happened that can make us dubious; the Lamb and His followers,
will have the victory; the point is to be His followers,
and then all the fiery darts of the wicked one shall fail.
A sore trial has come on the church,
and it behooves all who wish the restoration of good order, to take strait steps,
for there is not a disposition to feel compunction at
cutting off the skirt of the robe of the anointed;
the language may well be uttered, "`Rejoice not against me,
O mine enemy,`" and I trust some tried depreciated ones may say,
"`When I sit in darkness, the Lord shall be a light unto me,`" etc.
Quietness seems one of the best weapons of defense,
not a withholding through fear of man, but a watching unto prayer,
that nothing may be attempted without the ability that cannot be foiled;
great must be the suffering of the honest-hearted, but if it tend to deepen,
if it awaken to righteousness, we may hope it will work for good,
to those who hold fast the form of sound words, and are not shaken in mind,
and that the dear people who stray from the fold, may be brought to see their error.

I am comforted for your sakes, that the dear Scotch women Friends are with you,
we think Elizabeth Wigham a well-instructed scribe, and her precious B,
walking in the same safe path.
By letter from Moate, we find you are also to have dear M. S. and S. W.;
the best wishes I am capable of attend you all--that nothing may be
able to take you from under the sanctifying power of Truth,
nor dismay you from espousing its cause, when favored with the qualification.
Probably you may have heard that at our Quarterly Meeting,
a hope was raised that the Society of Friends was not yet forsaken,
that continued mercy was extended for its members to walk acceptably,
it was a memorable time.
Dear Mary Dudley has been mostly confined since; Richard Jordan is now in our province,
and we are daily expecting Samuel Smith.
I apprehend Mary Ridgeway is shortly to be in London, in the course of her service.
Sarah Lynes has had the concurrence of her Monthly Meeting to
hold public meetings in Friends' meeting houses about London.
Mortality awfully visits many of our dear friends and acquaintance:
we miss the sweet spirit of my sister Grubb, she died as she lived,
an example of meekness, suffered conflict by the apprehension of omitted duty,
but cast herself on the mercy of Providence.

[.signed-section-signature]
Sarah Grubb

--

Ninth Month 6th, 1805.--I left home under a concern which had attended my mind,
to visit Friends in Munster province, and some parts of Leinster,
and arrived in Waterford on the 14th. Next day I
attended the fore and afternoon meetings there,
under great discouragement and bodily weakness,
having with much difficulty reached the city;
but was enabled through Divine favor to answer
the service required of me in both meetings,
to my own peace and solid satisfaction.
+++[+++After performing the service required of him in those provinces, he says,]
In this visit I had to pass through many baptizing exercises,
the state of the church being very low in sundry places; the cares of this world,
and the eager pursuit after the lawful things of it, have, I fear,
blinded the eyes of many,
so that they make excuses that they cannot accept the invitations
which have been so frequently held out by the servants,
saying, "`Behold all things are ready!`"
In some of these mortifying labors, wherein the creaturely part was humbled, I had peace.
When I got to Mountmellick on the 12th of Tenth Month,
I expected to have gone by Rathangan to Dublin, and home:
but there I felt a fresh exercise on my mind drawing me
to attend the Quarterly Meeting at Waterford,
and after two days weighing it I gave up to the requiring,
believing it was from the Lord; and in that meeting,
especially in the meetings of discipline and select meeting,
I felt my mind much engaged in the service of them, which afforded me peace,
and I left that city with a comfortable hope that I had been in my place there.

In passing through the county of Wexford my covering was deep poverty,
except at Enniscorthy where I felt some openness, principally to strangers,
to whom my spirit was drawn in much love, which I believe proceeded from Him who is love,
to salute them and invite them to come and partake of the dainties of His table.
As I travelled on, my mind sometimes looked towards home,
but I could not feel any thing but a deep baptizing exercise of trouble,
which at those times sunk my spirits greatly;
I endeavored to support myself under these conflicts with the impression,
that I had not lightly undertaken this journey,
having had it on my mind about fourteen months or more,
and I went on it in the faith and full belief it
was necessary I should not hold back any longer.

I sat three meetings in Dublin silent,
and since to this date have only spoken in testimony once.
My spirit feels forsaken, ashes are on my head spiritually,
feeling myself made inwardly sensible,
that I am altogether unworthy and unfit to speak in the name of the Lord,
almost saying with Moses, "`Send by whom you will send,`" for I neither desire,
nor can I go;
and in this disposition I rejoice that I am set at liberty from dealing any
more with a people whose ears are dull of hearing--eyes they have,
but they see not the beauty there is in the Truth--hearts they have,
but they understand not the things which concern their everlasting peace!
May the Lord in His gracious condescending mercy, once more say to His people, Arise,
and shake yourselves from the dust of the earth, and put on your beautiful garments, Oh!
Jerusalem; that Zion may once more become the praise of the whole earth,
that she may again travail and bring forth children, to the praise of the great Name!

Twelfth Month 19th,
1805.--I travelled home the 5th of the Eleventh Month from the above journey,
and found my dear wife in a very low way and poor state of health,
and her disorder increasing rapidly.
She continued to sink until the 4th of Twelfth Month, when she quietly departed,
and I trust, has obtained a mansion in her heavenly Father's house,
which I believe she faithfully labored for from the age of about fifteen years.
At that early age, I have heard, she showed marks of Divine visitation,
and giving up to the heavenly vision,
she was enabled thereby to order her conduct in such a circumspect manner,
as to be a good example to the youth who were contemporary with her;
her presence among them kept down all levity without using any austere remonstrances,
or giving such advice as seemed to claim superiority over them.
She thus in the morning of life preached the cross to the beloved youth,
by daily taking of it up, and praised her Lord and Master,
as being worthy of being obeyed, by obeying Him.
Her company was sought by her elders,
who saw in her that wisdom was not confined to grey hairs,
nor an unspotted life to old age; for she manifested,
that by an early and faithful dedication to the
operation of the Divine grace in her heart,
both might be shown forth, in a conduct evidently coupled with the fear and love of God,
to the comfort and consolation of many Friends who were her intimates.

The first time I saw her, which was at a funeral at Dublin,
her appearance to me was that of a disciple of Christ.
I was then under the discipline of the cross,
having been united to the Lord's church and family about two years.
After we were married she proved to me a faithful and
exercised companion in many tribulations,
the worst of which was from false brethren;
and being a woman of an excellent and discerning spirit,
was made useful to me in advice and counsel,
having the qualification and being in the station of an elder in the church;
which gift she exercised in this Quarterly Meeting oftentimes in great weakness and fear,
being not only modest in exercising her talent, but also diffident,
preferring others to herself.
Poverty was very often the covering of her spirit, but it had a blessing with it,
for she was of much use, and had great place hereaway,
so that her removal is deeply regretted by the
few who are well concerned in this quarter.
I may say she was faithful in her attendance of meetings,
both at home and the Yearly and Half-Year's Meetings in Dublin,
where her value was acknowledged by her sisters sometimes choosing her as clerk.
She was four times at the Yearly Meeting in London;
the first time she acted as assistant-clerk,
which made her acquainted with many valuable Friends in that nation,
whose friendship and sympathy she obtained.

The last Monthly Meeting she attended was in company with three Friends from England,
who were traveling in Truth's service, when I was from home, one of whom, I was told,
in the Women's Meeting,
bore testimony that there was one present whose day's work was
over--that He who had been her morning light would become her
evening song--that there was a mansion prepared for her,
and that her rest would be glorious.
When her sickness in the beginning did not appear very alarming, she,
on waking from sleep once told me she expected to die of that sickness,
and that she had had a secret intimation of it in that sleep.
From that time she turned her thoughts heavenward,
and was very frequent in supplication that the Lord would look upon her in mercy.

She at one time expressed her unqualified belief in the Divine Nature of Jesus Christ,
through whom she expected remission of sins.
She said the principles of Friends were the principles of Truth,
that she always believed in them,
and was willing to lay down her life for the testimony of Jesus.
After she had been silent for many hours, and I scarcely expected she would speak again,
I heard her saying in a low voice, "`Who is this great enemy that surrounds me?
(meaning death, I believe,) Christ will overcome him.`"
She called up her maid-servants and gave them excellent
advice to the tendering of their hearts,
desiring them to make truth and honesty their guide;
she prayed fervently for me and her son, who was present,
advised him to be affectionate and dutiful to me,
and that when I looked on him I should remember her.
She desired to be remembered to sundry Friends, and said that she loved every one.
Thus was this beloved partner taken from me,
after living in sweet fellowship upwards of twenty-two years.
Many times I was bowed in humble thankfulness to the great and good Giver of
this first of earthly blessings I had received at His merciful hands.
I sensibly feel the loss I have of her sweet society,
but this is in degree compensated for by the lively hope I have,
that it is her everlasting gain.

As I stood at the grave my spirit felt clothed with such serenity and stillness,
that my sorrow ceased and resignation took up the place of it;
and though there was not any public testimony borne,
yet the sweet peace that was felt was more encouraging than words.
Her remains were interred in Friends' burying-ground, at Lisburn,
the 6th of Twelfth Month, 1805, aged fifty years and eight months.

[.embedded-content-document.letter]
--

[.letter-heading]
From Sarah Grubb to John Conran, On Occasion of the Death of his Wife.

[.signed-section-context-open]
Anner Mills, Twelfth Month 11th, 1805.

[.salutation]
My Dear Cousin,

I am obliged and consoled by your letter of the 7th of this month.
It is a great favor to feel an anchor to the soul under such circumstances as yours,
and it seems a beatitude of the Divine Being to sustain
when he sees fit to deprive us of our dearest ties.
I have found him near to me at such junctures, and have traced it in many instances,
but like other beams of sunshine, it withdraws after a season,
and then we feel our stripped state, which would be insupportable,
but for the recollection that the everlasting Arm had been underneath.
You will, my dear cousin, have frequent necessity to take this retrospect,
and to supplicate for a continuance of sustaining help;
for the endearingness of her whom you have been
deprived of will often break in upon your solitary mind;
you will miss her as Lady Rachel Russell said of her husband, "`sleeping, waking,
walking, at meals,`" and in many other ways: so that all will seem insipid without her.
I had no doubt she would die the death of the righteous,
and that her latter end would be like theirs.
I believe she was a nursing mother to many.
I wish your desire for us, who must follow, may be brought into effect;
I have many and well grounded fears for myself,
it often seems as if nothing but a miraculous interference
could rescue me from the accuser of the brethren.
I trust you feel peaceful in the winding up of your service in this province; it
must have consoled your dear wife that you yielded obedience to that requiring;
I thought you seemed preserved in a humble state of mind,
may it be the covering of your spirit to the end of time!

[.signed-section-closing]
I am your sincere friend,

[.signed-section-signature]
S+++.+++ Grubb.

--

Tenth Month 8th, 1807.--I left home for the Quarterly Meeting at Waterford.

11th.--First-day morning meeting was a very low season to me;
the state of the Jewish church, in the time of Nicodemus, was opened before me, who,
though a master in Israel, and a ruler among the Jews,
appeared to know nothing of the spiritual doctrine of regeneration,
though perhaps well instructed in the questions and traditions of his church;
this may be the state of too many amongst us, who have heard by the ear,
and their fathers have declared to them the truths of the Gospel,
yet if they do not experience the new birth in themselves,
and hear and obey the voice of Christ,
they are standing on the same foundation this ruler was,
and cannot clearly comprehend the meaning and
intent of this doctrine no more than he could.

The Quarterly Meeting was held the 17th, 18th, and 19th,
they were seasons of trial to me, being under a burden which I was unable to lay down.

20th.--Meeting for worship at parting: I felt a desire to stay over the week-day meeting,
and afterwards to go to Clonmel to be at their meetings on First-day.

25th.--At Clonmel, the evening meeting was to me a cloudy and low time,
but a little opening appearing,
I was enabled to show that the form did not entitle us to be children of the promise,
though we may call Abraham our father; I had also to call to the worldly-minded, etc.,
and was favored with liberty in this meeting to my comfort.
This day I felt a pointing in my mind to stay
over the Monthly Meeting here next Fifth-day;
these intimations can only be compared to holding forth a finger to a distant object,
yet I am afraid but to acknowledge them, and when fulfilled they afford peace.

29th.--Monthly Meeting, a low time to me; I sat in silence in the first meeting,
and had one observation to make, on a case before the meeting,
whether Friends should receive a written acknowledgment
from a person who had taken an oath,
which he condemned as inconsistent with our discipline,
and against the spirit of the Gospel--a Friend thought it was not full enough:
I remarked, that when the prodigal remembered his father's house,
his father went forth to meet him and brought him in; I felt tenderness to cover my mind,
and was fearful the band which united him to the
Society would snap if strained much tighter.

On reaching home on the 9th of Eleventh Month,
I felt peace and satisfaction from this journey.
When I was in Waterford,
I felt at times as if I should be obliged to enter on a family visit there,
which very much humbled me in viewing the weight
of the service and feeling my own weakness,
but through Divine favor it passed away and I was easy.

[.embedded-content-document.letter]
--

[.letter-heading]
From George Stacey to John Conran.

[.signed-section-context-open]
London, Twelfth Month, 18th, 1807.

[.salutation]
Dear Friend,

The tender sympathy you have expressed in the situation of our dear child demands
that I should not be long in acknowledging the receipt of your letter,
and this I can do the more gratefully as we are
favored with some appearance of convalescence.
For this prospect, and many other comforts and enjoyments,
we are strongly called upon to manifest gratitude;
and I sometimes wish there was greater prevalence of
this quality felt and displayed--a quality,
which, when we consider our relative and dependent situation,
and the goodness of the all-bounteous Source, ought to fill the mind;
but reflections like these are too often supplanted by the proprietorship we
assume in those very enjoyments which the great Giver furnishes us with,
and complacency in the gifts benumbs our perception of what is due to Him that gave them.

We feel much with you in your bereft and solitary situation,
considering also that its poignancy is not likely to be abated by the aids,
which some of us more favorably circumstanced derive,
from the interaction of feeling minds; yet He whom you love is omnipresent,
and doubtless will apportion of His consolations as He gives to partake of trials,
in such time and manner as shall ultimately tend to the soul's revivement and happiness:
in holding this belief how much has the traveller
Zionward the advantage even in this life,
over him, whose hope perishes with time!

We had heard, through the pen of James Abell to one of our neighbors,
of your having paid an acceptable visit to some of the southern meetings,
and we are glad to find from yourself that the result is peaceful.
From your silence respecting the state of things in your province,
I fear much of a consolatory kind cannot be said.
Have any of those that withdrew found their way back,
or is any disposition manifested to come more into the unity?
If they could retrace their steps, and submit to be broken to pieces,
they would perhaps be bound up again so as to be brighter than ever;
but this work of humiliation is hard to flesh and blood!
We had rather find an apology for our mis-steps in the supposed conduct of others,
than come under that baptism which brings the
sword upon all secret corruptions and disloyalty.

My wife joins in endeared love with your affectionate friend,

[.signed-section-signature]
George Stacey.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From John Conran to D. C.

[.salutation]
Dear Friend,

You have been frequently the subject of my
secret and serious meditations some years past,
at a time also when a larger share of intimacy
subsisted between us than has done of late:
I beheld you as a servant who had been honored and dignified with a precious gift,
or designed for usefulness and service in the church,
I mean as a nursing mother in our Israel.
His blessed eye, that is looking over all His works,
saw in that day the state of His church in this quarter,
to use the metaphor recorded in Scripture on a similar occasion,
"`there was neither sword nor spear among forty thousand in Israel!`"
The Lord's ways are not as our ways,
He employs secondary causes to bring about His gracious purposes,
and which bear the resemblance of the usual means in human affairs.
How often has He made use of His holy ordinance of marriage,
to translate a living instrument from one quarter of the vineyard to another,
even from one nation to another;
and often this translation has been a means of raising them up,
and qualifying them for usefulness and service in their new destination,
in the wise ordering of Him who sleeps not by day, nor slumbers by night.
And although the multitude, who are thus mercifully cared for,
perceive not this His fatherly regard; yet He is thus, season after season,
watching over His flock, and delegating the shepherds, giving them a charge,
as He did to Peter formerly, to feed his sheep and his lambs, if he loved Him;
happy indeed is that servant whom his Master,
when He Comes to take an account of His servants, shall find so doing!

Now, my dear friend, I believe your marriage was of this nature;
natural affection was the outward means to bring you here,
but I believe the Lord's hand was underneath, to make use of you,
and those talents He has entrusted you with,
for the service of His family in this quarter.
If we may judge of great things by small,
we may see with His truly dedicated and devoted servants,
that almost every thought of their hearts is to
be found doing their heavenly Father's will,
so I am persuaded the holy Head and High Priest of the church is going to and fro,
up and down, looking after the needs and necessities of His family,
and affording them assistance one way or other.
I have been jealous over you, I trust with a degree of godly jealousy,
querying how you have made use of your Lord's money.
The unfaithful steward, when under a sense of great poverty--to dig he would not,
and to beg he was ashamed--wisely went among his Lord's debtors,
asking how much they owed to their Lord; may you, my dear friend,
in much sincerity put the impartial query to yourself, how much do you owe?
Talents are not given to any of us to lay up or bury,
but to make use of to the praise of the Great Giver;
your candle has been lighted and placed on a candlestick,
what for?--that it might enlighten the house, and show forth His praise.
If it has done so it is well--it is not for me to judge;
my concern at present is to awaken an inquiry,
and put you in mind that the hour is coming on you and me,
and perhaps is nearer than we may expect, when we must go forth and meet the Bridegroom;
and happy will it be for those who shall be found ready to enter in with Him,
and receive the blessed sentence of, "`Well done, you have been faithful over the little,
you shall be made joyful in the house of your God!`"

Farewell, with near and brotherly affection I salute you,

[.signed-section-signature]
John Conran.

--
