== Chapter V.

[.chapter-synopsis]
* Attends Sundry Meetings, from 1808 to 1812
* Visits the Families in Waterford, Clonmel, and Cork
* Various Exercises and Services around Home.

Fourth Month 23rd, 1808.--I attended the Yearly Meeting in Dublin:
some of the Meetings I think were overshadowed with solemnity,
which very much kept down the wisdom of man;
a large committee of men and women were appointed,
to consider the state of the Society as represented by the answers to the queries,
they had sundry sittings, which were in general to satisfaction,
and the state of things was pretty fully opened.

Fourth Month, 1809.--I attended the Yearly Meeting at Dublin as usual:
the national committee produced some parts of
the minutes of the National Meeting of Ireland,
which they had been engaged in, to assimilate some of them to the English minutes,
and to revise, and if needful, to abridge;
that part which was finished was read and approved,
and desired to be used in the place of all others.

I attended this year all the Quarterly Meetings in this province,
and all our own Monthly Meetings,
and visited the families of Friends of Moyallen meeting,
in company with Thomas Shillitoe, and William Neale of Mountrath meeting.

Fourth Month, 1810.--At the Yearly Meeting in Dublin,
the remaining minutes were read and approved,
and the whole ordered to be printed and distributed to the several Monthly Meetings.
A committee of men and women Friends were appointed to
consider the state of the several Quarterly Meetings,
which was taken up in a solid manner; the many outrunnings in marriage,
especially among the females,
brought a lively concern over the committee to
endeavor to find a remedy against this evil,
and as it is most prevalent in the province of Ulster,
where the largest share of Friends are in low circumstances,
it was proposed and agreed to raise a fund through the nation,
to be placed at the disposal of a suitable committee of that province,
to encourage good conduct in the youth of both sexes,
by assisting such with a sum of money as their funds will afford,
on their entering into the engagements of life, either in marriage or suitable business,
as the committee may think proper; this was agreed to,
and an order sent to the different Quarterly Meetings to put forward such a subscription.
I think we had cause to believe that some of our sittings were Divinely owned;
also this committee, in their care and concern for the body,
and the preservation of the discipline.

Sixth Month.--I attended the Quarterly Meeting held at Richhill,
and was very unwell with a cold which deprived me of my voice,
so that I concluded that I could not speak intelligibly;
but in the afternoon meeting I felt the word of life strong in me to advocate
several of our testimonies which the worldly spirit calls singularities,
but was enabled to prove that they are consistent both with Scripture and reason.
The testimony of Truth was set over these objectors, and the meeting concluded,
I believe, to the satisfaction of Friends,
and to my own admiration that I was so supported over my indisposition and hoarseness.

Seventh Month 12th.--I laid before the Monthly
Meeting a concern which had attended my mind,
to pay a visit to the families of Friends of Waterford Meeting,
which had arisen when I was in that city near three years before,
and had exercised my mind at sundry times since.
Friends took it under consideration,
and left me at liberty to pursue that and such other
service as Truth might open for and require.

Eighth Month 27th.--Monthly Meeting at Waterford:
I presented my certificate and laid my concern before Friends,
who appointed a Friend to accompany me.
In this meeting I had to remind them of that declaration,
that we have all sinned and fallen short, but how far, or the extent,
we ought each to seek to know for ourselves.
Our great adversary endeavors to palliate,
and is very expert in using arguments to set us at ease in our sins,
but if we bring them to the discovering light of Christ in our minds,
we shall see them as they are in the sight of God,
where no palliations or excuses will cover them from His righteous judgments,
which will be revealed against every thing that is not of His own begetting; therefore,
I exhorted Friends to bring their deeds to this
light that they may pass under the flaming sword,
for nothing that is unclean, or done in the will of the creature,
will be permitted to enter that kingdom which is purity, peace, and joy,
in the Holy Spirit.

Ninth Month 27th.--I came to Clonmel,
and entered on the visit there to Friends`' families,
and in concluding it was favored with peace after many deep baptisms.

Tenth Month 20th.--The Quarterly Meeting at Waterford was
attended by Henry Hull from New York Government in America,
Martha Brewster from Bury, in England, and sundry other Friends.
In the concluding sitting of the Select Meeting I laid before
Friends a concern that had attended my mind for some time past,
to visit the families of Cork Meeting, which, after deliberate consideration,
was united with, and I set out on the 27th for Clonmel, in company with Henry Hull.

28th.--Henry Hull was largely and instructively engaged
in the morning and afternoon meetings at Clonmel.

30th.--A large public meeting, at which was supposed to be about 700 persons;
our testimonies were explained in a satisfactory manner by Henry Hull,
on whom the whole of the public service fell.

Eleventh Month 8th.--Monthly Meeting at Cork,
I laid before Friends my prospect of visiting the families of that meeting,
with which the meeting concurred,
and Henry Hull offered to accompany me to some of the families.

+++[+++John Conran was enabled to perform this service,
and after attending Limerick and Mountmellick meetings,
also the Quarterly Meeting held at Carlow,
from the 29th of the Twelfth Month to the 1st of First Month 1811, inclusive,
returned home, on which occasion he remarks]: I do not find that I have much to say,
only that I endeavored to be faithful to that which had the appearance of duty,
often laboring in little and low places,
at which times duty and faith were closely tried; and after having done the little,
the only reward was not to feel condemnation, and therewith to be content.
On leaving Cork I felt my mind ofttimes broken into tenderness,
and in much love to Friends of that meeting,
which continued with me pretty much to Limerick,
and was the same love that drew me to engage in that service.

Fourth Month 25th, 1811.--I left home to attend the Yearly Meeting in Dublin.
In this meeting we had the company of Henry Hull from North America.
I had a suffering time, mostly in silence, especially in the meetings for discipline,
which to me were heavy.
I returned home after the Meeting.

In the Eleventh Month, I accompanied Ann Burgess from Leicester round the Lough.
We held public meetings in the following places to good satisfaction: Newtown,
Donaghadee, Belfast, Antrim, Grange, Ballinacree, Colerain, and Moyallen.

Twelfth Month 1st.--The Quarterly Meeting in Lurgan,
which was large and attended by Sarah Grubb and Ann Burgess,
both of whom I thought were much favored,
being well qualified to open the principles to those who are without.
The meeting for discipline was conducted in harmony,
and the select meeting again re-instated,
which had been laid aside for about twelve years.

[.embedded-content-document.letter]
--

[.letter-heading]
John Conran to Ann Burgess.

[.signed-section-context-open]
Twelfth Month 14th, 1811.

[.salutation]
Dear Friend,

I received your kind and sympathizing letter, which was truly acceptable to me.
Your proposed plan of my removing into Lisburn,
and getting shelter in some Friend`'s family, I have often considered heretofore;
but in viewing in my mind the several situations there among Friends,
I could not see any one in that Light which is profitable to direct, therefore,
for the present have abandoned that design.
If I took a lodging there, dieting by myself would be uncomfortable; and a house,
which I once inclined to, might prove too burdensome.
So that, my dear and much respected friend,
I do not see a better way at present than to wait the Lord`'s time,
apprehending the trials and provings I now pass through are by His permission,
for further purification and refinement.

When I went abroad with you it was in the cross,
having a great dislike to that desolated part of our province.
Since we separated I have remembered with secret satisfaction our movements,
and that inward union and fellowship which flows from
our holy Head to the living members of his body;
this the world knows not of, their friendships are of this world;
"`but,`" says our holy High Priest, "`you are not of this world,
I have called you out of this world,`" its pursuits and vanities!
Blessed call indeed, oh! that all who heard it were obedient to it;
their peace would flow as a river,
and their hearts and hands would be lifted up`' with
thanksgivings and praises on the banks of deliverance.

You are serving a good Master, and I believe with faithful dedication,
be faithful unto death as well as unto life, that you may inherit the crown of life.
The apostle says he was in deaths oft,
a state of deep humiliation necessary for the Lord`'s favored servants to experience;
this is the preparation of the heart which is not of man, it is of the Lord,
because here we can cast down every crown and high imagination of ourselves;
and the baptism sometimes is so deep that we scarcely dare look up to Heaven only to say,
"`Have mercy on me, I am a sinner.`"
Although we are buried with Him, yet when thus tried, remember, my dear friend,
for your consolation, the precious life which at times we do much rejoice in is safe,
being hid with Him in God,
the sure hiding place and refuge of the just and righteous of all ages.
Though I write these things to you, they are I believe your own already;
yet in these baptisms our faith is tried to a hair`'s breadth,
but out of the mouths of two or three witnesses the word is established.

[.signed-section-signature]
John Conran

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Conran to James Abell, (under deep trials).

[.signed-section-context-open]
Dublin, Fifth Month 1st, 1812.

[.salutation]
Dear Friend,

I received your very acceptable letter by our mutual friend, John Leckey,
which came in a time when my mind was dipped into sympathy with the Seed,
which I feared would be felt in a suffering state in
various sittings of the approaching solemnity.
On the approach of these solemn seasons my lot is a suffering one,
and though painful to the natural part in us,
we ought not to repine in being companions with our dear Lord and Master,
and accounted worthy to suffer with Him;
that when our measure is filled up in His militant church,
we may be favored to have a mansion of His preparing in His triumphant church,
in His holy presence, and in the company of His saints and angels,
where the wicked cease from troubling, and all sorrows are wiped away.
This state, which is attainable, and is set before us that we may endeavor to attain it,
is worth patiently submitting to the light afflictions of this present season for.
Though we are at seasons crowned with the heavenly gift, yet,
if the wicked are permitted to make it a crown of thorns,
and we have to feel the sharpness of them as well as the shame,
the disciple is not above or better than his Master;
He also was crowned in both capacities, but the submissive language of His spirit was,
(let us remember it,) "`Not my will but your will, O Father, be done.`"

His holy will concerning the members of His church is sanctification,
and if His unerring wisdom choses the furnace for that end,
He can bring us forth as He did the three children formerly, in safety,
their garments undestroyed, and their bodies without the smell of fire upon them,
for the angel of His Divine presence was with them,
and is still with His afflicted little ones,
who are preferring Him to their chiefest joy in this world.
I remember the saying of a dear friend, Thomas Scattergood, under a holy influence,
to me when under deep suffering, "`Satan has desired to have you to sift you as wheat,
but I have prayed for you that your faith fail
not;`" and his holy prayer proved availing,
even to this very day, enabling to speak well of the Lord`'s name,
because His mercy endures, and will endure from one generation to another.

I nearly sympathize with you, my dear friend, in your present suffering state,
but not as Job`'s friends, in a similar trying dispensation, with presumption;
no my dear friend,
but under a full persuasion that your trials are in unutterable wisdom,
to purify and to bring you to a more full acknowledgment of
the depths of His counsel--that you had known Him like Job,
in an unspotted life and conduct, and brought praise to His Truth.
Yet here is not to be our rest, but to obtain a further knowledge of Him,
in which every other consideration may be abased,
and we bow ourselves before Him in dust and ashes, that He alone may be confessed,
and His name (power) be exalted in us and over all blessed forever!
I salute you, my dear friend,
in the fresh feeling of that love which I believe flows at
this time from the Fountain that will never be drawn dry,
though flowing from generation to generation,
at which the Lord`'s flock have at all times been made to drink,
and of which the flocks of the stranger cannot partake.
And may He who dwelt in the bush and it was not consumed, dwell in you, and you in Him,
so that the arrows of the archers may be blunted and turned aside,
and the Lord may have the acknowledgment of praise,
is the sincere desire of your affectionate brother,

[.signed-section-signature]
John Conran.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Henry Hull to John Conran.

[.salutation]
Esteemed Friend,

May the protecting Arm of Divine Power shield you through the yet remaining conflicts,
that you may know a safe landing in the haven of an eternal rest!
Your love has been great to the Beloved of souls,
manifested by your attachment to His cause on the earth,
which you have espoused and adhered unto in a day of shaking, when many were blown away,
and have mingled with the chaff that floats in the air!
What a favor in the part of the county you lives in!
Oh! that you may know the Ancient of days to be
with you now when old age is making its ravages,
that you may be the encourager of the younger branches of the family
whom the Head of the church may bring forth into usefulness.
My spirit was united to some of those,
for whose establishment in the Truth I have desired, that the walls of our Zion,
which have been marred, may be completely restored and built up,
that there may be rendered unto the Lord of Hosts the glory that is due.
Then will He restore unto Israel judges as at the first,
and counsellors as in the beginning!
In the fellowship of the Gospel I conclude remaining your friend,

[.signed-section-signature]
Henry Hull

--

Fifth Month, 1812.--I attended the Yearly Meeting in Dublin, which was large,
and at times favored with a living spring of Gospel ministry,
to the edifying and comfort of the living part of the family.
The meetings of business were also favored with the calming influence of Divine Power,
so as to cause the waves to be still, which were at times distressing,
occasioned by three appeals from the province of Munster,
which has been cause of exercise to some there for several years past,
and occasioned a breach of love among them.
The state of that province coming weightily before the meeting at this time,
a visit to it was appointed, and my name was set down for that service with five others,
to meet at Limerick Quarterly Meeting in the Seventh Month,
and to proceed further as Truth may open the way.

In the Seventh Month, I left home to attend the Quarterly Meeting at Limerick,
the several sittings of which proved to me seasons of deep suffering,
and I found no relief in them till the last sitting, which was closed,
when I requested a pause might be made, after which I laid down my burden,
and expressed the exercise I had passed through, which was deep suffering;
the occasion of it I dare not conjecture, fearing to be found in the seat of judgment,
but referred the judgment to each, to examine themselves,
how far they had contributed to this distress which was
now felt to cover the minds of the living amongst us.
The meeting closed in a painful manner to me, feeling little or no relief.

Next day in the meeting for worship, I had an open time to the youth,
of whom there was a large number present, and the meeting ended comfortably.
I then went to Mountmellick, and remained there nearly two weeks,
attending the meetings in course, which felt to me to be low and exercising seasons,
very little ability afforded to minister till the day I left it,
when I was concerned in the week-day meeting, to express my sense of sundry states--some,
in whom the precious seed of God`'s kingdom was covered with the clods of the earth,
which prevented its growth--in others,
the briars and thorns choked it--while some were soaring aloft,
above the simplicity of Truth,
and entering into airy speculations concerning those things
which can only be known by the revelation of the Father;
it was by this revelation that Abraham saw Christ`'s day, and was glad,
and the prophets saw it and foretold it;
some were called to come down from the above state of self exaltation,
by Him who is willing to enter in, and abide with them, if they will but obey His call.
I left this place not altogether relieved from the burden I had to bear,
being sensible how hard it is for the voice of the servant to be effectually heard
by those who have not submitted themselves to the voice which has spoken,
and is speaking from heaven.

24th of Eighth Month, I set out for Dublin, and after attending three meetings there,
and our Quarterly Meeting near Charlemont, returned home.
Since that time I have had very low poor times in and out of meetings,
and sometimes under the necessity of ministering
in some of them in little and low places;
but I believe these dispensations are in that wisdom which is profitable to direct,
that we may experience the few barley loaves to be sufficient.

Twelfth Month.--The Quarterly Meeting at Lurgan, was, I thought, at times favored,
and in some of the sittings my mind was comforted in
feeling that Divine goodness was near to us,
and acknowledged our assembly with a holy solemnity,
in which ability was afforded (I hope) to minister to several states present:
the meeting concluded to satisfaction and the comfort of the living.

1813.--I have been greatly tried for these twelve months, with a stripped state,
and with various temptations,
the subtle adversary being permitted to assault me in various shapes,
and repeatedly to roar against me,
and terrify me with inward and fearful impressions on my mind.
But these trials turned to a good account for me,
by drawing me to seek for help from Him on whom help is laid,
and through gracious condescension, in the needful time,
His Divine presence was manifested in my soul,
His holy light dispelled the darkness and administered strength;
so that in the frequent successions of these trials, strength was added to strength,
holy confidence succeeded weakness, and I was hereby made measurably strong in the Lord,
and by the power of His might enabled to rest in hope,
that He who had been with me in many tribulations would
never forsake me in my latter days;
yet my faith was often closely tried.
I attended the Yearly Meeting in Dublin this year, and had but little to offer in it,
especially in the meetings for discipline, which to me were cloudy;
I fear that the knowledge of the letter too much prevailed,
which I believe casts a shadow over the brightness which otherwise would be seen,
and in which alone the discipline can be suitably and comfortably conducted.

I have at times felt my mind drawn to attend the meeting at Lisburn,
to which I formerly belonged --in it my spirit has been
baptized into a painful and trying state of poverty,
and in the cross I have had to minister in this
dry and barren state without feeling relieved.
Oh! the love of the world, how overwhelming it is,
and chokes the precious seed that the good Husbandman has sown in His field!
Some now, as formerly, cannot bear sound doctrine, but would rather say to the servants,
prophesy to us smooth things, prophesy deceits:
but such physicians are of no value who would cry, Peace, peace,
when there is no peace but what the world gives.

Twelfth Month 1st.--Many are and have been the trials
and tribulations I have had to pass through,
both in my public and private capacity.
My afflictions are great, and I seem often left comfortless,
and at seasons ready to conclude that I would no more speak in the name of the Lord,
and have ofttimes gone to meeting with that resolution;
but when the word of life has sprung up in my heart, I could not refrain,
and words would almost burst from my lips; and though no condemnation would follow,
yet constant poverty of spirit would be my covering,
and mortifying recollections of my past life would impress my mind,
and sink me into great abasedness of soul,
therein acknowledging my unworthiness and unfitness to
take the great and holy name of my God in my lips;
but to this state I submit, and bear it patiently,
as I am made sensible it is truly my desert.

The Quarterly Meeting is now near,
and it brings a considerable share of weight over my mind,
as I do not know of any other minister likely to be present,
and deep poverty is my attendant;
but to the great Head of the church I commit His family thereaway,
and hope He will have compassion on them,
and send them home satisfied that it was good that they were there.

The Quarterly Meeting is now ended, and it was well attended for the time of the year;
the meetings for worship were I think favored,
and I got through the service which presented to my peace and satisfaction.
The first sitting of the meeting for discipline felt to me in danger of being disturbed,
I thought Satan was present with us, and once or oftener showed his head;
but the Lord was pleased to own us, and he was kept down,
and a close exercise and watch prevailing, the business was concluded to satisfaction.
The answer to the query '`how meetings are kept up`' brought an exercise over Friends,
that a Committee was appointed (of which I was one) to attend all the Monthly Meetings,
and assist them in making appointments to visit the deficient,
and to stir them up to more diligence.

Third Month 7th, 1814.--The Quarterly Meeting at Lisburn:
the meetings for discipline were low.
Friends too generally are not sufficiently watchful over their own spirits,
to keep them in obedience to Christ,
in whom are all our fresh springs for service in the church.
I have been for a long time kept very low in my mind,
and in that state found myself drawn to minister, which has been in the cross,
but I dared not neglect or refuse the opening.
We are to offer the small cattle, as well as the large,
when they are demanded of us--the former have been accepted at my hands.

I have been drawn to visit sundry week-day meetings in the province,
and the fewness of the attendants brought discouragement over the prospect;
but giving up to the small appearances in my mind,
the service was often owned beyond my expectation, and I returned in peace.
I generally am most easy not to make any unnecessary delay after a meeting is over,
but return and eat my morsel in secret,
and receive from my Master what He is pleased to grant,
which is ofttimes an impressive sense of my own unworthiness,
and under that impression I can render the praise to whom it is due.

Fourth Month.--I am now passing through baptisms
preparatory to the Yearly Meeting in Dublin,
which are deeply afflicting and hard to be borne.
Excuses of age (nearly 75 years),
and infirmities are not felt to be sufficient for my absenting myself from it,
neither a daily prevailing sense of unworthiness and unfitness
to appear with the more enlightened children of the Lord;
nothing affords peace but submission to the requirings of a Master who knows me,
and what I can be made to endure.
My exercise is so great that death seems to be preferable,
and the day of my birth lamented that a man child was
born into the world--woe is me! for many reasons!
But the Lord knows my afflictions,
and in His unutterable wisdom permits me to be thus tried,
and by those who should not do it, which makes it harder to be borne.

Fifth Month.--I attended the Yearly Meeting in Dublin,
which cost me a close exercise for some weeks,
feeling considerable bodily as well as spiritual weakness;
but I was enabled to give up and to trust for the
renewal of strength both ways to Divine Mercy.
I had some service in the meeting for discipline,
and in a large evening meeting on First-day, to my satisfaction.

As I travelled home, my mind was much inwardly drawn, and in silence,
a stream of Gospel ministry at times ran through me in secret,
as if I were preaching to a large auditory,
and the doctrine so apposite that it melted my
heart into humble contrition and admiration,
and I felt my strength renewed under the remembrance of this saying,
"`He that believes on me, out of his belly shall flow rivers of living water.`"
I came home in peace, and glad that I had been there.

Ninth Month 6th.--Our Quarterly Meeting near Charlemont,
the meetings on First-day were held in silence, and numerously attended,
the meeting for discipline was favored, and the next day I had an open testimony,
to the members of our own Society as well as others,
recommending them to the Divine Light in themselves as the
door of the true sheep-fold of which Christ is the Shepherd;
that unless they came in by that door, professing with us or any others was in vain.

11th.--First-day, at Megabry, a time of deep wading in silence,
which was at length broken with these expressions, "`You believe in God,
believe also in me,`"--"`the devils believe and tremble.`"
If we do not believe in Christ our faith stands upon the same grounds with theirs,
and we lose the benefit of His second coming without sin unto salvation;
and if we despise Him in his little and low appearance in our hearts,
the Jews did so in his bodily appearance and were rejected of Him;
and small as His appearance may be to the carnally wise and prudent of this generation,
it was He whom the angels of God were commanded to worship.

Eleventh Month 2nd.--I have been now for some time reduced to a low state of mind,
but pretty much resigned under it; my exercise in meetings is trying,
feeling very little of that living virtue that
encourages to act in the services of the church;
yet in this very low situation,
I feel a necessity at times to offer the little that appears,
which is attended with peace, but is again succeeded immediately by deep poverty,
which is an exercising trial of faith and patience.
I dare not desire a change of raiment,
for in these tattered garments my nakedness is plainly seen,
to the deep humbling of my poor mind: let all that is of the natural man be brought low,
so that God be glorified through my abasement!

18th.--The Preparative Meeting at Megabry, in which my faith was closely tried,
feeling a subject on my mind for a long time,
but attended with so little ability to deliver
it that I struggled much and long to pass it by;
but near the conclusion I felt strength to stand up,
and was enabled to get through to my peace; my usual dryness succeeded,
and sunk my spirit into mourning,
but I was mercifully supported by the arising of these words in my mind,
"`Seek not to yourself great things,
and your life shall be given you for a prey whithersoever you go,`" which comforted me,
as I have hitherto felt life to follow those weak appearances.

20th.--First-day, at Megabry; a state of infidelity was the burden of my spirit,
arising out of those writings which are so plentifully scattered abroad in these days,
leading the unwary astray,
to follow after lying vanities and the deceivings of their own foolish hearts,
thinking to comprehend the things of God by their own wisdom.
I have felt this day much depressed in mind,
from not giving up to attend the Monthly Meeting at Moyallen, yesterday;
the pointing thereto was so small, and my poverty so prevalent,
that I passed it by, but I hope to be more attentive in the future.
The ways of God are at times unsearchable, and past our finding out.
The Quarterly Meeting will be in about two weeks,
which I expect will bring me into some preparatory baptisms,
as is usually my lot before these large gatherings; may the Lord strengthen my weakness,
which is very great and has been for some time past, if it be His holy will!

Twelfth Month 6th.--Our Quarterly Meeting at Lurgan:
in the concluding meeting I was enlarged in an open and
clear testimony in defense of the Scriptures,
and the Divinity of our blessed Lord,
against a spirit of antichrist which seemed to possess some present;
and I concluded the meeting in supplicating the Lord that He would be
pleased afresh to anoint the eyes of those who said they saw,
but were blind, and to open their eyes that they might see the New Jerusalem,
and the beauty of true holiness,
so as to be able to worship God aright through the Spirit of his beloved Son,
who is God over all, blessed forever and for evermore.
The meeting concluded under a solemn covering, and I returned home in peace.

My movements in the ministry for some years back have been after long waiting,
the appearance of life very small, and my faith closely tried,
but a necessity has attended which I have been afraid to neglect;
they have often been unexpectedly enlarged in Gospel love, and afforded peace;
but very shortly the whole recollection of the
precious unction has been clearly taken from me,
and I have been reduced to my usual state of poverty--the gate +++[+++like Mordecai]
has been my safe-guard,
for there nothing can dress or perfume with the odors and ointments that had
been poured forth when the Bridegroom had entered into His chamber.
Blessed are the dead who thus die, yes, says the Spirit,
they shall rest from their labors, and their works shall follow them!
Blessed poverty indeed, for in it the creaturely part has no share!

First Month 12th, 1815.--The Monthly Meeting near Ballinderry;
the fore part of the meeting was a low time,
my mind was much tried with a wandering spirit which I endeavored to subject,
and after some time experienced quiet;
when that passage opened on my mind recommending
the offering our bodies a living sacrifice,
and I was gradually enlarged,
and led to compare the state I had been baptized into during
the early part of the meeting to the waves of the sea,
succeeding one another--that this was the work of the enemy to render our sacrifice
unacceptable to God--but let us permit the waves to pass over our heads,
and not to carry us away into the world,
and thereby deprive us of the opportunity of renewing our strength in Christ,
who through His instruments appointed those seasons to
His church and family for that gracious end and purpose.
It was a time of refreshment and renewal of strength,
for I went to meeting under deep exercise, not expecting or desiring to be so engaged,
and under the feeling of life I was drawn forth in supplication at the close.
The covering of the first meeting was carried into the meeting for discipline,
which was conducted and concluded in a truly solemn manner;
the praise is due to that all-wise and holy Being in whom
"`is life, and the life is the light of men,`" and who has not
forgotten to be gracious to a backsliding people!

In sitting in meetings for discipline,
I look for as clear an evidence to speak as in meetings for worship,
therefore my words are few,
but I hope they are in degree seasoned with salt--
"`let your speech be alway with grace seasoned with salt,`" which is the
life--in this path the wayfaring man cannot err,
and peace is found in his dwelling;
it is a means of keeping down those forward spirits which are ready to run when not sent,
whose state is that of flatness and death instead of peace and consolation,
and to whom the language applies, "`Who has required this at your hands?`"

22nd.--First-day meeting at Megahry: Cast down, but I hope not forsaken.
I have had deep trials of late that caused me to cry by night and by day,
Lord help your servant who cannot help himself!
But my cry returned back into my own bosom,
as if the ears of the Lord God of Sabaoth were not open to my cry.
My sore ran in the night season, and I was not comforted.
How long, Lord, will you not hear my prayer and my supplication!
I feel dried up as a potsherd, but I still hold fast my confidence.
Make haste, Lord, to help me, before I go hence and be seen of man no more,
for there is neither wisdom nor knowledge in the grave!

Second Month 9th.--I attended the Preparative Meeting of Lisburn,
and was concerned therein to exhort parents and
heads of families to train up their children,
both by precept and example, in the nurture and admonition of the Lord,
which would be as a twofold cord that might be a means of drawing
them to the living principle of light and grace in their tender minds,
and make therewith a threefold cord that could not be easily broken.
Also recommending the children to obey their parents in the Lord, for this is right;
concluding with the state of Eli and his family, who did not restrain his sons,
though he had counseled them against the evil of their ways.

Sixth Month 6th.--Our Quarterly Meeting at Moyallen,
I had a pretty open time in both meetings on the First-day;
the meeting for discipline was to me a remarkably clouded time,
I was baptized in the cloud into death.
As I lay in bed that night or early next morning,
the spring of Gospel ministry opened and flowed in my heart abundantly,
in such a variety of doctrine as filled me with surprise,
which gradually arose from a small beginning to a stream that I could swim in.
I lay silent in spirit, and attended to the flowing of it to my admiration;
towards morning it closed,
and I arose in my usual poverty and went to meeting in a low and stripped state,
but had not sat long before some little matter gradually arose before me,
and as I attended on the opening it increased to the time I
should stand up with a metaphor of Christ`'s school,
in which He is the teacher:
fresh matter gradually opening in my view I was enlarged in a
clear testimony which afforded peace and comfort to my mind,
the praise of which is only to be given to Him to whom alone it is due,
the great and holy Head of His church, who is blessed forever and ever!
