== Chapter VI.

[.chapter-synopsis]
* 1815+++.+++ Continuation of the Journal of His Religious Experience and Services.

Ninth Month 10th.--I have not felt inclined of late to record any of
the occurrences which attended me in my spiritual progress which were
various--some painful trials and probations,
and many temptations,
over which I was favored to get with thanksgiving and praise where only it was due.
I attended, as usual, all the meetings at home, and sometimes the neighboring ones,
some by appointment and others on my own concern,
which were in general to my satisfaction.
These services were at times attended with baptisms that brought to my recollection
the state the apostle had to pass through when he said he was cast down,
but not forsaken; in which times the promise of the Savior was fulfilled,
"`I will not leave you comfortless:`" His poor depending children,
who have none in heaven but Him, nor in all the earth in comparison of Him,
give Him the praise of His own blessed work,
for they experience Him to be the Resurrection and the Life;
it is by and through Him alone they live, and because He lives they live.

Our Quarterly Meeting was held last week in Grange, in Charlemont,
which was large and favored;
I went in much discouragement as there was no other ministering Friend,
and there were some disagreeable things to come before the meeting by an appeal,
which at one time wore the appearance of a breach of love and unity;
but I thought the Author of every good word and
work did appear with healing in His wings.
I felt a pointing to stay their weekday meeting next day, where were many young people,
to whom I had to minister the word of consolation,
and encouragement to purchase the Truth, let the price be what it may,
for Divine wisdom and a right understanding seasoned
with grace would be the companions of it;
the opportunity was through Mercy remarkably favored.
I left them in peace, and returned home to sit at the gate, a safe dwelling place!

Tenth Month 25th.--I felt a draught to attend the Monthly Meeting near Charlemont,
and was silent therein; in the second meeting,
upon the clerk`'s querying if any Friend had anything to offer,
I felt it right to say that I came there from an apprehension of duty,
but in both meetings there was, I thought, such a thick cloud over me,
I could not travel forward--that whatever was the cause I could not tell,
but if each of us were so disposed to inquire in sincerity,
"`Is it I?`" I believe the individuals might find out who it was;
but that if we abode under this covering, our stay in the wilderness would be prolonged,
so that instead of advancing, we might be returning back again to our former conditions,
and never reach the promised land.
The clerk stood up, and said the Friend`'s concern was right, he believed,
as there was occasion for the remark.
My mind was relieved, and I returned in peace.

Eleventh Month 18th.--I had a closely-sifting season last night,
which brought me very low, more so than I have felt for a long time;
the sentence of death was my portion, and under it I was prostrated before the footstool,
of mercy, scarcely daring to look up;
when the Judge of quick and dead sits in judgment on us, who can stand when He appears!
What must be the terrors of those whose sins accompany them to the tribunal of Christ,
when their lot is cast for eternity, with a certain, fearful looking for of judgment,
and fiery indignation and wrath!
In this furnace, I saw much still for the fire, and more for the fuller`'s soap,
the prospect of which brought me very low, ready to give up all,
under a deep sense of unworthiness; in which the Lord was exalted, whose right it is,
and the creature abased: here I felt the truth of that saying of the apostle,
"`Unto us belongs shame and confusion of face.`"

Twelfth Month 14th--My travel seems through the wilderness,
and Pharaoh and his host pursuing me.
There is still a great deal in me to be slain; when will you be sheathed,
oh sword of the Lord, the Word of His mouth!
Every word of my mouth appears to be weighed in the balance of the sanctuary,
there is nothing escapes His eye.
The inmost thoughts of my heart are judged as soon as conceived;
there is not any thing hidden from Him.
In vain did Adam hide from that call which can shake
the heavens and the earth also--"`Where are you?`"

For some time past my hopes have been all centered in Divine mercy and forgiveness,
my former works of righteousness have been blotted out, and in my heart I have said,
"`Though you slay me I will trust in you!`"
In my troubles I have endeavored to remember the day of my espousals,
when His light and His truth shone into my dark habitation.
I was then brought into His banqueting house and His banner over me was love.
But now I feel my enemy spreading snares to entrap me,
but I trust the fear of falling will preserve me through the mighty God of Jacob.
"`Your ways, oh Lord,
are past our finding out`"--but the advice of Moses
formerly to Israel is good for me at this time,
"`Stand still and see the salvation of God.`"
I have but little to add at this time but to acknowledge the Divine mercy in
supporting me with some patience under distressing trials in my family,
but no way has opened for my escaping from them.
I feel bound to this quarter of the vineyard where poor labors appear to be acceptable.

I felt a concern to attend the Monthly Meeting at Moyallen,
and being desirous of turning the fleece upon it, produced an exercise for two days,
which was very trying; and when it had reduced me to resignation, the concern left me,
and I remained at home in peace.
When I feel drawings abroad, they are generally pleasant to the taste,
but in turning the fleece they are bitter inwardly and very hard to give up to.
There is in man,
though he has passed measurably through the fire
and drunk of the bitter water of affliction,
a share of the first nature still unsubdued, that would say,
"`Send by whom you will send!`" or that complaint of, "`Who has believed our report?`"
Yet gracious condescending Mercy bears with us as a tender parent,
and rewards us (instead of chastising) with His evidence of peace!

1816 Third Month 24th-- I went to Moyallen First day meeting,
and had a heavy dull sitting for above an hour and a half,
when a very small opening appeared before me, a few words,
which I reasoned with to put it by, when a language moved in my mind,
that if we were so poor as not to be able to offer an ox, ram, or goat,
then a pair of turtle doves or two young pigeons would be accepted.
So I stood up with two or three sentences,
and moving gently on as a few more arose before me, the waters rose gradually,
so that I left the meeting under a solemn covering, and myself in peace:
let the praise be to Him to whom it is due, who is strength in weakness,
and riches in poverty.
The great necessity for watchfulness in ministers in exercising their
gifts in meetings for worship has been shown to me lately.

As I sat in meetings, a field of offerings opened before me,
in which was much sound doctrine, on various subjects,
which appeared to me suitable to many states and conditions who might be present;
but as I rarely stand up till a considerable lapse of time, I viewed the subjects,
whether they might be offered, when this language clearly came before my mind,
that this ram had not horns,--the whole was resumed back into the treasury,
and another ram was fastened in the thicket, and was offered,
which I believe was accepted with wine and oil,
and I had to conclude the meeting with solemn supplication to the Lord, who is Wonderful,
Counsellor, and the Prince of Peace!
Praise his holy name, O my soul, for He only is worthy of it.

This winter I had many bitter cups to drink, both outwardly and inwardly:
we have need of patience--Lord, increase it, and my faith, that they fail not!
I do not remember the furnace hotter, but I believe the cup is from the Lord`'s holy hand,
therefore I must drink it: the bitterest cup is sometimes the most wholesome,
therefore you, His poor despised little ones, drink all of it.
The reply of Eli to the child Samuel, when he told him every whit, is instructive;
when Eli heard the sad sentence pronounced against his house, he submitted, saying,
"`It is the Lord, let Him do what seems Him good.`"
A sorrowful and warning lesson to parents to exercise that authority
over their families which faithful Abraham did in his,
having this testimony of Divine approbation, that he commanded his family after him,
therefore the Divine will was manifested unto him;
and if we are sincerely engaged to do our part, help will be administered to us.

Seventh Month 10th.--The week-day meeting at Megabry was, I thought,
comfortably held in silence; many doctrines opened in my mind in a living experience,
which I thought I could have stood up with to edification,
but the necessity or woe was not with them,
therefore they passed away under this impression,
that they might open again in some other meeting.

11th.--I attended the week-day meeting at Lisburn, much in the cross,
as a hard time generally is my lot there; I sat in great poverty for upwards of an hour,
when a very small opening appeared, with which I stood up, and gradually proceeding,
it increased till it became as a broad river, when the sense impressed the day before,
of these openings being renewed in some other meeting, was fulfilled, I believe,
to the satisfaction of many present,
as well as to my own--praises be given to the Great Giver of every good and perfect gift!
Watchfulness is as necessary to ministers as faithfulness,
lest they enter into temptation.

14th.--+++[+++After speaking of a favored meeting at Megabry,
he says:]--It feels to me as if there were a fresh visitation afforded to this meeting,
which was some years back highly favored, as I have been told,
and appears by the records of the Society; but when the elders of that day were removed,
there arose a generation who had not been witnesses of the
saving help which had been afforded to their fathers,
and of some of them, it may be said,
they knew the Lord only by hearing of His name and power,
but their hearts were far from Him.
Yet He whose mercy endures from one generation to another,
is pleased to visit the children`'s children,
to the third and fourth generation of those who have loved Him and kept His commandments.
May this blessed covenant of life and light be once
more renewed in this quarter of the Lord`'s vineyard,
to the raising up of such whose lips may be
touched with the live coal from off the altar,
under the holy influence whereof sons and daughters may in true dedication say,
"`Here am I, send me!`"
Though I do not expect to see the morning of
this day arise with healing virtue in its wings,
yet I rejoice in the hope that it will come and will not tarry.
Blessed and praised be the name (the power) of Israel`'s God, who can bind,
and who can loose when in His unbounded wisdom, He sees fit so to do.
Oh! may the blessing of the everlasting hills be upon the head of Joseph,
upon the head of him who was separated from his brethren;
may there be that fruitfulness in the Gospel of Jesus Christ,
experienced in which the branches run over the wall,
and there is a going to and fro in the earth proclaiming the
glad tidings of the Gospel of peace and salvation,
through obedience to the Divine illumination in their own minds.

Eighth Month 4th.--I have of late felt, as ofttimes before,
when passing quietly about my lawful business,
a spring of Gospel ministry open in my mind,
and many Gospel doctrines flow therefrom for a
considerable time in a clear and convincing manner;
I have kept still, in humble admiration, desiring to treasure them up,
in order to bring them out on some future occasion; but the whole has been resumed,
and I have had to go forth without scrip or purse or two coats.
Today, after a favored meeting,
this state appeared to my mind as what is called in Scripture,
"`the renewings of the Holy Ghost.`"
These experiences brightened my candle which had
been burning but dimly for some time past,
and raised in my heart praises and thanksgivings
to Him whose mercies are from everlasting,
through His dear and beloved son, our gracious and merciful Redeemer;
who in His heavenly wisdom sees fit to hide Himself for a season,
to increase our diligence in seeking for Him,
and to Him for those fresh supplies which he graciously
grants to His poor depending little ones,
who in His absence mourn,
but in His life-giving presence rejoice with fear and trembling.
Amen, so be it.

25th.--First-day meeting.
Before I left home my bitterness was so great that I went out shedding tears,
almost careless what became of me,
but I experimentally found that was not the case with my merciful Lord and Master.
After I sat some time in meeting,
the blessed state of the poor in spirit opened before me,
with the benefits arising from it: from the feebleness of the impulse attending,
I felt a fear of moving under it for near an hour, so that it left me, naked and bare,
upon dry ground;
but at my petition (on my uneasiness at having
neglected a line of duty) unspeakable condescension,
was pleased again to bring the opening into view with a little more certainty,
upon which I moved forward,
and Truth arose and its enemies were scattered-- the light of the
Gospel shone brighter through me than I had ever known before,
and various states and conditions were described--that the kingdom of
heaven was only attainable through the aid of the grace of God,
and submitting ourselves to the redeeming efficacy of
the cross of Christ--the state of the poor in spirit,
made so not in the will, wisdom or strivings of men,
but through the wisdom of God showing unto man his weakness and natural deformity,
and the need he has of a Savior lest he should die in alienation from
God --and that it was this state of inward and deep poverty
(to which I appeared to be well qualified to speak from my late baptisms into it)
that effectually knocked at the door and gained an entrance,
for the gates of heaven are opened to it, if faithfulness is continued in to the end.
Let our oblations be ever so rich, and sacrifices ever so near and dear to us,
even as a first-born,
and though the temple we frequent be more magnificent than Solomon`'s,
yet obedience to the revealed will of God in our hearts
will be the only acceptable offering at our hands.
The covering over the meeting was solemn, under which it broke up.

Ninth Month 15th.--My baptisms of late have been deep,
and as much as I can bear up under, which causes strong and frequent cries,
"`Lord save me or I shall fall.`"
After all my trials I fear lest I should become a castaway--by night
and by day my cries are to my dear Lord to have mercy on me,
for I feel ready to die, and can take no spiritual sustenance to support me.
When will the Almighty arm be made bare for my deliverance?
Surely the Lord delays His coming!
But oh! my soul, be not you too much dismayed,
for when He does come His reward is with Him.
In my humiliation my judgment is taken away--I feel hedged in on every side.
When oh Lord! will you cause the light of your countenance once more to shine upon me?
These purging seasons are necessary;
in one I passed through this morning every crown
I might have been favored with heretofore,
was cast down at the footstool of the Lamb, who is alone worthy to be honored and obeyed:
I cast myself and all that I have into the arms of His everlasting mercy,
which endures from one generation to another.
I have not felt so deep a plunging I think for years,
which I suppose was necessary to do away more of the dross still behind.
Oh! the wormwood and the gall,
how bitter is this cup to drink of-- this is a partaking of a
measure of Christ`'s sufferings spiritually,
that our life may be hid with Christ in God,
and when He who is the Resurrection and the Life shall arise, these shall arise with Him,
and be made partakers of His life.
Praises and thanksgivings to Him who lives and reigns forever and ever.

26th.--I felt drawings on my mind to attend the week-day meeting in Lisburn,
which was very much in the cross, even to tears.
I had to deal in a very close manner on the power of the cross,
and the blessed effects derived from obedience to it; with a caution against Delilah,
and reposing in her lap, and to take warning by Samson,
who was a Nazarite from his birth, yet he lost his strength and his light,
and became a bondman to the uncircumcised,
and was bound in fetters of brass --spiritualizing it.
It was an open time, and a solemn covering was spread over the meeting.

30th.--My exercises are many,
and deeply distressing on account of the state of my son`'s affairs,
with the poor prospect his small family has of a livelihood;
my own state also being a stripped one, leads me ofttimes to call upon Divine Mercy,
that he would be pleased to afford me but one ray of light to show me where I am,
if I am still in the land of the living.
My sore runs in the night season, and occasions me many sleepless hours,
meditating an escape from this furnace, and to pitch my tent in some other place.
Such thoughts occupied me early this morning in bed,
when these expressions impressed my mind in a solid manner,
and entirely laid aside my meditated removal
elsewhere,--"`You are a fruit-bearing branch,
you must abide in the Vine,
or you can not bring forth fruit;`" by which I understood that if I
roll moved in my own will or desire I might become fruitless,
and be as a useless branch broken off and cast away.
A lesson of sound instruction, may I never forget the awful effect it produced in me.

Twelfth Month 2nd.--The Quarterly Meeting at Lurgan,
which was attended by our dear friends Hannah Field and Elizabeth Barker,
from North America, whose company and gospel labors were truly satisfactory:
I think the meeting was comfortable, and the business conducted with harmony.

Second Month 2nd, 1817.--I attended the meeting at Moyallen,
where after a deep travail I was opened on the new birth,
from the state of the babe whose food is proportioned to its weakness,
the pure milk of the Divine Word--its progress
to the state of the young man--then to manhood,
enabled to resist the devil--then to that of an elder who becomes a pillar in the church,
able to bear up and support a share of the building--and the
next translation would be to heaven and happiness,
there to receive the fulness of the answer of "`Well done,`" etc.
It was a time of favor, and brought me the comfortable evidence of peace:
there was a person present lately received into membership,
for whose encouragement and strengthening I believed I was thus drawn forth.

6th.--I attended the Preparative Meeting in Lisburn by appointment,
in it those deistical principles so prevalent were closely
spoken to and resisted on the clear evidence of Scripture,
with the danger of dying in a denial of Christ before men,
and the awful consequences thereof.
I had to trace the enemy`'s delusions and various transformations from Adam,
in sundry generations of mankind, describing their appearances,
and that he still is the unwearied enemy,
and is now attacking the Divine light from heaven,
desiring to gain proselytes to the opinion that it proceeds altogether from man,
as a portion of his reason, and not from Christ in us the hope of glory.
It was an exercising time to my mind, but left the evidence of peace.

I am now in the 78th year of my age,
and am mercifully favored with health and ability to attend meetings at home,
and sometimes abroad: when the time comes that the account must be rendered,
may it be with joy and not with grief, striving to do whatsoever is commanded to be done.

Third Month 7th.--Our Quarterly Meeting in Lisburn,
my previous preparation for it was great discouragement and poverty of spirit,
which led me secretly to desire that some other ministering
Friend might be sent to it to relieve my distress,
but none came.
In the First-day forenoon meeting I had a little relief, but it was a poor low time,
and the afternoon meeting was held in silence.
I had a relieving share in the service of the meetings for business,
and in the parting meeting had an open time, being enlarged to several states,
and concluded in supplication.
Since that time I have had several deep and purging seasons
that I have almost been ready to surrender my crown and to say,
"`Send by whom you will send;`" but a small portion of faith and patience being afforded,
I was made willing to travel on through heights and through depths,
and put my whole trust and confidence in that arm of Divine support
which has hitherto sustained me through many trials arid probations:
to Him is the praise, but to me shame and confusion of face!

12th.--For some time past I felt drawings to attend the week-day meeting in Lurgan,
and after some reasonings respecting the smallness of it I went, and found it very small;
yet there were those in it who I believed were under religious exercise and close trials,
to whom I had to hand forth encouragement to persevere
and wrestle for the blessing as Jacob did,
that they might prevail with God, and then their light would shine forth with brightness,
which would enable them also to prevail with men,
so as to acknowledge that God was in them of a truth--that
they had many trials of their faith to pass through,
but I urged them not to be discouraged,
for all the stones which compose the spiritual building, Christ`'s church here on earth,
are tried ones,
and are in this manner brought into their places in that body
of which Christ Himself is the holy Head and High Priest.
I believe my concern was on account of this class, and it afforded me peace on my return.

To record the many baptisms I have to pass through,
and painful exercises which I believe are the experience of all Christian travelers
(in that way which the vulture`'s eye has not seen) is not my intention;
the wind blows where and when it wishes, we hear the sound thereof,
but know not from where it comes;
therefore such must be contented to bear the blasts of
it without considering much about the cause:
this is very much the course I travel in.
I felt drawings to attend Belfast meeting this day two weeks,
which from my weakness at the time, with some other discouragements,
made it hard to give up to, but I was secretly helped through,
and had a time of favor and much enlargement in both meetings,
and openness in sundry families, stopping there nearly three days.
Since then my borders have been narrowed, and I rest satisfied,
hoping I feel myself at times under the shadow of His holy wing,
in which I find great delight; though at others some withering blasts are felt,
for which I hope I am thankful.
A change of seasons in the natural world is pleasant,
the spring coming on after the winter, with the singing of the birds is cheering;
so are the secret touches of Divine love succeeding the cold blasts of winter,
strengthening and refreshing to the traveller,
encouraging him to hold on his way without fainting or growing weary.
This is part of that hidden mystery which the world by wisdom knows not of,
neither can it, as experience only can teach it;
by this the wayfaring man (though a fool as to worldly wisdom) has found it,
and walks therein, while the worldly wise count his life as madness,
and that his end will be without honor.
Unsearchable, Oh Lord! are all your ways,
and past our finding out any other way but by submission to your holy will.
We have girded ourselves heretofore, and went whithersoever we would, but the time is,
now come to me when another girds me and carries me sometimes where I would not,
but I believe in that wisdom to which I cannot add anything.
It is now become as my meat and drink, upon which I live,
to look inward for secret help and direction in all my goings,
that I may be enabled to walk without reproach from my own conscience or from men.

Ninth Month.--I attended the Quarterly Meeting at Grange, near Charlemont,
and next day the week-day meeting at Moyallen, which was satisfactory;
after which I returned home,
and found the sheriff had that day sold by auction almost the whole of my son`'s crop,
but my share of property was untouched.
I was made acquainted with it just before meeting,
which brought me to a stand whether to go to meeting,
or home to attend the auction and claim what things I had a right to.
I staid at meeting, and left my affairs to Divine disposal, and I did not lose anything,
though I was told there were some greedily wanting to have my hay sold,
as I was not there to advance the money if it were;
but a stranger came forward and offered to advance the money for me till my return:
thus was I preserved from loss!

+++[+++It appears that John Conran went through much trial in his son`'s family,
with whom he had resided after his marriage in 1807; and in 1813, he writes]:
--my situation here has been very dissatisfactory,
but I have thought these trials were permitted for my refinement,
and though I have very often prayed and entreated that I might
be favored to see some other situation to retire to,
yet at present I cannot, but have still to suffer most afflicting seasons.
May God not lay it to their charge, for they know not what they do!

Eleventh Month 16th.--Many have been my trials and deep exercises of late,
both inwardly and outwardly, that I have often secretly prayed that my faith fail not;
but an invisible Hand supported me, and kept my head above the waters,
when the successive waves appeared likely to overwhelm me.
I feel bound to this meeting, so that I cannot find an open door to go out and leave it;
and though my labors are frequent among its members,
the dry bones in the open valley will rise up in judgment against them and condemn them,
for they showed signs of life, and rose up when the prophet prophesied upon them;
but here there does not appear any marks of resurrection, the earth keeps its place,
not showing any symptoms of being moved out of its place in their hearts,
which makes the labor harder to the poor storm-beaten traveller,
who at times can scarcely find a path through the wilderness, which leads to peace.

This day the excellency of the Scriptures was spoken to and acknowledged,
but the more excellent way was preferred,
that Word of life and light which gave them forth--that they were ofttimes my study,
and administered comfort and consolation in comparing my
exercises and temptations with those which are there recorded;
yet although my memory would serve me to repeat the whole of them,
and to preach therefrom the doctrines they contained,
if it were not mixed with true faith proceeding from my having tasted, felt,
and handled the pure Word of life and light which gave them forth,
my preaching would not profit the hearers, or afford peace to myself.
Some in this day search them, and think in so doing they shall have eternal life;
but though they testify of Christ, yet of themselves they do not give life.
Apollos, in the beginning of his ministry, was mighty in the Scriptures,
and from them preached Christ boldly, not fearing the opposers in that day;
but when the two well-instructed elders heard him so powerful in the letter,
they took him under their pruning hand, and taught him the way of God more perfectly,
and then he became a fellow-laborer with the Apostle, and what the latter planted,
Apollos watered, and God alone gave the increase.

Seventh Month 9th,
1818.--Feeling a small draught towards the week-day meeting at Hillsborough,
I thought it safest to give up, though attended with a discouraging poverty.
I sat down in that state, but was rather surprised at my feelings,
which were covered with great stillness,
that I thought I had got into a quiet habitation from the enemy,
who on these occasions often endeavors to stir up in me wandering thoughts.
All was silent,
when there arose before me not only doctrines instructive to the Christian traveller,
but encouragement also to persevere in that way that I believe Truth,
by its Divine light, had cast up before the mind, and was inviting to walk in.
I waited on these openings, as they moved on my mind, upwards of an hour,
desiring a clearer evidence to express them, which not being afforded,
I was submitting to retain them for some other season, and now to keep silence;
when this intimation touched my mind, that Shiloh`'s waters run softly,
which had the healing effect to strengthen my feeble knees, so that I stood up,
and proceeding quietly on by little and little, as it was afforded me,
they gradually increased to a pretty full stream
of comfort and consolation to my own poor state,
and I hope also to the minds of some others, the savor of which remained with me,
and the next day also,
relieving me from that state of desertion which is very often my experience.
Your ways, oh Lord! with the children of men, are wonderful,
and past human wisdom to find out; the stork knows its way in the heavens,
because it is instructed by you, but man, by refusing Divine instruction,
knows not his way, it is past his finding out.

I am now in the 79th year of my age,
and I believe I may say I feel my watchfulness increased,
having to examine carefully almost every word or sentence I make use of,
lest by any means I should miss of so great salvation which
has been offered to me in the discovering light of Christ.
Oh! you careless ones, and lukewarm professors of the blessed Truth,
who have neglected your day`'s work in the day of God`'s mercy to your souls,
and are spending your money (or talent) upon that which does not profit,
what will you do when the end comes, and the talent is called for with usury?

20th.--Our family was broken up in Tromra; my daughter-in-law, with the children,
went to her father`'s, and in a few days after, I went to Belfast, to J. B.`'s,
and staid there till about the 26th of Ninth Month.
My abode there was pleasant;
I had some open and satisfactory opportunities in their meeting,
the recollection of which has been consolatory to my feelings.

Twelfth Month 23rd.--I felt my mind drawn to attend the Monthly Meeting at Grange,
(County of Tyrone), feeling a sympathy with the suffering seed in that place;
the privileges of Christ`'s sheep were shown forth,
not the least of which was that of being enabled to
distinguish His voice from that of the stranger,
which they will not follow because he is a stranger--
Christ leads His sheep at times into green pastures,
and by the still waters, causes them to drink of Shiloh`'s brook that runs softly,
brings them down to the washing pool, and up again, bearing twins,
a meek and quiet spirit and love to God and their neighbor.
When I sat down a restless spirit,
(one who had been disowned) stood up and preached against the old prophet,
but it was to me as a sounding brass, being void of that charity which thinks no evil,
but rejoices in the good in whomsoever it appears:
my services in both meetings were I believe acceptable
to some and brought peace to my own mind.

25th.--This morning early, I was deeply humbled with a sharp attack of the enemy,
lest I should be exalted or assume any glory to myself,
which justly belonged to my gracious Lord and Master:
shame and confusion of face was my portion.
After breakfast, in my usual retirement in my chamber,
I was mercifully comforted with a fresh instance of Divine regard flowing into my soul,
which healed my wounded spirit, showing to me that He can wound,
and that He also can heal, blessed and praised be His almighty and holy name,
now and forever.
Amen!

+++[+++Frequent mention is made in his memoranda of these
seasons of daily inward waiting on the Lord,
they often extended to the space of two hours,
and were made to him times of deep instruction, or inward refreshment,
or as he himself expresses it,
occasions in which he experienced something of what the
apostle describes as "`the renewings of the Holy Ghost.`"
The Editor, while selecting from these private memorials,
has been impressed with the excellence of John Conran`'s example in this respect,
and can hardly forbear expressing the desire that it may be more generally followed;
for while the leisure of many might not admit of such
lengthened abstraction from their daily avocations,
none it is believed,
would be permitted to go unrewarded for dedicating such a portion of time,
as they could rightly spare from their temporal duties,
to seeking for that soul-sustaining food without which,
the spiritual life must languish and decay --needful alike for all,
but especially important for those who feel themselves called upon
like John Conran to become leaders and teachers of the people.]

Second Month, 1819.--I have had a wilderness travail for some weeks,
having passed through some bitter baptisms in secret,
but my only consolation is that the Lord can deliver out of them all;
though the fire of temptation is permitted to burn,
it is He only who can quench the fiery darts of the wicked one.
I go mourning on my way daily, looking for Him whom my soul loves, but find Him not.
How long, Lord, will you hide yourself?
For in your holy presence there used to be joy, and with you is peace for evermore.

11th.--Attended the Monthly Meeting at Lisburn,
and had the company of Benjamin White from Pennsylvania, and John Pirn from London,
the former was largely engaged in gospel labor, I sat very much in my usual manner,
little and low.
