== Chapter VIII

[.chapter-synopsis]
* 1824. Various Exercises and Openings in Scripture Doctrine
* Conclusion of His Journal

Second Month, 1824.--I returned from B. after a week`'s absence;
in one of the meetings there I had to address some whose lamp was gone out,
and they were sensible of it,
that they were not prepared to answer the awful summons
if it should come while they were in this situation;
I said I believed this impression was made on their
minds by Him who wills not the death of any,
for His gracious will is that all who have erred and
strayed from His heavenly sheep-fold should return,
repent, and live;
and therefore I recommended it as the loving mercy of God in Christ Jesus,
to awaken them from that sleep of forgetfulness,
which if continued in much longer might terminate in death.
A solemn stillness covered the meeting, and I believed the state was reached.
I was invited to spend an evening at their house,
but did not go-- if any good is performed, let it be the Lord`'s work, and not man`'s.

During this latter period of his life, he appears in his early waking hours,
or other seasons of retirement, when prostrated in awful silence before God,
to have often been favored with a flow of Scripture doctrine,
which was spiritually explained to his understanding in a remarkable manner,
so as to fill him with humble admiration and grateful praise;
he frequently committed these passages, with the heads of their explanations to writing,
while fresh in his memory,
and on one of these occasions remarks how suddenly these Divine openings were closed,
as if a person had been reading to him in a book, which was afterwards shut,
and the communications which had been in the Divine light ceased, adding,
not one sentence I think could I remember a few minutes after,
I could not read any more in that book, neither did I attempt it,
but abode in the quiet submission.
The cause assigned to me this morning for it is,
to convince me from where these openings proceeded; if from my own judgment, meditations,
or compiling,
they would not have been so suddenly obliterated as never till
latterly to make the least appearance on my recollection,
as other circumstances have done.
The Scriptures are a sealed book to the natural man,
and none can break the seals but the Lion of the tribe of Judah,
whom his own works do praise.

+++[+++At another time he says],
These seasons of Heavenly good have appeared to me as somewhat of what Paul alludes
to in the passage concerning
"`the washing of regeneration and the renewings of the Holy Ghost,`"
and are thus at times permitted for the strengthening and refreshing
of our souls in our weary travail and deep baptisms,
lest we should faint by the way; they would be to us as the brook was to Elijah,
who having drunk thereof, travelled in that strength,
in the bitterness of his spirit (baptism), till he came to the mount of God,
where he heard the voice of God commissioning and
appointing him to further services in the church;
under which refreshment his strength and faith were
renewed to resist the appearances of the fire,
the earthquake, and the strong wind--to know the still small voice,
and to follow its requirings--submitting to the necessary baptisms for a minister.

Seventh Month 21st.--As I sat in retirement this forenoon,
I was led to contemplate some of the privileges
attendant on a membership in the militant church;
this is that body of which Christ is the high and holy Head,
from whom the members receive their nourishment,
and qualification for use and service in it.
Some receive five talents, some three, and some one, which when occupied with,
even by such as seem as the uncomely parts of the body more abundant honor is bestowed:
when these are called forth to exercise their talent in the life and power of the Gospel,
the beholders will clearly perceive that they "`know not
letters,`" and their education has been low and mean--from
where then proceeds this flow of words so fitly spoken,
and well applied to the truths of the Gospel and the mysteries typified in the law?
not from school learnings it is evident--they must therefore
against their will be compelled to acknowledge that the same
Teacher who taught the disciples in the beginning,
taught them,
and that they had been in the school of Christ--after
this manner more abundant honor is conferred.
This may be encouraging to such as are comparable to
the ram`'s horns in the hand of the great High Priest,
which were instrumental formerly, we may remember, to bring down the walls of Jericho,
the first conquest made on the other side Jordan,
and should encourage the one talented not to lightly esteem the smallness of their gift,
and to remember, that man is not to live by bread alone,
but by every word which proceeds from the mouth of God.

[.embedded-content-document.letter]
--

[.letter-heading]
From Richard Cockin to John Conran.

[.signed-section-context-open]
Doncaster, Eleventh Month 9th, 1824.

[.salutation]
My Beloved Friend,

Your cordially acceptable salutation, dated Fifth Month 11th,
claimed an earlier proof than the present,
that it afforded us much pleasurable satisfaction to receive another letter from you,
although it was at the same time accompanied by a considerable drawback,
on account of your increasing disability for letter writing which was so manifest;
it was however, an occasion of rejoicing to us, in having again to observe,
that the best things remain uppermost with you,
and that spiritual greenness continues to be the clothing of your mind.
It was also very pleasant to us to hear that you had again
been enabled to attend the Yearly Meeting in Dublin,
and to mingle in exercise with your friends in endeavoring to
promote the best interests of our Society,
of which you were so kind as to give us an interesting account:
so that notwithstanding bodily weakness is becoming your enfeebling attendant,
yet your love to your friends, and to the precious cause of Truth,
appears to remain unabated--which I regard as a certain evidence,
that your spiritual health is preserved in a quickened lively state; and this,
my dear friend, I trust will be continued to the end,
so as that you may have to adopt the consoling language of the apostle,
"`I have fought a good fight, I have finished my course, I have kept the faith,
henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, shall give me.`"

How cheeringly animating is the prospect,
when a portion of that living faith is vouchsafed,
which enables the tribulated traveller Zionwards,
to afresh thank God and take courage--may you, my beloved friend,
witness your spiritual strength so replenished with
faith and confidence in Almighty sufficiency,
that as your bodily powers are increasingly feebler, your mind may be sustained,
as with an anchor sure and stedfast.
It may be permitted to you, as it is the lot of many other travellers,
to be tried at seasons, with discouraging impressions, yes at times fears, doubts,
and enfeebling reasonings may be the depressing feeling of the poor mind,
when the enemy may assail us with renewed attempts,
to weaken our trust and confidence in the redeeming power of the Savior of men;
so that there is still need for us to watch and pray lest we enter into temptation,
and so long as we are clothed with humanity,
so long there appears a necessity for us to endeavor to have our minds centered in
a state of humble dependence on Almighty sufficiency for preservation.

We could wish to be affectionately remembered to T. C. and J. Wakefield and children, he,
with other dear friends at Lisburn--it is very grateful to my feelings,
to witness the flowings of near regard sweetly attract
my mind towards our dear friends in Ireland,
to many of whom we are united in the bond of religious fellowship;
under the continued feeling thereof to yourself, in which my E. C. very cordially unites,
I remain your nearly united and tenderly sympathizing friend, and brother in the Truth,

[.signed-section-signature]
Richard Cockin.

--

Eleventh Month 20th.--This morning long before daylight,
as I lay mourning over the state I felt both in temporals and spirituals,
I remembered the comforts I had enjoyed, when I possessed a domestic establishment,
an affectionate wife and children, a house and land, a sufficiency to support them,
with other enjoyments.
When I contrasted these with my present situation, my wife removed,
my only daughter suddenly taken, my son over whom I have often lamented,
with his children far distant, and I a lodger in another`'s house, being houseless,
and not one foot of land to call my own,
not a relation near to me to close my eyes in a time,
perhaps near at hand--these and many more discouraging reflections similar,
weighed me down, besides a stripped state of mind.
Under the exercise which these produced, I cried,
"`I am desolate,`"--when these words were quickly impressed on my mind,
"`On a Rock`"--it was the voice of the Comforter, who said "`that Rock was Christ!`"
Comfort followed, with thanksgiving and resignation!

First Month 30th, 1825.--I awoke this morning before daylight,
and after some time I was introduced into silence, and into the school of Christ,
where for upwards of an hour, I was taught wonderful things out of his law,
some of which I believe I had not ever known before;
this caused me humbly to be prostrated before Him,
and to confess that He is the Wonderful Counsellor,
in whom alone was and is the power and ability for every good word and work.
Being First-day, in meeting I was clothed spiritually with sackcloth and ashes,
but after sitting in this state near an hour and a half,
I felt the necessity to move forward, and after some wading,
a large field of offering opened before me, much to my comfort and instruction.

Second Month 15th.--This morning I was introduced into that school,
wherein is taught the hidden mysteries of godliness,
to those only who have their ear opened to hear them,
and are found waiting in the temple.
Much instruction in heavenly things passed through my mind, in the newness of life.
The language of mankind was confused at Babel because they attempted to save themselves,
by their own wisdom and understanding, from a return of the waters,
they trusted not to that preservation which had so far repeopled the world,
but would be independent of it.
God saw the work of men`'s hands that it was foolishness,
therefore frustrated it by confounding their language,
which scattered them over the face of the earth.

This confusion of language has continued to this day, and their building,
instead of being to them as a tower that would reach to heaven,
never raised them higher than earthly things:
in this state the natural man is found at this time,
not being able by his own strength or wisdom,
to reach to that purity of language which was lost,
in which God can be acceptably and truly worshipped as God,
and which can only be recovered by the instructions and teachings of the Holy Ghost.
From this state of confusion, proceed the many modes of worship in the world,
in which very many may be said to worship, they know not what;
some in their prayer call God their Father,
when their works plainly show whose children
they are--they call Him their Lord and Master,
and disobey His righteous commands every day-- they pray for forgiveness of their sins,
on the terms of forgiving the trespasses of those who sin against them,
and they will not forgive any a small trespass, who have trespassed against them,
but cast them off till they pay the last farthing--they call heavenly things bitter,
which are found to be sweet to the spiritual worshipper--and the light of the world,
which is the spiritual appearance of Jesus Christ in man,`'
showing to him what is good and the evil of his ways,
(for, "`that which makes manifest is Light,`") many say this is man`'s natural faculty,
and some a remainder of his first estate before he fell;
when the Divine Judge condemned him, that in the day that he eat of the forbidden fruit,
he should surely die.

Thus was the language corrupted from that purity in which it was taught by God,
when man was in the pure image of his Creator,
when he could by the aid and assistance of the Holy Spirit, give names to all cattle,
and the fowls of the air, and to every beast of the field.
But after the fall, the wisdom of man,
(the fruit of the forbidden tree) found out many inventions,
corrupted the language that was Divinely taught,
and introduced the present confusion of tongues,
which cannot be brought back to its original purity,
but by submitting to and obeying the teachings of the Holy Ghost,
without which influence no man can call God his Father, or Christ his Lord,
(1 Cor. 12:3); nor can any man,
but by the same Spirit know who the Son is but the Father,
nor who the Father is but the Son, and those to whom the Son reveals Him.
This knowledge is denied by some churches, saying that revelation has ceased,
that the Scriptures contain all that is necessary for salvation; the above text proves,
I think, the necessity of revelation.
"`To know you the only true God, and Jesus Christ whom you have sent is life eternal.`"
We may gain a knowledge of the Scriptures by reading, or tradition from our parents,
and be equal to Apollos, who was mighty in the Scriptures,
and from there preached Jesus Christ in the synagogues boldly;
yet he was not hereby baptized with Christ`'s baptism,
nor received as a minister in Christ`'s church,
till the (spiritual) way of God was taught him more perfectly.
I believe the Scriptures are the words of God, given by Him to mankind by inspiration,
through holy men of old--that they are a handmaid to the Holy Spirit, conveying to those,
who will receive their testimony, the mind and will of God.

Fifth Month 18th.--The Quarterly Meeting approaching,
and my accustomed preparation for it trying baptisms, poverty,
and discouragement--the Comforter not come--my sight failed,
and little hope of a revival--yet not so far deserted as the prophet Habakkuk,
whose faith did not fail under greater privations.
Lord, help my faith, and give me to remember when your candle shone upon my head,
and caused me to rejoice in hope that though cast down
I was not forsaken--praises be to your holy Name!

Eighth Month 14th.--I have been for some weeks past under a particular dispensation,
a recollection of several incidents of my former life,
and which had passed under judgment and condemnation, unto pardon;
the remembrance was so fresh, that it required an almost constant watch to exclude them.
This dispensation brought me under a trying humiliation,
so that I was often ready and desirous to give up a
service of which I felt myself altogether unworthy,
and when engaged in it, was so feeble, that I generally was brief and discouraged.
This appears to me a state the apostle experienced,
when he said nothing belonged to him but shame and confusion of face.
I have been greatly abased, though mercifully preserved from yielding up my crown;
but through all God was magnified, that His mercy had preserved me,
for to Him alone the praise is due.
It may be a preparatory baptism for the ensuing Quarterly Meeting, +++[+++and if so]
I am satisfied to abide under its continuance, desiring that the Lord will not pity,
nor His hand spare,
till His holy hand has formed and fashioned me to what He would have me to be.
My Lord and Master cried out on the cross, "`Why have you forsaken me?`"
I have in similar and lesser circumstances, cried out in like manner,
but did not feel any condemnation, therefore I am encouraged to hold on my way,
hoping to be enabled to do so, unto the end of the race,
which is not gained by the swift, but those who hold out to the end will gain the prize.
Herein the creaturely part is crucified, and the Lord magnified,
because His mercy has endured so long.
I believe I may say with the apostle, "`I am crucified with Christ, nevertheless I live,
yet not I,
but Christ liveth in me,`" and the life I now live is not according to the flesh,
but in my measure according to the blessed will of the dear Son of God,
and to Him is the praise and thanksgiving, now and forever.
Amen.

Written by myself who am almost blind, J. C.

[.offset]
+++[+++Many of his latter memoranda were written by a kind friend from dictation.]

Eighth Month 23rd.--Memory is sound--I must say farewell to sublunary enjoyments,
and wait my approaching +++[+++end], which I do by night and by day,
not trusting to any works of righteousness of my own,
but to the mercies of God through Christ Jesus.

Twelfth Month 20th.--Last First-day I was at our meeting here,
which to me was remarkably hard, a spirit of unbelief to a great degree was felt by me,
which shut me up for near two hours, a small share of relief was as afforded,
but the cloud which had been broken, soon again closed and the light was obscured.
In the evening after reading the Scriptures in the family,
we had a time of solid retirement, which fully recompensed for the trials in the meeting;
the wing of Divine love was felt by me to overshadow us, and under the shadow,
I hope we were made to rejoice, in our several measures in solemn silence,
which continued during the remainder of the opportunity.
Under this baptism my mind was impressed with this language,
"`Your sins and your iniquities are no more remembered,
I have cast them out behind me;`" this I could
not embrace as being my state and condition,
and that the voice that I heard, was the voice of Him whom my soul loves,
being often of late baptized into a recollection of my former manner of life,
which led me to say that it is of the Lord`'s mercy that I was not consumed.
In this frame of mind I continued to look from this opening,
till it was repeated three or four times, when peace was solemnly proclaimed in my heart,
and was the seal that closed it.
Thus I believe, we are at times mercifully favored with a degree of that hope,
that the Lord knows them that are His.
The foundation of the just and righteous of all generations cannot fail,
and those who build their hopes thereon shall experience that,
though the winds may blow and the rains descend, it will stand.
A holy confidence was raised in my mind,
which caused me reverently to bow before the Great and Good Giver of it,
and to praise and give thanks to Him who is worthy of it,
and who lives and reigns forever.

Painful have been my days, and wearisome have been my nights,
in waiting for the arising of the Sun of righteousness,
who I think has delayed His coming, which is a trial of my faith and patience;
but as all His ways are wisdom, and past our finding out, I endeavor to submit thereto,
and acknowledge my unworthiness, of the favors hitherto bestowed upon me,
and strive to be content with the small share of light still vouchsafed.

Fifth Month 14th, 1826.--I returned from the Yearly Meeting in Dublin:
it was pretty well attended, and in some of the +++[+++sittings we were owned by the]
Master of our assemblies, which was an encouragement to His faithful ones;
I was favored with a little help to get through what was laid upon me,
to my satisfaction, and returned in peace.

26th.--This morning early I was favored to experience the Shepherd`'s voice,
opening and wonderfully expounding many different passages of holy Scripture,
which led me to praise and magnify His adorable mercy in condescending to
visit and communicate with such a poor mortal as I am.
These communications are frequent, which I may call the renewings of the Holy Ghost,
to strengthen and refresh the weary traveller, and +++[+++in them I recognize]
the union and communion of the saints,
which our first parents enjoyed in Eden--blessed union and communion,
through obedience to the grace of the Holy Spirit!

Tenth Month 1st.--As I sat still this morning after breakfast,
this language passed +++[+++livingly]
through my mind, "`Rejoice and be exceeding glad,
for there is a place prepared for you in my kingdom--and
proceed as hitherto in secret prayer and silent waiting,
and you shalt not be puffed up by whatsoever may be committed to you.`"

Twelfth Month 15th.--I am daily waiting my change,
having only the mercies of God to trust to.

1827.--I am daily waiting in the temple, if I may be favored to hear this joyful summons,
"`Enter into the joy of your Lord,`" where the wicked cease to trouble,
and my weary spirit I trust will experience rest.

[.asterism]
'''

[.offset]
+++[+++These appear to be the last words recorded in John Conran`'s Journal,
and in a hand almost illegible, he being nearly blind;
but he continued to attend meetings, even sometimes at the distance of fourteen miles,
as long as his bodily strength permitted it,
so great was his desire to wait with his friends for
the arising of the heavenly Power of Christ therein,
and to be found faithfully occupying with the gift mercifully bestowed upon him,
often saying, as an incentive to a more perfect dedication of mind and body,
"`I serve the Best of masters, who, I can testify from long and precious experience,
withholds no good thing from those who faithfully serve and obey Him.`"]

[.offset]
+++[+++The following extract from the Testimony concerning him drawn
up by the Friends of Lurgan Monthly Meeting will show how he
was engaged with the same zeal in the last meeting he attended,
being the day previous to his death]:--

[quote]
____
With affecting energy,
he closely pressed Friends to faithfulness and diligence in
attending the meetings for worship and discipline,
saying, the parable of the great supper had deeply impressed his mind,
by which he was instructed to believe that no excuse, however plausible,
would be taken for neglecting those important duties; for none, he thought,
could be more reasonable than were mentioned,
wherein one having bought a piece of ground,
it was but prudent for him to see it before paying for it--another, five yoke of oxen,
which it was only reasonable he should be permitted to prove before he paid
the purchase-money --while a third had married a wife and could not come,
having thereby necessarily undertaken to provide for a family,
especially as he is declared to be worse than an infidel who provides not for his own.
Then mourning over those who were not sensible of their situation,
and of the great salvation offered to all, he said,
"`I now again tell you what I have so often declared
that '`no other foundation can man lay than is laid,
which is Jesus Christ.`'`" Then warned all to be careful of neglecting calls from Heaven,
and by the servants sent as messenger after messenger, testifying,
"`Behold all things are ready,`" for should they continue to do so,
the children`'s seats at the Lord`'s table would be filled by others,
who beholding the Light, would flock as doves confined in a room to the windows; adding,
he was made thankful in being assured that Light
had already broken forth and the day had dawned;
and when about to resume his seat, he advanced and said,
"`For thus having been permitted to live to see this day, I praise, honor,
and magnify my God!`"
____
