[short="Testimony of Lisburn Monthly Meeting"]
== The Testimony

[.chapter-subtitle--blurb]
Of the Monthly Meeting of Lisburn concerning our dear friend, John Conran,
late of Moyallen, deceased.

Although this our beloved friend resided for some years previously to
his decease within the compass of another Meeting,
we find ourselves engaged to bear a testimony respecting him,
having been for the greater part of his life a member of our Monthly Meeting,
and many of us having partaken of the benefits of his religious labors.

By a manuscript of his own, it appears that he was born in the city of Dublin,
in the year 1739, of parents professing with the Church of England;
being in easy circumstances, they gave him a pretty liberal education,
having placed him at school at Ballitore, where he remained until fit for business,
and was then apprenticed to a person in the linen trade at Lisburn.
In this situation, he had more liberty than hitherto,
and being a good deal exposed to unsuitable company,
was led into many of the dissipations incident to youth; for which, however,
it appears he was soon brought under condemnation,
and was thereby induced frequently to look inward,
under a belief that that which may be known of God is manifest within;
to use his own expressions,
"`his secret breathings began to be after God,`" he became
more diligent in his attendance of public worship,
and zealous in the performance of the rites and ceremonies of
the profession in which he had been educated.
The continued observation of some of these not
producing the good effects he had anticipated,
he was led, after the lapse of a few years, to look for something more substantial,
and secretly cried for deliverance.
Sin became a heavy burden;
he gradually forsook the pleasurable amusements in
which he had been in the practice of indulging,
sat much alone, and in reading the Holy Scriptures,
they were often made a means of comfort to his tribulated mind;
his desire after stillness and retirement increasing,
he was led into a dependence on Divine instruction.
The work of religion having thus commenced in good earnest,
and his heart prepared for the reception of the Word of Life, he was reached,
about the thirty-third year of his age, in an extraordinary manner,
under the ministry of Robert Willis, a Friend from America,
in a Quarterly Meeting of Friends at Lurgan, into which he had gained admittance,
although not a member.

Notwithstanding he was on terms of intimacy with several individuals of our Society,
he had preconceived a disrelish to our principles;
but his views were now completely changed, and,
under a firm conviction of the rectitude of the proceeding,
he soon afterwards fully embraced the doctrines and views of Friends, not, however,
without passing through many deep conflicts of spirit on this account,
and in the retrospect of his former course of life,
which was often brought before the view of his mind,
attended with a conviction of Divine judgment for transgression;
thus having experienced the terrors of the Lord for sin,
he afterwards became willing to persuade men.

In the year 1780, our dear friend first appeared in the ministry in a meeting at Lurgan,
and continuing faithful to the pointings of duty,
he became an acceptable and able minister of the Gospel.
Deeply impressed with the solemnity of the nature of the engagement,
he was concerned in the exercise of his gift,
to move under the influence of the Holy Anointing;
and thus abiding in watchfulness and humility,
and in reverent waiting and dependence on the Lord alone,
his communications were frequently attended with a sense of
the baptizing power of our Holy Head and High Priest;
and although often but short, were weighty and powerful.
Skillful in dividing the word aright, he ministered caution, counsel,
and reproof to the disobedient and unfaithful, as well as comfort, consolation,
and confirmation to the tried and drooping mind,
and to such as were seeking the way to the kingdom.
Often deeply experiencing a state of inward poverty and need,
he was eminently qualified to minister to this condition in others.

In the exercise of the discipline of our Society,
our dear friend was conspicuously useful.
Zealously concerned for the support of our religious
testimonies in their ancient simplicity and purity,
and for the preservation of our members in soundness of
principle and consistency of practice,
he was enabled, by the aid of divine Grace,
to stand with Christian firmness against that spirit of infidelity which, at one period,
was so prevalent,
and caused the defection of many in these parts from the standard of Truth.
This was a time of great conflict to his mind but he was favored to
be preserved in steady adherence to the cause he had espoused,
and emboldened to testify his belief in the efficacy of
the redeeming power of Christ Jesus our Lord,
and that it is "`not by works of righteousness which we have done,
but according to His mercy He saves us, by the washing of regeneration,
and renewing of the Holy Ghost.`"
Through all,
he evinced that his chief desire was to be found
faithful in the commission he had received,
and a good steward of the manifold Grace of God.

In the diligent attendance of our meetings for worship and discipline,
our beloved friend was a bright example,
and frequently much exercised on account of those
among us who were deficient in this respect.
He labored fervently to impress upon the minds of all the
necessity of not conforming to the spirit of the world,
illustrating by example the doctrine which he preached,
by sacrificing everything of a secular nature that might have stood in the way of
his performing those religious duties which he believed incumbent on him.

In the year 1805, our dear friend was deprived by death of an amiable wife;
a woman of a truly pious disposition, and tenderly beloved by her husband.
This, with some other domestic afflictions of a peculiarly trying nature,
which were subsequently his portion,
he was enabled to bear with Christian resignation and fortitude.

Of late years he did not travel much in the work of the
ministry out of the compass of his own Quarterly Meeting;
he had, with very little exception,
been constant in his attendance of the Halfyear`'s Meeting,
and subsequently of the Yearly Meeting in Dublin,
up to the year in which his decease occurred,
and several times attended the Yearly Meeting in London.
It appears also that he paid repeated visits to the
meetings of Friends in most parts of this nation;
nearly the last engagement of an extensive nature in this way, was in the year 1810,
when he visited the families of Friends in Waterford and Clonmel,
and having been afterwards joined by Henry Hull, a Friend from America,
then on a religious visit to Friends in Ireland,
they were unitedly engaged in a similar service in some other places.
In the autumn of 1819, being then nearly eighty years of age,
he united with John Kirkham, a Friend from England,
in paying a religious visit to the families of Friends of Dublin,
much to the satisfaction of his friends, and the peace of his own mind.

In giving forth this testimony to the life, labors, and services of our departed friend,
we desire not to exalt the creature, but to magnify and extol that Divine Power,
by whose grace he has often been heard to declare,
"`that he was what he was,`" and that
"`to him belonged nothing but shame and confusion of face.`"
He was a man of weighty spirit and deep in religious experience;
being possessed of a good understanding and a sound and deliberate judgment,
his advice was often sought for by his friends in matters of importance.
Thus it may be indeed said, he was truly useful and honorable in his day,
and many of us have had cause to rejoice that he was raised up among us.
Great was his travail of spirit for the welfare of Zion,
and the enlargement of her borders--many were the conflicts he
endured on account of the desolations in our Society,
yet he was often permitted to rejoice in the belief,
that although he might not live to witness it,
a day was approaching in which the cause of truth and
righteousness would more generally prevail,
and in which many would flock to its standard, as doves to the windows.

During his long and useful life he had been favored to
enjoy almost an uninterrupted state of good health,
which with the possession of his mental faculties remained with him nearly to the end,
although it was evident that his natural strength was gradually on the decline.
His removal was rather unexpected, and quite sudden;
nevertheless we have good ground to believe, that,
as he had not deferred a preparation for eternity to that solemn hour,
he was ready for the awful summons; and although we feel our loss to be great,
we have no cause to mourn on his account,
but rather to rejoice that in the abundant mercy of our Heavenly Father,
through the mediation of His beloved Son, our Holy Redeemer, this our dear friend is now,
we trust, enjoying in the full fruition of immortal bliss,
the reward of dedication to the service of his God,
and that as he continued to the last in firm but humble reliance on
that Divine Mercy which had accompanied him through life,
the same merciful Power, we reverently believe,
was his support in the hour of dissolution,
and became his conductor through the region and shadow
of death into that city whose walls are salvation,
and whose gates are praise.

He departed this life at Moyallen, on the 16th day of the Sixth Month, 1827,
in the 88th year of his age, and about the 48th of his ministry.
His remains were interred in Friends`' burying ground at Lisburn,
on the 18th day of the same month,
having been accompanied to the grave by a large number of Friends and others,
upon which occasion a meeting was held,
wherein the solemnizing influence of the Power of Truth was felt to predominate.

Given forth in the Monthly Meeting of Lisburn,
held there the 15th day of the Eleventh Month, 1827,
and signed therein by a number of men and women Friends.
Read and approved in the Quarterly Meeting for the Province of Ulster, held at Lurgan,
the 3rd of Twelfth Month, 1827, and signed in and on behalf thereof, by

[.signed-section-signature]
Thomas Cheisty Wakefield,

[.signed-section-context-close]
Clerk to the Men`'s Meeting.

Read and approved in our Women`'s Quarterly Meeting for the Province of Ulster,
held at Lurgan same time, and in and on behalf thereof, signed by

[.signed-section-signature]
Margaret Harvey,

[.signed-section-context-close]
Clerk to the Women`'s Meeting.
