== Preface

In offering to the public the present small volume,
it may be well to state that it has been selected from
the manuscript journal of our dear friend John Conran,
late of Moyallen, in the County of Down, Ireland.
Care has been taken, in making these extracts,
to preserve and connect all the most valuable and instructive matter,
leaving out only such passages as did not appear desirable for publication,
or whose scope was embraced in other parts of the work.
Some verbal alterations have also been made to lessen the many repetitions,
and a few additions where a clearer elucidation
of the sense of the writer seemed required,
which have in most cases been placed within brackets;
the sole object of the Compiler having been neither to add to, nor to diminish from,
the testimony which this faithful servant and labourer
in the Gospel was concerned thus to leave on record,
for the magnifying of that Divine Grace which was not bestowed on him in vain,
and by which he was what he was.
For the above-mentioned omissions the Editor finds a
sanction in the following allusion to his journal,
made by John Conran near the close of his life:

[.embedded-content-document]
--

"`Upon having these memoirs read to me, I observe some matters which may appear,
and did so to me, as scarcely proper to be inserted in them--to the wise and prudent,
among us and others, they will appear to be foolishness;
but as I sat this day in religious retirement,
it was opened on my mind that the new birth is brought forth like the
natural one in a state of infancy--in this state we think as a child,
and speak as a child, and use and practice childish things;
but when we gain some further strength and acquaintance with the Divine mind,
we gradually see things as they really are, and lay aside these childish things,
experiencing a growth in spiritual stature till
we attain that of a young man or woman in Christ.
Some years since also being retired into religious silence,
at a time of great discouragement from having heard
that Isaac Sharpies had destroyed his writings,
the following charge was clearly uttered within me,
'`Gather up thy fragments, let nothing be lost, for they will be looked for.`'
Under these considerations,
I feel easy to leave these passages to the revision and discretion of solid Friends,
to retain or obliterate as they may think them likely to be useful or otherwise.`"

[.signed-section-signature]
--John Conran

[.signed-section-context-close]
Moyallen, 11th of Fourth Month, 1827.

--

Should any in rising from the perusal of the succeeding
pages admit feelings of discouragement,
from observing the deep probations through which our dear friend had
frequently to pass during the latter period of his life,
it is hoped that they will recollect that he was a chosen instrument in the Divine Hand,
and as such needed again and again to be dipped into Jordan
for his further purifying for the work whereunto he was called;
and that as he was thus deeply baptized,
so he was the more enabled to live very near in spirit to the Source of all good,
and was often refreshed by Him who promised to be "`as the dew unto
Israel,`" at times in a manner which it would not be suitable,
perhaps not possible, to convey to others.
So let none be dismayed, or cast away their confidence;
rather let them continually remember that "`He is faithful who has promised,`" and
that no more will be required of the feeblest of His fold than He will with the
requirement give them strength either to endure or to perform.

It is believed that to those yet remaining, who knew and loved John Conran,
these memorials of the Lord`'s leadings and tender dealings with him will be precious,
and will revive in their remembrance the line upon line and precept upon precept
which he was made an instrument of conveying to them in the days of their youth,
when the visitation of Divine love was extended to them;
may the recurrence thereof lead to the heartfelt inquiry,
how far the Heavenly calls have been answered,
and their day`'s work kept pace with their day;
and if a degree of fear and doubt should clothe their minds on this scrutiny,
may there be an earnest applying for Holy help to make straighter
steps to their feet the remainder of their little time,
that so they may yet be enabled to glorify and praise His name,
whose mercy endureth forever!
And may those of the rising and succeeding generations, in observing the unshaken faith,
the simple obedience, the confiding patience,
and the deep humility which characterised this faithful servant of his good Lord,
be stimulated to follow him as he endeavoured to follow Christ,
that so they also may be graciously permitted to
lay down their heads with peace and praise!
