== Chapter I.

[.chapter-synopsis]
* John Conran
* His Education
* Early Life
* Religious Exercises
* Convincement of the Truth
* And Leading Into the Testimonies Thereof.

I have had it on my mind, at sundry times for years past,
to leave some memorial of the tender and merciful dealings of a gracious Creator with me,
unworthy as I feel of the least of them;
and I trust and hope my endeavouring to do so at this time proceeds
more from a desire to give the praise to whom it is due,
than to exalt the creature, to whom only belongs shame and confusion of face.

I am now, (1808), in the 69th year of my age,
and though the concerns of my past life may by many be
thought of little consequence to the public,
for whom they are not recorded,
yet they may prove of advantage to some who may be led to
travel in that path which the vulture`'s eye has not seen.
The keen discerning eye of human wisdom hath not been able, in any age of the world,
to disclose that mystery that was hid from the wise and prudent,
in all ages and generations; but the patriarchs, prophets, and apostles,
being way-faring men, of simple manners,
and not acquainted with that learning which the heathens took so much pride in,
walked in the living experience of the ways and
workings of jihe Divine grace in their own hearts,
following and obeying it, and were thereby made partakers of that covenant of life,
which cometh only and alone through the spiritual appearance of Jesus Christ within them.
Such as these, let their outward name to religion be what it may,
whilst they obeyed this heavenly light and were followers of it, became children of it,
and the works they did in obedience to it were works of righteousness,
and were accepted at their hands.
It was after this manner, that many professing heathenism,
were not only a law to themselves,
but their lives and conversation made them as lights in the world;
the full manifestation of the glorious gospel day,
being reserved for the coming and appearance of our Lord and Saviour Jesus Christ,
which day Abraham saw in the vision of life and was glad:
in the same life and light the prophets and holy men of old,
as they were inspired by the Holy Spirit, foretold these glad tidings.
This revelation, man by his own wisdom,
and aided by all the acquired learning either of himself or others,
was not able to comprehend; neither was this learning sufficient for men in former ages,
nor is it sufficient in this age or generation,
savingly to shew to themselves or to others, who Christ within, the hope of glory, is,
or to enable them to confess Him in life and conversation, governed by holy fear,
that He is the Christ, the Son of the living God--flesh and blood cannot reveal this now,
no more than it could to Peter, but our Father who is heaven.
Believing in this Scripture, Matt. 11:27., that "`no man (as man) knoweth the Son,
but the Father, nor the Father, but the Son,
and those only to whom the Son doth reveal Him`"

I make these few observations in the forepart of this narrative, as my mode of living;
birth, and parentage, was not corresponding with my profession and faith at this day.
And as my change from the outward and visible signs, representing God`'s grace to man,
to the inward and spiritual grace, typified by these shadows,
was not the result of my own wisdom or will, or that of others,
but arising from the secret manifestations of His Divine grace in my heart,
I feel desirous to bear my testimony to this inward revelation of light and truth,
which I fully believe comes from Jesus Christ,
to redeem those who feel it and are obedient to it,
from all unrighteousness and the world`'s lusts, and to teach them to live soberly,
righteously, +++[+++and godly], in this present world, Titus 2:11-12;
and that it not only teaches us,
but also is sufficient to help and deliver us in every needful time of trial,
which a belief in the outward ordinances, and the observation of times and ceremonies,
never did accomplish for me, as may be seen hereafter in this recital.

I was born in the city of Dublin, in the year 1739,
my parents professing with the Church of England, I was bred in that profession,
and had the advantage of a pretty liberal education under a clergyman of that way.
After I had acquired some acquaintance with the classics, before I was twelve years old,
I was placed under the care of Abraham Shackleton, of Ballitore,
where I acquired further improvement in my former studies,
as well as an acquaintance with such learning as
was necessary to qualify me for business.
I may not omit a circumstance which attended me there when about thirteen years of age,
being an instance of the merciful visitation of Divine grace to us in early youth,
appearing as a spirit of judgment,
and condemning those things which His blessed Spirit holds a controversy with.
In company with some of my school-fellows, I drank some sweet liquor,
(Shrub) which overcame me; after I was in bed some time,
I felt close convictions take hold of me,
which made me sorrowful,--these gradually grew upon me,
and were succeeded by great terrors of death, and future judgment,
which caused me to cry out for mercy, and that I would never be guilty of the same again.
My old master came up to my bedside,
and stood abstracted till this dispensation subsided, perhaps about fifteen minutes.
These impressions, though deep at the time, were soon erased,
and I thought very little more about it, being taken up with amusements.

I was placed apprentice in Lisburn, in the county of Antrim, to learn the linen-trade;
in that situation I had more liberty than hitherto I had experienced.
My intimate acquaintance was with young men about my age,
and having a pretty good share of money given to me by my relations,
it led me into amusements to which youth are incident.
I kept a horse, and was very fond of hunting; I attended balls and assemblies,
to which I was much addicted, and this led to a desire after fine clothes,
which I indulged to an expensive degree; I was also fond of music,
and had a strong propensity to singing and whistling, which the love of music leads to.
I may say with Solomon, I gave my heart to know pleasure in most shapes,
which the sons of men are given to--not as the wise man said,
to know what it was good for;
that knowledge was reserved by the good Shepherd for a future day,
when I was made to see in that light which is superior to the written word,
that these things lead to the chambers of death; for the lovers of pleasure are not,
nor can be, lovers of God, as there is no concord between Christ and Belial.
I continued pretty much in these practices and
habits till I was about twenty-four years of age,
when I felt my mind oftentimes brought into serious reflections,
and that disposition gradually wore away which led me into gay company,
and at the same time out from hearing the Divine voice,
which is a still small voice in the secret of my heart; and to the surprise of many,
some of whom were otherwise valuable members of the community,
I left the assemblies which were termed innocent amusements.

I had lodgings in town, and kept very much at home;
my former companions used to come and tempt me to go with them,
but I refused with such a countenance bespeaking a degree of solidity as surprised them,
and I heard it was reported I was taking leave of my senses,
which occasioned others to come and look at me to see if it were so.
My disposition for singing and whistling, which was a favourite amusement, fell away,
I could not tell how, and I think I never resumed it;
and although my education never led me to look
inward for that which is only to be found within,
yet I was often led into secret recollection and retirement in spirit,
which led me into a belief and perhaps some sensible experience,
that what was to be known of God was made manifest within.
My secret breathings began to be after God,
these led me to the frequent attendance of public worship,
and I very rarely missed receiving the bread and wine,
except I apprehended myself disqualified.
The recommendation not to approach the Lord`'s table,
nor to receive the elements unworthily, lest I should eat and drink my own damnation,
had been a block at which I had long stumbled; but one day, on that occasion,
I thought I felt restrained from going out as usual with those who did not communicate,
so in much fear I approached the table, and received the bread -and wine,
which gave me great satisfaction that I had now received this rite of my church,
and I continued this practice for some years.
I believe I was permitted in this seeking state of mind,
to try this ceremony what it was good for,
for I was an advocate for the religion of my education,
and I have been told by a dignitary in it, that he was always glad to see me in church,
as my deportment there was devout, and he was sorry to lose me.

I was intimately acquainted with sundry of the people called Quakers,
and had an esteem and friendship for them;
but their pretensions to such refinements in religion, their claim to inspiration,
and their silent meetings with the benefit said to arise from them,
I could not well relish, neither did I at all believe it.
I was of the judgment that the New Testament contained
all that was necessary for man`'s salvation,
but it used at times to stagger me,
how I should put to practice its precepts--in it was the form,
but where was the power to fulfill?
Oftentimes I did groan for deliverance from the power of sin and death,
and like many of my then fellow-communicants,
I believed there was no redemption from it on this side of the grave;
this settled me down in a degree of ease in the outside performances,
which like the law formerly did not make the comers thereunto perfect; yet to me,
I believe, they were made useful to bring me unto the better Covenant.

Whilst I was seeking after redemption from sin and transgression, I left the town,
and took a farm, where I have now lived about forty-three years:
I believe this removal was in the ordering of best Wisdom,
it led me away in a great degree from my former acquaintance and habits;
my spare time was taken up with useful, and to me they were agreeable, occupations,
I farmed, and followed my linen business.
I attended the public worship rather more constantly than before,
though about three miles distant,
and thought nothing could shake my opinions which were orthodox in relation to it;
I had not any thoughts of making so important a revolution as to
change or alter the religion of my education--here I was at ease.
But from my frequently retiring into a secret communion in my own heart and being still,
I was gradually led to a close reliance and dependence upon Divine instruction,
not considering that any other body of Christians made
this profession more openly than I did.
Divine Mercy saw me at this time, as He saw Nathanael formerly under the fig-tree,
when no other saw him, and suffered me to try my own strength,
in endeavouring to establish my own righteousness;
that by finding it unequal in the contest with the man of sin,
I might more readily submit,
when the time should more fully come to ask for and receive strength from Him,
upon whom our help is laid.

I usually presented my petitions night and morning,
that I might be preserved from temptations and from sins,
and very frequently read some portions of Scripture before I went to bed.
The week before I received the elements I usually read the service appointed thereto,
and watched over my words and temper,
that I might receive this rite with some degree of acceptance.
But it was often cause of surprise to me,
that I felt no additional strength to be derived from
my pretty constant attendance on public worship,
and the sacrament, so called,
having read and heard of the beneficial effects
obtained from receiving the bread and wine;
for on those occasions,
(which were to me in good degree solemn,) when I
retired from what was called the Lord`'s table,
and humbly kneeling in the pew I returned thanks to God,
and prayed that it might be blessed to my regeneration,
my prayers even then seemed to be dry and unproductive
of the fruits I was taught to expect from them.
All this was performed in my own strength--I said I would be wise,
but it was far from me--the hair that was by nature black was not hereby made white,
nor that which was crooked made strait,
and instead of the old matt being more crucified then than before,
the enemies of my own house kept possession; yet I may say their goods were not in peace,
I longed to get them turned out, and to be set free from the law of sin and death,
under which I groaned and strove for the mastery.
I had a natural warmth in my disposition,
which I was very desirous to overcome as it unsettled
my mind from that state of quiet in which I found rest;
but all the care I used was not sufficient at times to subdue it,
and it was cause of great uneasiness to me when it did get up:
yet I was enabled through Divine favour to keep up a fair outside appearance with men,
was not guilty of immorality, and was reckoned sober and religious,
and upon these grounds I held a pretty good opinion of my own attainments.

Here I was ready to settle down, and to think I had reached the desired haven of rest;
but this state, I believe, is one of the subtleties of our grand adversary,
and is a false rest, and not +++[+++that+++]+++
prepared for the people of God: out of this the enemy will not disturb us,
he will allow us to remain there all our lives,
as I fear too many do--resting in their own labours, their works will not follow them.
But my merciful Redeemer, who knew the integrity of my heart,
and saw that bread did not satisfy my hungry soul,
because I hungered and thirsted after righteousness which these things did not produce,
was pleased to visit me again and again by the secret touches of His Holy Spirit,
gradually drawing my attention thereunto season after season,
making me acquainted therewith as a light in my dark heart,
and as a reprover and swift witness against the appearances of evil,
to which I gave heed, and rejoiced in it,
but must say I knew it not as I have since known it; I believed it was Divine,
but my mind being so limited by the prejudices of education in favour
of that profession of religion I was taught to believe in,
I did not look for, neither did I expect to feel, in myself,
the second appearance of our Lord Jesus Christ without sin unto salvation.
My views and expectations were outward, my worship was only in the outward court,
which was trodden by the Gentile spirit.
I sought for Him without,
whom my soul secretly desired to find--a Saviour
who was promised to save us from our sins,
and not in them.
Sin had become so exceedingly sinful to me, that my cry at times was, "`a Redeemer,
or I perish;`"--but I found Him not--I was seeking the living amongst
the dead--the law formerly did not make the comers thereunto perfect.
He, whom I was seeking, was risen,
and the day was coming upon me that these empty forms and shadows were to flee away,
and the Sun of Righteousness to arise with healing in His wings,
in order to bring forth that life in me, which, being hid with Christ in God,
all my endeavours in my own strength, will, and wisdom, proved ineffectual.
And when the day of the Lord`'s power came upon all those things I thought so much of,
as my attainments in a religious life and conversation, it burned as an oven,
and consumed everything of that nature,
that the Lord alone might rule and reign in my heart, whose right it is.
My righteousness appeared to be as filthy rags,
and was not sufficient to cover my nakedness; I could then say with holy Job,
'`"`Naked I came into the world, and naked I shall go out,`" unless, oh Lord,
thou cover me with a new garment,
the fig-leaf covering does not hide me from thy
judgments, which then began to be revealed in my soul.

I had been in the practice of going occasionally
to the meetings of Friends for years past,
but as my spirit became exercised after more durable riches than I had already obtained,
I attended them more frequently, yet cannot say,
I felt myself much benefited thereby; for,
although I knew the people called Quakers made profession of a
more spiritual religion than other people in this land,
I was not then capable of forming a just judgment of that
which I had only heard of by the hearing of the outward ear;
my spiritual eye had not been then anointed,
by which only I could see the wonders of the new creation of God, in, and through,
His dear Son, Christ Jesus.
The time was not yet come that the Lord would enter into His temple,
and the earth would be moved at His Divine presence,
who indeed is the Lord of the whole earth, and worthy, worthy to be feared, honoured,
and obeyed!

Whilst I was in this seeking frame of mind, I attended a Province Meeting held in Lurgan.
In the first sitting a Friend spoke upon this portion of Scripture, "`Behold,
I stand at the door and knock: if any man hear my voice and open the door,
I will come in to him, and will sup with him and he with me.`"
I did not find this testimony produced any good effect in me,
for I was built up in a good opinion of the religious profession of my education,
and I did not see much in the lives and conversations of many amongst the Quakers,
to induce me to give them much preference to many amongst my fellow-professors: moreover,
I did not comprehend the nature or use of silent meetings.
There was a Friend there from Pennsylvania, Robert Willis.
I think he was silent in that sitting.
Upon Friends gathering into the Meeting for Discipline, I went in,
not knowing the impropriety of it;
and though there were doorkeepers they let me pass on
as they observed a solemnity in my countenance.
In the pause of silence Robert Willis spoke, what it was I could not tell,
my mind being gathered into inward silence;
but such a power broke in upon me that I was greatly broken into tears,
and my whole body was shaken in an extraordinary manner,
attended by feeling the Divine Life to arise within me;
and though it brought a spirit of judgment with it, yet it left a healing virtue,
so that I thought then I would not be ashamed to
confess to the Truth in the public streets,
let the shame be ever so great.
The cross then was nothing to me when compared
with the treasure which was hidden in my heart;
I was then determined to sell all,
so that I could gain this pearl I had been
searching for so long in vain among the rubbish.
Oh! I remember that day, how I did rejoice! a new song was put into my mouth,
even praises to my God!

I do not expect any other but that this statement will be called enthusiasm,
or the effects of a disturbed or warm imagination,
by those who have never been acquainted in themselves
with the like happy and blessed experience,
which I call, as to myself, the beginnings of the new creation of God in Christ Jesus.
The Gospel, in the days of the first messengers,
was termed by the worldly-wise and prudent,
foolishness--an eminent publisher of it was told too much learning had made him mad;
their lives, indeed, were counted as madness,
because the life they then lived was in Christ Jesus,
whilst the lives of those who condemned them were after the flesh,
fulfilling the lusts thereof.
At the same time I fear there are many who make a profession with me of those things,
who are not able to comprehend them,
for we have not any thing that is good but what is given to us of God;
and if we are not concerned to ask wisdom from Him, we shall not receive it,
for the promise remains to be to those who ask: some amongst us do ask,
but they ask amiss, asking that from the form which it cannot give.
To these states I shall not use any reasoning to strive to convince them of their error,
having the experience in myself, how hard, nay, I may say,
how impossible it would have been to have convinced me of these truths before,
till Divine Mercy was extended to me,
and by a simple operation comparable to the clay and spittle to open my blind eyes,
so as measurably to enable me to see the light of His glorious countenance,
and to confess Him before men.
But I write these things for the way-faring man and woman who may be travelling Zionward,
and can read me in their own experience, to encourage them to hold on their way,
and to let no discouragements they may meet with in their wilderness travel,
cause them to look back to Egypt,
for it is only those who hold out to the end that will be saved.

I was now very much reduced to silence, and my spirit oft-times inward,
waiting and looking after Him whom my soul loved.
I thought,
having found Him of whom Moses and the prophets did write--
whose blessed day Abraham saw in the vision of life,
and was glad,
and whose blood of sprinkling speaketh better things than that
of Abel--that now the Egyptian bondage of sin was at an end;
which perhaps was the case with Israel formerly,
when Moses brought the message to them from the God of their fathers,
commanding Pharaoh to let Israel go and worship their God.
But spiritual Pharaoh was not to be so easily prevailed against as I thought.
When he found I was for moving from under his government,
and making for the promised land,
submitting myself day after day to the guidance of the cloud by day,
and the bright flame by night, I was closely pursued by him, his horsemen and chariots,
as if they were determined I should not escape from them.
The power that was permitted to them to try me with was great,
so much so that I thought there was no power so great,
not having as yet experienced the coming of Him who was stronger than they,
clothed with the power of His Father, to spoil +++[+++the strong man]
of his goods, turn them out and take possession for Himself.
This is the work of regeneration,
so little known by the worldly-minded professors--this is the gospel of glad tidings,
(the power of God,) preaching and teaching liberty to the captive,
and the opening of the prison doors to them who had
been bound by the chains of darkness and of sin.
This is not the work of a day,
or of a year--perhaps it may be that of the greatest part of our lives,
to be going on towards perfection, as the apostle Paul declared,
"`Not that we are already perfect;`" though he had been a preacher of the great and
acceptable year of the Lord in Arabia and the coasts and the nations round about;
the command of our Lord and Master must be remembered in every stage of our journey,
to "`watch and pray.`"

Oh! the terrors that surrounded me by day and by night,
lest the enemy should overpower me, and bring me back to the house of bondage,
having been already made a partaker of a degree
of the glorious liberty of the sons of God.
One temptation after another was presented to me,
some in the wisdom and guile of the serpent,
blasphemies in the roaring of the lion were spiritually uttered in my hearing;
but I found by experience my peace and safety
was in deep retirement of spirit and silence;
and though the subtle adversary came only to kill and to destroy,
yet his waters turned God`'s mill, driving me home,
and to seek for help where help was laid, and in due time I found to be there.
Deep indeed were my conflicts,
so that I was willing to exchange conditions with the labouring poor,
if I might find peace with God and remission of past sins.

In Eleventh Month, 1772, I attended the Half-year`'s Meeting in Dublin:
at this time I had not made any alteration in my dress or appearance,
it was pretty much in the usual way of other people.
In one of the meetings for worship I felt my mind drawn into deep
silence--every outward consideration seemed to be withdrawn,
and a deep solemnity was the covering of my spirit, which I very much gave up to,
having found my strength at times renewed by it.
In this season Robert Willis stood up,
and what he delivered I believe I did not then know, nor have I since,
but I felt my lost state and condition so set before me in the secret of my soul,
that with the anguish of it I cried for mercy;
for I thought the pit was open and ready to receive me,
and all the horrors of it surrounded me.
This visitation of judgment, with the terrors attending on it,
brought me very deep and low in my mind, and I found the +++[+++Divine]
fear to operate as a fountain of life,
preserving me more from the snares of sin and death than the
many years of will-worship I had been in the practice of.
I could now say, from an awful experience, that my Redeemer lived,
was a God near at hand and not afar off,
and that He was of purer eyes than to behold sin
of any kind with any degree of approbation.
I returned home much humbled, was often in retired silence,
and diligently searched the scriptures to find some relief to my troubled mind;
and I can bear my testimony to them, that they are the scriptures of the Spirit of Truth,
given forth of old time by holy men of old as they were inspired of the Holy Ghost;
the same Divine Spirit bearing witness to them in my spirit,
and opening to me counsel and instruction, to my edification and comfort.

It was now that the Lord`'s judgments were revealed in my earth,
that I might thereby learn righteousness, all my sins and my transgressions,
which were many, were set in order before me;
it appeared that a book of remembrance had been kept on high,
and that nothing was forgotten.
Oh! the terrors of those days,
when the righteous Judge of quick and dead sat in judgment in my soul,
arrayed in terrible majesty and power, not only to search out the most hidden things,
as if nothing was to escape His all-seeing eye,
but I was made livingly sensible He had the power to cast into hell.
Day after day uttered speech, and night after night declared knowledge,
that there was no repentance in the grave,
the repentance and remission must be done in these bodies;
for hours I have been on my knees with uplifted hands, asking for mercy,
and sometimes apparently brought to the brink of
everlasting death before I could feel remission of sin.
My duty to my parents was brought into inquisition, and I had to make a close inquiry,
in great fear, as they were both dead, and no recompense in my power;
but I had the peaceful answer to make on the scrutiny,
that I had not ever willfully disobliged or behaved undutifully to them.
Oh! ye children, let me entreat it of you, in the fear of the Lord,
"`obey your parents in the Lord, for this is well-pleasing`" in his holy sight;
and you who act in a light manner by your parents,
and trouble them by your disobedient conduct, I am persuaded of it,
you will have to answer for it in this world, or in that which is to come.

Now, to speak on a subject that such numbers,
whom I prefer to myself in acquired knowledge and natural understanding,
place so great dependence upon, is hard for me;
yet I cannot easily avoid relating my experience of that formal profession I made,
when all my deeds of righteousness (so called) and unrighteousness were
brought before the great tribunal that was now set up in my heart.
I saw that when the true church fled into the wilderness,
and the great red dragon cast out his floods of persecution after her,
there was a place prepared for her there for a time, times +++[+++and half a time;]
that then the wisdom of men got into dominion,
and sat as antichrist in the temple`' of man`'s heart,
where Christ before had sat and ruled as the Head of His church.
Then they apostatized from the true faith, which was his Divine gift to His church,
and haying lost the light in the darkness of the human understanding,
they set up a form of godliness, denying the power that can only produce it;
and instead of the true and living faith which was once delivered to the saints,
they established creeds and forms of prayer,
like the kerchiefs we read of that fitted every stature,
that suited every state and condition;
thereby turning the people from feeling their own
states and conditions as they were in the sight of God,
(who, perhaps,
was at the same time judging them secretly) to trust to prayers and
supplications made ready for them some hundred years before they were born;
when the Divine Spirit, who willeth not the death of him that dieth,
was ready to make intercession for them,
not in a set form of words aptly joined together,
but in sighs and groans which no other could utter for them.

And as to prayers in a set form being presented
at the Throne of Grace by unregenerate man,
who is in a state of moral turpitude--I am persuaded they are an abomination to God,
and will not meet his acceptance.
First make the tree good, and the fruit will be good also; but it is Christ alone,
the good Husbandman, that can make the tree good, and then He will eat of the fruit.
I was in the practice, night and morning, of saying prayers in the form,
in as humble a manner as I knew how.
This was borne with in the days of my ignorance; but when in the light,
I saw how will-worship was not acceptable in His holy sight, and had forsaken it,
this practice remained; and one night, as I was on my knees,
I felt such a terror take hold of me, that I quickly rose,
and never dare afterwards proceed in the same formal manner of praying.
When the true church came out of the wilderness, which she has done in these latter days,
she came out leaning on the breast of her Beloved--laying aside all
useless forms and ceremonies that do not profit the comers thereunto,
and solely depending upon the immediate teachings of
the Grace of God and the revelations of His Holy Spirit;
thereby antichrist was dispossessed of his rule and government in the church,
and Christ took to Himself his own power and authority to rule and govern,
who appoints His own servants,
qualifying them for the several uses and purposes which
He in His holy wisdom has allotted,
sending them forth, and telling them, "`Freely ye have received,
freely give;`" these seek no man`'s silver or gold, or apparel,
but serve their own necessities, and those of others, by the labour of their hands.

Although I had suffered deeply, as I thought, in the hour of judgment and of burning,
yet those things which I had suffered were only as a beginning of sorrows;
the ground of the heart was not to be lightly turned up,
the gospel plough was to be introduced, and the fallow ground broken up,
and I was to sow no more among thorns:
the terrors of God`'s judgments were often set before my mind,
and made such deep impressions as I believe will never be erased.
It is a truth past all contradiction with me,
that the Divine Spirit will not dwell in a temple which
He has not previously cleansed in a great degree.
I speak now to you, my beloved brethren and sisters,
who have in your own experience known your measure of the depths of Satan,
and have been brought out of Egypt with a high band and outstretched arm,
and have known Christ`'s baptism to be with fire and the Holy Ghost,
and that it is the baptism which only and alone affords
the answer of a good conscience towards God,
and cleanses both flesh and spirit.

To relate much more of the inscrutable judgments of God,
which are past finding out but in the experience of them,
may not be needful for me to do at present.
I may say that "`day after day uttered speech,
and night after night declared knowledge`"--quietness
succeeded these fearful voices uttered from the mount,
not through or by man, in it he had no share or portion;
remission of the past seemed to +++[+++be spoken]
in this quiet frame, and a voice to say, "`go and do so no more.`"
I was now brought into the school of Christ,
in order to be in* structed by Him in the law that was to be the government, through Him,
of my future life; the old wine was poured out,
the old heavens were rolled up as a scroll, I willingly surrendered them to the fire.
I conferred no longer with flesh and blood, but gave up to the heavenly vision,
and bowed down my ear to instruction, for He spoke now as never man spake;
instead of whetting His glittering sword, and laying hold of judgment,
He became my shepherd,
and drew me to follow Him in the new way by the Shepherd`'s crook of His love,
sometimes leading me into green pastures, refreshing my poor disconsolate mind.
Then it was I thought I would joyfully run the
way of His commandments and never be weary:
here I would gladly have tabernacled, but I was to go down from the mount,
and pass through the winter season,
and mourn the absence of Trim whom my soul was now taught to love,
for the savour of His ointment was delightful unto me.

The same Divine principle +++[+++of light and life]
which led me out of the forms and ceremonies to
worship the Father in spirit and in truth,
also led me by its secret teachings into a straight and narrow way,
as to all superfluities in dress and address; and knowing in whom I had believed,
the same hath preserved me in it to this day, and I trust will do so to the end,
as there is no variableness with Him.
Simplicity of dress and address is becoming a humble follower of a crucified Saviour,
whose garment or vesture was so unlike the fashions of that day,
that they cast lots for it as a curiosity, for it was without seam.
There is a cross to many among us in these things,
as the practice of them declares to the beholders whose disciples we profess to be;
and although all power in heaven and earth is given unto Him, yet,
because the world in their foolish vain hearts despise the wisdom of God in these things,
intended to crucify us to the spirit of the world, and the pomps and vanities of it,
they are ashamed of the cross, and would rather enjoy the pleasures of a sinful world,
which are only for a season,
than to suffer affliction with the people of God in the scoffings of the world.
Although I knew that +++[+++the Quakers]
held these testimonies, and that they were outward marks of union with them,
nevertheless I was desirous to know the ground of them in myself,
and not to take up any thing in which such great salvation was concerned,
but from a clear conviction that it was from the
living foundation God had laid in my heart,
and not man.

The practice and use of the plain language is consonant with
the rules of grammar and the language of holy men of old,
as the Scriptures bear testimony; yet I was desirous to prove all things,
to bring them to the standard of truth in my heart,
and if they stood the measure of that, to cleave to them.
I began to use this language sometimes, and at other times not, when in my infancy:
my near kinsfolk, I heard, said I was beside myself,
therefore it was a cross to use it in their presence;
but denying the cross brought sorrow and weakness along with it, and a fear,
that if I went down the steps of Jacob`'s ladder I should find it more difficult to
recover the ground I had lost than even to ascend to another step.
The prospect of the glorious crown of righteousness that was
set before me as attainable through faithfulness,
encouraged me to press forward; as I endeavoured to do so I grew stronger,
the yoke became easier, the burden light;
and when through inadvertence an omission occurred,
(for afterwards I never dared willfully to
transgress,) I always felt wounded in my spirit.

The change in my dress was a great cross, as I was always given to fashionable dresses,
and at this time had sundry suits of apparel of this sort.
I felt a solemn covering to come over my spirit early one morning, whilst in bed,
which drew me into deep silence and attention,
when I felt it required of me to conform to the simple appearance of Christ`'s followers;
His garment was all of a piece, so ought mine to be, of a piece with my speech,
my life and conversation.
This felt to me a severe stroke; no shelter was now left for me,
but I must appear as a fool to the world,
my speech and then my garments would betray me that I had been with Christ,
and professed myself to be one of His disciples.
I wept bitterly,
and pleaded the cross it would be to me before my friends and acquaintance,
with the loss it would be to me in my present clothes;
but all was silence to my complaints,
and the leaven worked in the lump till the whole man was leavened into submission,
and then I ran the way of His commandments with joy and alacrity of heart,
so much so that I have heard in passing some people say
they would give their oath I was a Quaker.
Oh! saith my spirit, that all the family were so conspicuous, even in the outside,
that they might be known thereby whose they are!

Another testimony we hold is, that we cannot with a good conscience,
contribute in any wise to support the ministry of any church whatever,
who derive their maintenance from their service at the altar;
because we believe Christ is in this day the head of the true church militant,
that His promise made to it before He ascended to His Father, "`Lo, I am with you always,
even to the end of the world,`" has been fulfilled, and is in this very day fulfilling,
His Divine presence being felt where two, three,
or more of His living children are met and assembled in His name.
This being a truth that we fully believe, we are feelingly made sensible that He,
the head of this body, qualifies and sends forth servants and handmaids, as of old,
to minister, preparing them for His work and service, by various dispensations,
baptisms and spiritual washings,
and hands to them the bread which He has broken and blessed,
and they have to hand it to the multitude, without any addition of their own.
And these knowing in whom they have believed,
will neither pay nor receive wages of any man, as the price of their labour;
they are persuaded that He whom they serve is faithful and true,
and having received their ministry without fee or reward, they freely give it,
looking to Him who sent them for their recompense,
which is the sheaf of peace in their bosom.
I was willing to bear my testimony on account of tithes,
the cross was freely submitted to:
I had formerly made agreement for my tithes at forty shillings per annum,
during the incumbency, the bargain was not done away, and my hay being in cock,
and a large quantity within the power of a large river, made me very uneasy,
so that I wished the proctor would take his demand; there it lay, I believe,
two or three weeks,
and I did not feel at liberty to draw it till the bargain with the proctor was vacated.
He readily gave me my liberty, telling me he expected nothing else from me,
and he took that season, I think,
twelve or thirteen meadow cocks for his forty shillings,
which might be worth upwards of ten pounds.

Upon reading this account, some unbelieving person may query,
how did I know but the subtle adversary had put on the appearance of an angel of light,
and had deceived me?
I answer such an one in the words of our blessed Lord, which are the words of truth;
He says, "`My sheep know my voice, and follow me,
and the voice of a stranger they will not follow;`" moreover
we are desired to follow after the things which make for peace,
and things whereby we may edify one another:
now I never found anything but peace as the consequence
of unswerving obedience in these particulars.

I have now given a brief recital of the cause I had to unite in religious
fellowship with those with whom I have since continued to walk,
subject to many scoffings and mockings from some of my kindred,
as well as from many others,
and was mercifully enabled not to turn my cheek from the smiter,
but to bear them for His sake, who suffered more and worse, from sinful and perverse men.
I rejoice and give thanks to my merciful Redeemer,
that He has in mercy called me from the receipt of custom,
and has given me a portion in His service, and fellowship with His people;
and I write these things hoping they may be Messed to
some wayfaring traveller in the same road,
that they may become as way-marks to them,
and show thereby that it is not an unbeaten path,
but others have travelled it before them, and found safety.
