== Chapter VII.

[.chapter-synopsis]
* 1819+++.+++ He becomes a member of Lurgan Monthly Meeting
* Religious exercises
* Accompanies John Kirkham and visits the families with him in Dublin
* Continuation of his exercises and services.

Third Month 22nd.--I am now removed by certificate into
the bounds of the Monthly Meeting of Lurgan,
and am settled in Moyallen in the family of my friend T. C. W.,
which feels to my satisfaction.
It was in the meeting of Lurgan,
I first felt the principle of life and light which
manifested to me my lost state and condition,
and caused me to cry secretly for "`a Saviour or I die,
a Redeemer or I perish,`"--and it was in the meeting of Lurgan
that my mouth was opened the first time in a public testimony,
for the Truth.
The present state of this Monthly Meeting feels to me very discouraging--the
Aarons and Hurs are very few--their meetings for discipline composed of
about eight or nine men--and a spirit gone forth that has laid waste some
families that were once valiant for the Truth,
whose influence has operated like the tail of the serpent to draw many down after them;
the spirit of antichrist is to be felt at times denying the Son to be of the Father
in that fulness which He declared of Himself--a depressing prospect for me,
but no other appeared to open before me, and I was shut out of my two former habitations.
Yesterday I stood up in meeting here with an opening on the necessity of having a
true and living faith in God through the manifestations of the Divine Light,
which is Christ, and though in my silent sitting,
clear doctrine had opened to my view on that subject, I said but a few passages,
when I felt a spirit of opposition and resistance, and sat down under my burden,
sorrowful on their account.

Fifth Month 3rd.--I returned from the Yearly Meeting in Dublin, which was large,
our friend Benjamin White, was frequently and largely concerned in the meetings,
and his companion John Pim.
I was often in silence, being rather a burden-bearer than a testimony-bearer,
but I hope was sometimes suitably opened into some of the states of the church.
In the Select Meeting I had to exhort the members, as my fellow-labourers in the gospel,
to stand plumb upon the living Foundation,
for if a pillar leaned to any side it shewed weakness,
or a disposition to slide off the foundation; if that should happen,
the pillar will be of no farther use in the house, but must be cast out.
There were two members of that meeting, soon after removed from their stations.

My offerings in meetings, though pretty frequent, yet are very short,
sometimes only a few sentences,
but they often bring with them a solemnity and peace to my own mind.
Other dear Friends, with whom I am sometimes their companion in travail,
can launch out into the deep,
whilst I can only keep near the shore with very little sail;
if it were not for the evidence of life attending the morsel,
I should be ready to conclude I had lost ground, not comprehending the cause,
and this language is sometimes uttered under great depression of spirit, "`My God,
my God, why hast thou forsaken me!`"
My inward exercises are very great indeed--contend not, I beseech it of thee,
with thy judgments in my soul, for what am I before thee?
but a worm,
unworthy of the least of thy mercies!
Oh! Mercy, that I am not consumed, for I am hateful in my own sight; how, then,
must I appear in thy most holy and most pure sight,
when the very heavens are not clean before thee?
Then, oh Lord! do I cast down every high thought and imagination of myself,
and sit in the dust at thy footstool, and there desire to receive the law from thy mouth.
Thy judgments sink deep in my soul; when thou visits the people with them,
they will learn righteousness, and I fear not till then.
Many in this meeting having strayed from thy fold, and some of them into a far country,
from whence they may never find their return,
unless thou art pleased in mercy to stretch forth the shepherd`'s crook of thy love,
and draw them.

Seventh Month 8th.--Week-day meeting at Moyallen, a small company.
I felt a concern to rest on my mind to show the loving mercies of God to mankind,
and how unwilling He is that any should be lost to that great
salvation that He hath prepared before the face of all men,
to whom, for this gracious end and purpose,
He hath given a portion of His own blessed Spirit, which, when they will not obey,
He sends His servants, rising up and sending them.
And He hath also given to us other tokens to warn us of His coming to judgment,
the gradual decay of our bodies, natural faculties, and intellects;
even these are often not sufficient to awaken us to a
feeling so as to prepare us for our Lord`'s coming.
Ephraim, we read, had grey hairs upon him,
yet he knew it not--also other states which that favoured tribe was in,
which prevented him from lending his ear to the instructing voice of God.
My concern was warm for some present, and I had to express that the door was still open,
that they might enter in, and find bread to eat, and raiment to put on,
that would cover their nakedness;
but if the Master of the house should rise up and shut to the door,
that they might knock and not get entrance,
for His declaration is that His Spirit shall not always strive with man.
If we let the day pass over our heads, and the night overtake us,
we may then grope for the wall, and not be able to find that whereon we can rest,
and I believed this might be the last call before the command goes forth to "`let
Ephraim alone,`"--desiring that no one might say this is not for me,
and shift, if they can, the weight from themselves to others; but turn to the Light,
and as the disciples did formerly ask, "`Lord,
is it I?`" and the right one will feel this answer, "`Thou hast said it.`"

Eighth Month.--I accompanied my friend, John Kirkham,
from Essex to the following meetings, viz., Lurgan, Lisburn, Hillsborough, Belfast,
Moyallen, and Richhill, in all of which his service was considerable,
and mine very small, having been kept little and low for some time;
but it is the Lord`'s doing, and I am resigned to it; He gave, and He hath taken away,
blessed be His holy name.

+++[+++In the Tenth and Eleventh Months, he visited the families of Friends in Dublin,
with John Kirkham, upon which he remarks+++]+++:
"`Though I had the concern for some years on my mind, at times very strongly,
yet I believe the right time was mercifully pointed out,
and this I acknowledge with secret thanksgiving to Him whose counsel is wisdom,
and His own works do praise Him.
I entered the families greatly stripped,
but in my silent waiting on that Fountain which never can be drawn dry,
I was favoured gradually to feel light to arise out of darkness,
and by following it I was enabled to minister sometimes in little and low places,
and at other times more plentifully, to my own peace,
and I hope to the edification of others.
In two meetings I was favoured to unburden my mind in a full
testimony against that prevailing and dangerous principle of
infidelity which I fear has taken root in some minds amongst us,
but it is to be feared more deeply among the people at large.
I was silent in thirty-three meetings,
but at times the gift operated on me in silent tears, to my comfort, peace,
and resignation; I believe it was good for me that I was there,
and am thankful for the +++[+++Divine+++]+++
aid in helping me to go forth under my varied exercises; the praise is due,
not to me in any wise,
but to the all-wise and good Helper of those
whose only reliance is upon His Divine support.
I returned home with peace,
but it was succeeded by a trying state of poverty in our own meeting,
and when apprehending myself required to express anything in meeting,
had to do it with a stammering tongue and faltering lips,
and to close with very few words, very little being committed to me;
but I abide with the little,
and endeavour patiently to submit to the present dispensation,
though at times these expressions escape my lips, '`Hast thou forsaken me?`'`"

Second Month 17th, 1820.--I attended the Monthly Meeting in Lisburn, which was large,
but a low, heavy, wading meeting; I was held in silence,
not feeling any thing but great poverty,
which is generally my experience in that meeting;
the world is the cloud that overshadows the tabernacle,
by which the Sun of Righteousness is obscured.
When, oh Lord! wilt thou arise, for thy great name`'s sake, and dispel these mists,
that the people may see where their help is laid!
The gods of silver and of gold are the works of men`'s hands,
but the work of righteousness is thine, and brings peace, quietness, and assurance,
and that forevermore!

24th.--At the Monthly Meeting in Richhill, I was a long time in silence: when I stood up,
I said to this effect, that were I to express my feelings at this time,
I should say I apprehend myself to be led into the valley among the dry bones,
and that they were very dry; but I felt the caution of the prophet to possess my mind,
when he was asked if those bones could live;
he did not rashly enter into judgment upon his brethren,
but referred the judgment to the Judge of quick and dead, saying, "`Lord,
thou knowest.`"--Neither did I, remembering that He who raised Lazarus from the dead,
could raise up an army from the dry bones who should stand for His blessed name`'s sake.
And though the state of things may now be very low among them,
yet I believed there was a remnant present,
who should be encouraged to persevere and hold on their way,
and use the little strength they had, and that it would be increased,
if faithfulness were abode in.

Third Month.--The Quarterly Meeting in Lisburn, to me, was but a low time; after it,
I went to Belfast, and sat in their week-day meeting, and two meetings on the First-day,
which were satisfactory.
If the few there keep faithful to what is already made known,
the little will be increased, and they will be made as way-marks to others;
for I believe there is a right seed sown in that place, which is vegetating,
and will in the Lord`'s time show itself green above the earth,
which now covers it from outward view.
I feel that love towards it that is stronger than death, and it will prevail.

26th, First-day.--After reading the Scriptures in the evening,
we had a season of solemn silence,
in which I felt my mind concerned to express the
benefits derived to us under the Gospel dispensation,
in which our lots are cast in this day--that there is
not now any occasion for one man to say unto another,
or to a brother, "`Know the Lord;`" for all may know Him,
from the least to the greatest--neither need we say one to another,
"`Who shall go up to heaven, or to the furthermost parts of the earth,
to bring Christ from thence, that we may hear Him and obey Him;`" for He, the Word,
is near to each of us, in the heart and in the mind, telling each of us the way,
and to walk in it--that though the Scriptures are the words of God,
yet Christ is the Word that was before the Scriptures--that all things were made by Him,
and that when He, the Firstborn, came into the world,
the angels of God were commanded to worship Him--that He is the Light
of the world--that a measure and manifestation of this Divine
illumination is given to every one to profit withal,
which if we follow in the way of its leadings,
will lead us in the straight and narrow way, which ends in eternal life.
We are all candidates for this glorious end,
and the voice of Divine mercy has gone forth throughout the earth,
inviting us to come to this Light, which is Christ; and what by nature we cannot do,
His holy Spirit will enable us to do, if faithfulness is abode in,
and He will save us with an everlasting salvation,
which the works of the law could not accomplish.
My mind was principally drawn to the servants, five of whom were present,
and one of them had been clerk to a public worship house;
the opportunity closed under a solemn covering.

Fifth Month 9th.--I came home last evening from the Yearly Meeting in Dublin,
our dear friend, Stephen Grellet, with his companion, William Allen, were there,
and had considerable service in the meetings,
and a paper recounting some of their travels in foreign parts was read, which,
with some verbal communications from Stephen Grellet, were truly gratifying,
and instructive to put our trust and confidence in the Divine counsel,
and not to fear what man can do.
I was in silence in all the public meetings, but returned in peace,
and was satisfied I was there.

18th.--I felt my mind drawn to the Monthly Meeting at Lisburn, which I attended,
also the Meeting of Ministers and Elders, where,
in reference to a deficiency in bringing families to meeting,
I remarked that the authority which parents had given them by
the Great Parent of the family should be maintained,
as the patriarchs were kings and priests in their families,
and reminded them how the centurion was praised
for supporting his authority in his family.
The succeeding meeting was very low, and I sat a long time much depressed,
when I had to say that the foundation of true Gospel ministry was love--that
God so loved the world that He sent His only begotten Son into it--that He,
the Minister of ministers, preached to the people love to God above all,
and love to our neighbour--that his church was built without hands,
and did not need the support of men`'s hands--that whoever
ministered in it should remember the advice of the apostle,
to minister in that ability which God giveth--that if any ministered out of this ability,
their foundation is comparable to hay, straw, etc., and will be consumed,
as God is said to be a consuming fire; and as He is also said to be jealous,
His glory He will not give to man, nor His praise to the works of men,
for His own works do praise Him, and if any one should take that honour to themselves,
they will lie down in sorrow.

Eighth Month 9th.--A meeting was appointed at Moyallen for Charles Parker, of Yealand,
and Daniel Oliver, of Newcastle, and the next day one at Lurgan, which I attended;
they were both low times.
In the latter, I had to remind Friends of the prize that is set before them,
a crown of glory eternal in the heavens;
but if we do not run we shall not obtain--if we stand still,
we shall be found in the same spot at the end of the race.
"`So run, that ye may obtain.`"

11th.--This morning as I lay awake before day,
I felt a flow of Gospel truths to break forth in my mind--attended with life,
shewing the necessity of experiencing the new birth brought forth in us;
till that is the case, let our profession of religion be what it may,
or our name be ever so high, we are in the Gentile nature,
and our worship is in the outer court.
This felt to me at the time so clear, that I thought nothing could gainsay it,
nevertheless if the blind eye is not Divinely opened, it cannot see into this mystery.
God made a covenant with Israel at Sinai, which covenant they did not keep;
He has made a covenant in these latter days by writing His law in the heart,
and in the mind,
and those who break this covenant and will not keep it are not the Lord`'s people,
nor is He their God, as they do not worship him.
These truths were sealed on my mind,
and as things new and old are brought out of the scribe`'s treasury,
so in the newness of life they may be brought forth to the edification of some.
Blessed are the eyes which see these things and have faith given to believe them,
they shall no longer wander in darkness, but shall have the light of life.
My spirit was deeply bowed with thankfulness, and peace was the covering of it.

Ninth Month 2nd.--The Quarterly Meeting in Grange, was very large,
supposed to be above 600 persons.
Charles Parker and companion were there; I may say I was thankful to be present,
although I was in a stripped state, and wearied in body with my journey from Belfast.
The close of the meeting for discipline was comfortable,
I was drawn forth in supplication,
that the little remnant who had toiled and laboured all the night,
might be favoured to return to their habitations,
with a portion of that bread which had been broken among us,
by Him who feedeth the young ravens,
and those who sincerely ask it from Him--that
they and their families might rejoice together,
in thanksgiving and praise, to Him who only is worthy, now and forevermore!
I had a desire to see the Friends of that particular meeting, next day,
in their weekday meeting, which they very fully attended,
and I was concerned to deal closely with them,
for their general neglect of this reasonable service,
telling them that I felt the Divine jealousy raised,
so as almost to close me from any communication at that time,
which was the reason I was held so long in silence--because the servant`'s
invitation had been more attended to than that of the Master,
who had so often invited, not only by His holy Spirit in their hearts,
but also by His servants--that we called Him Master and Lord,
but did not honour and obey Him as such,
nor yet confess Him before men as we ought to do, etc.
I returned home in the evening, with a sheaf in my bosom.

17th.--I attended the meeting at Richhill, and a public one by desire of Nathan Hunt,
from North Carolina, who was largely engaged in testimony therein,
to the exalting of our principles, and addressing himself to many states present,
I believe, very suitably; and although occupied at home in a laborious line,
to maintain himself and family, being a blacksmith,
nevertheless he had the tongue of a scribe well instructed,
bringing things new and old out of his treasury,
and was as a polished shaft in his Master`'s quiver,
wounding and bringing down the hairy scalp of his enemies.
I felt myself so small and little, that I durst not venture to my tent door,
even to look after this man of God, as he entered into the tabernacle!

Tenth Month 1st.--First-day, I am now returned from meeting,
where I have been practically instructed that I am little and low,
and of no account in my own eyes, and perhaps in the eyes of others also;
the life seems to be much veiled in me, yet I feel a necessity to move with the little,
and to be content therewith; this has been my lot for a long time in this meeting,
but when the great Shepherd shall appear, we may hope to appear with Him.
I have been now for a considerable time closely beset, especially in the night-season,
by the enemy who is permitted to assault me, and I have cried most earnestly for help,
which has been mercifully afforded, when my strength failed.
If those who are acquainted with the Source of help
are scarcely saved from the jaws of the devourer,
where shall the sinner and the ungodly appear!

19th.--Week-day meeting here, after a long time in silence the +++[+++subject of the+++]+++
ten lepers who were cleansed was opened before me--only one returned to give God thanks,
and he was a stranger, not of the house of Israel, where were the nine?
strangers will be called in to sit at the table with Abraham, Isaac, and Jacob,
in the kingdom of heaven, while the children of the kingdom shall be cast out;
for the time may not be far distant when many, who have not been favoured as we have,
with one servant after another being sent with their lives in their hands, to invite,
saying, "`Behold all things are ready,
come ye and eat at the Lord`'s table,`" whilst we are making excuses,
forgetful of His mercies--I say these strangers will come to the light,
flocking like doves to the windows, and will fill up our vacant seats,
for His table shall be filled, and the children of the bride-chamber be cast out,
if they will not hear.
When the Divine light first shone into my heart, I was a stranger also,
but I immediately cleaved to it, and surrendered my body, soul, and spirit to it,
willing to give all up to be possessed of this precious pearl;
and I have been mercifully preserved in the love of it to this day,
now about eighty-one years of age; praise the Lord, O my soul,
for His mercy endureth forever, to those who love and fear him.

Twelfth Month.--At the Quarterly Meeting at Lurgan,
we had the company of Huldah Sears from Virginia, who had large service;
I was shut up in the several sittings, but the last, on Third-day,
when I was enlarged in comparing the shadows of the law,
with the substance revealed in the Gospel.
In the meeting for discipline, the answers from the several Monthly Meetings,
shewing a considerable deficiency in the attendance of week-day meetings,
brought a deep exercise over us for some time, and a consideration arose,
what could be done to endeavour to apply some remedy to this complaint,
uttered in every meeting for discipline.
After a time of retirement,
it opened in my mind to propose the appointment of a committee,
to pay a visit to the several Preparative Meetings,
and to endeavour to stir up Friends to this reasonable and necessary duty,
so much complained of as neglected; which was agreed to, and a committee appointed,
who performed the visit, I believe, to general satisfaction, in the next month.

First Month, 1821.--There feels to me, a disposition in some here,
wanting to comprehend the hidden mysteries of God,
and to measure them by their natural understandings;
to this spirit I have sometimes to minister, but my labour seems in vain,
it must be brought to the Master Himself if cast out.
On First-day, I had to compare the natural man to the world,
in its primitive state as described by Moses, void and without form,
and darkness upon the face of the deep,
until the Spirit of God moved upon the face of the waters--"`and God said,
Let there be light, and there was light, and God saw that the light was good;
and God separated the light from the darkness, the light He called day,
and the darkness He called night`"--man, as born of a woman,
is void of Divine knowledge of heavenly mysteries,
but endowed with a knowledge of the things necessary for man,
called "`the things of a man;`" with this knowledge man generally turns the
strength of his mind and faculties to the obtaining of earthly things;
but the Spirit of God, moving upon this state, says in His own time,
"`Let there be light,`"--and in that light, man then discovers his state of nature,
and feels he is unable +++[+++of himself+++]+++
to do those things,
which the secret counsel of the Most High shews him in his conscience,
are necessary to be done, if he attains to heaven and happiness.
The light then is gradually separated from the darkness,
and the light is called the day of merciful visitation to the benighted soul of man;
and though this light appears in man, it is not of man,
but from God in Christ Jesus our Lord.
Therefore, man should give up his own wisdom in these things,
and wait daily at Wisdom`'s gate,
for that wisdom which alone can explain those mysteries, which were hidden from ages,
and are now revealed in the second coming of Jesus Christ, +++[+++in Spirit+++]+++,
in whom is all wisdom and knowledge, and who is blessed now and forevermore!

10th.--As I sat in my usual retirement this forenoon, a stripped state was my companion,
nevertheless I endeavoured to travel on,
remembering Jacob wrestled through the night season;
under this state of conflict this language feelingly impressed my mind,
"`Mordecai returned to the king`'s gate;`" which comforted me,
and begot in me thanksgiving and praise, that my then state was opened to me,
and I journeyed on with renewal of strength, praising God whose mercy endureth forever.

My baptisms are frequent, by day and by night, especially in the silence of the latter,
though deeply exercising, deep answering to deep in holy writ,
yet they are productive of secret prayer for preservation from the roaring lion,
seeking to devour; the hand which was stretched forth to save Peter,
is stretched forth in due time, when every other help fails,
His saving grace is found sufficient, and my little grain of faith is increased,
to confess, '`Thou art the Son of the everlasting Father,
thou art the Saviour of all who put their trust in thee!`' I have
been favoured with precious seasons in the night sometimes,
when I have felt the inflowings of Divine good to my soul,
bringing the whole man into solemn silence, and covering me with heavenly light;
under this I have lain secretly praying for preservation,
and acknowledging I was but dust and ashes.
These seasons I compared to the brook by the way which refreshed
after the close exercises and baptisms I had passed through,
and increased my faith to say, '`Lord thou hast been my Alpha,
condescend I beseech thee to be my Omega, now in the 82nd year of my age,
that when thou in thy unerring wisdom seest meet to call me from works to rewards,
I may be enabled to say, Speak, Lord, for thy servant heareth, and is waiting thy coming.
Praises be to thy holy and blessed name who liveth and reigneth forever and ever.
Amen.`'

Fourth Month 1st.--First-day meeting at Moyallen: near the time of separating,
a concern ripened so as to encourage me to stand up and say,
that the church of Christ here on earth was a high distinction,
which all bodies professing Christianity claimed as their own,
but let us consider what the Scriptures say
concerning it--they say it is the body of Christ,
of which He is the high and holy Head--that it receives strength and
nourishment from the Head--that as the oil was poured upon the head of Aaron,
which ran down his beard to the nethermost skirts of his garments,
so doth the unction from the holy One,
run down from the highest to the lowest member of His body--
that Christ is the officiating minister in His church,
making use of servants and handmaids,
as He did in the Jewish church--that such are made holy, harmless, undefiled,
and separate from sinners, as He told his people formerly, "`Be ye holy,
for I am holy,`" as the Head is holy so must the members (the body) be holy also,
by having their robes made white in the blood of the Lamb,
who is the Word of God--which Word is in each of us,
as a swift witness against every appearance of evil, reproving and condemning it,
and as we submit thereto, our sins will be washed away,
and we shall be clothed with the fine linen,
which is the righteousness of the saints--that it is not +++[+++a mere reliance on+++]+++
Christ without us which will give us admittance into the kingdom of heaven,
though we may plead having eaten and drunk in His presence,
and that He taught in our streets--it is Christ within us that will give us
the blessed hope of glory--for there is no seed can destroy sin in man but
Christ the Seed of the woman--and if we live in sin and die in it,
"`Depart from me ye workers of iniquity,
I know you not,`" is the sentence on those who are not
washed and cleansed by the inspeaking Word of God,
who told His disciples,
"`Now ye are clean through the word that I have spoken unto you.`"
The Meeting concluded under a solemn covering.

[.embedded-content-document.letter]
--

[.letter-heading]
From Charles Parker To John Conran.

[.signed-section-context-open]
Yealand, Fourth Month 6th, 1821.

[.salutation]
My Dear Friend,

I was duly favoured with thy acceptable letter,
and glad to observe therefrom the revival of an exercise in your
Quarterly Meeting to extend labour for the help of each other,
and to carry home and communicate to individuals and families what may be unfolded
to you of their states and conditions--to point out the path of danger,
and hold forth the inviting language of "`Come brother, come sister,
let us go up to the mountain of the Lord, to the house of the God of Jacob,
and He will teach us of His ways,`" etc.
In my younger days an exercise of this sort was yearly
performed in the meeting wherein I resided,
by appointment of the Monthly Meeting,
and I think I am a witness of its profitable tendency, both among the youth and others:
but it hath been rarely moved in of later years,
and then mostly under the concern of individuals who
have been travelling in the work of the ministry only.
Probably it may be allowable to think that, in consequence of the decline of such care,
defect and indifference have more abounded, and the love of many has become more cold;
it has at least been evident, in many places,
that deadness and formality have more prevailed, and, "`Am I my brother`'s keeper?`"
has been the language more exhibited in conduct, if not in expression,
for want of minding and improving the gift that is in them.

I can feelingly sympathize with my dear friends in Ireland,
they have had much to try them, and much to discourage them;
yet the Lord`'s arm is not shortened that He cannot save,
nor His ear grown heavy that He cannot hear the secret
breathings and petitions of His dependent children and people.
But the things of time and of sense have tended greatly to weaken,
as well as the undue influence of false brethren;
and I cordially unite in desire that my fellow-professors,
both in Ireland and the land of my nativity,
may come out from them and be separate--may not touch the unclean thing,
that He may receive us, and be unto us a Father, and we become His sons and daughters.
Thy remark concerning those who have separated from you, and are not now of you,
I cordially unite with, for,
however cases may differ as to the cause of departure of any,
something is at least due as an acknowledgment from such who desire to return;
and if they are made sensible of their mistake,
and the real ground of their desire for a reunion with the body arise from conviction,
I do hope it will be no task to such, but rather a relief,
to make their situation truly known, and cause it to accompany their request.

[.signed-section-closing]
I am, with sincere esteem, thy affectionate friend,

[.signed-section-signature]
Charles Parker.

[.signed-section-context-close]
Hay, in Brecknockshire, Wales, 17th of Fourth Month, 1821.

[.postscript]
Being here on my journey, I am desired to present thee with the love of our dear friend,
Nathan Hunt, whom I expect thou wilt see in Dublin, and may add,
that I feel helped on my way, as I was favoured to be in Ireland.

--

14th.--Monthly Meeting in Lurgan: this morning early before I arose,
I felt a gentle stream of Gospel truths flow in my mind for some time,
some portions of holy writ were opened in a view that I never saw before; when I arose,
all was wiped out, and a trying poverty succeeded,
in which I secretly craved that I might be spared going to meeting; but I had to go,
and in it the waters rose so high as to become a broad river to swim in of new matter,
what I saw in the morning not appearing; sundry states were clearly opened and spoken to,
the previous baptism I passed through showed me clearly to whom the praise belonged,
to me it did not, for without His holy help I can do nothing that is good.

Fifth Month 13th.--As I lay awake early this morning I
felt life spring up in my mind with this expression,
"`I will be with thee wherever thou goest,`" which brought
thanksgiving and praise to Him who liveth forever.
I felt myself most unworthy to be thus cared for, but He careth for the sparrows,
and a hair of our head falleth not to the ground without His notice.
In the meeting I was low and poor till near the conclusion,
when I felt a little life to arise,
with an invitation to come to Christ and learn of Him who is meek and
lowly of heart--that He being the express image of His Father,
full of grace and full of truth,
what teacher on earth can we find so capable and able to bring us to God?
He invites us this day to learn of Him,
but the stumbling-block is in the way--His yoke must be taken up, His cross borne,
which is the teaching of His holy Spirit, denying all ungodliness and worldly lusts;
for He will not pour the new wine of His heavenly kingdom into our old bottles,
all must be made new.
There was a sweet solemnity over the meeting, and under it we separated:
it may be said "`He wakeneth me morning by morning,
He wakeneth my ear to hear as the learned.`"

Sixth Month 5th.--Our Quarterly Meeting concluded, many of the younger class attended;
I think I may say it was a favoured meeting,
and that the great Head of the church vouchsafed His holy presence at times amongst us,
and I hope broke the bread of life,
and handed it through His instruments to the comfort and
consolation of some who were of the mourners in Zion.
My baptisms previous to this season for some weeks were trying;--am I forsaken?
hast thou forgotten to be gracious?
But I was favoured with patience and hope to sustain me, as upon examination,
into which I was led, I did not find any transgression brought against me.
I do not remember any meeting in which I was more helped than in this:
to Him only be the praise, who is the helper of those who put their whole trust in Him!

Seventh Month 8th.--As I sat in meeting,
a flow of sound gospel doctrines moved in my mind,
connected and supported by appropriate portions of Scripture;
but though I could subscribe in my judgment to them as gospel truths,
yet I kept still in my retirement,
not feeling the life with them +++[+++requiring utterance+++]+++,
which is more than meat to the soul that truly
waits for that bread which comes not from men,
but from heaven; for nothing but the Spirit of God can gather to God,
according to the doctrine of our blessed Lord, that of ourselves we can do nothing.
At length life arose, and I stood up in it,
and declared the state I had been baptised into,
comparing it to that the prophet Elijah was tried with in the mount,
when the supernatural appearances of the strong wind, the earthquake and the fire,
passed before him.
He was not moved by them, but remained in the cave, for the Lord was not with them.
He came forth when he heard the still small voice, wrapping his face in his mantle,
by keeping his eye steadily fixed on the Lord, his holy Head,
he was mercifully preserved from the +++[+++delusion of the+++]+++
false prophet, and received his commission to "`go and anoint,`" etc.
I had to compare the above state to that of such as take upon themselves,
and are appointed by man, as ministers of the Gospel,
not waiting for nor even expecting the Divine unction from the Holy One to qualify them,
and so come ready prepared with written documents compiled from the holy Scriptures,
which the natural man easily comprehends and readily subscribes to,
bearing in his view such a resemblance +++[+++to his state+++]+++
as face answers face in a glass,
but going away under these impressions which are superficially made by man,
he straightway forgets what manner of man he is.
But the words of Christ preaching in the heart are with that power
from above as reaches to the edifying of his body in love,
and the convincement of the hearers that we must no longer continue
in sin if we expect to be incorporated as members in Christ`'s body.^
footnote:["`I have not sent these prophets, yet they ran: I have not spoken to them,
yet they prophesied.
But if they had stood in my counsel, and had caused my people to hear my words,
then they should have turned them from their evil way,
and from the evil of their doings.`"--Jeremiah 23:21-22.]
His church militant on earth--and that Christ in us, by His light and grace,
is our only hope of glory.
The true gospel ministers turn the hearers to Him as a Teacher, and from man,
whose breath is in his nostrils, and who cannot, with all his acquired learning,
make that strait in himself which is by nature crooked,
nor open his own blind eyes to see the beauty there is in holiness,
and that the end thereof is eternal life.
I had to compare the ministry of such to the three appearances
which Elijah could not acknowledge as proceeding from God;
the earthquake to the agitations proceeding from the natural affections of the man,
which never can produce in any the righteousness of God--neither that strong
windy doctrine as if it would rend the mountains and break the rocky heart
in pieces--nor was the Divine Power in the fiery zeal which some cover their
delivery in as with a cloak--these must pass away,
because they are not from God, and the still small voice be waited for,
which always will convey certainty of duty and our
present states to the true waiter in faith and patience.

Seventh Month 15th.--A field of offering was presented
to my view at meeting on various subjects in holy writ,
and I stood up with a pretty clear opening, and proceeded for some time,
when a cloud overshadowed me, and I paused, and the whole was taken from me.
A spirit of unbelief seemed to be the cloud I felt, to which I had to turn,
and suitable doctrine was furnished largely to prove from Scripture
the Divinity of our most blessed Lord--that He was the Son of God,
and not of Joseph--and that if we did not believe in His second coming in Spirit,
to do away sin and to finish transgression in those who believe in Him,
such would lose the benefit of His coming in the flesh,
and remain dead in trespasses and sins.
It was a laborious exercise I passed through, but I felt clear;
the wisdom of man is foolishness in the sight of God!

[.embedded-content-document.letter]
--

[.letter-heading]
From John Conran To +++_______+++.

[.salutation]
Dear Friend,

It was encouraging to me to hear that any portion of the manuscript I
committed to the inspection of thy dear father has merited his approbation,
with that of my much valued and beloved friend,
N+++.+++ H. Thou mayst trace out the way the wayfaring men have to travel;
many are the trials and probations they have to pass through,
but the Lord delivers them out of them all; the dross is to be purged out,
and then comes forth the vessel for the finer.
Oh! my dear friend,
the ways of God with man in the regeneration are past his finding out;
the changeableness of apparel they have to put on has more colours than Joseph`'s coat,
yet it is the garment the beloved child has to wear;
and though false brethren may be the means of
starving and selling the owner into bondage,
nevertheless the Lord is with him, and in His own time will deliver him:
the rod of the wicked shall not always rest on the lot of the righteous.
We may have in such times to walk through the shadow of death,
yet through faith we shall fear no evil; His rod and His staff shall comfort us,
and we shall be led from one degree of strength to another.

The awful situation you were placed in lately affected me;
I may say my heart expanded in secret thanksgiving for your preservation,
and that the fire was not suffered to kindle upon you.
The same Almighty hand which preserved the three
children was extended for your deliverance;
and I have not any doubt but thanksgiving and praise were
secretly poured out in remembrance that His mercies,
both ancient and new, will continue forever to those who put their trust in Him,
to those who will not bow down to the golden image which is +++[+++as it were+++]+++
set up in the plain of Dura by spiritual Nebuchadnezzar.
Hold on, my beloved friend, worship the God of thy fathers in faithfulness and in truth;
dedicate to Him the first ripe fruits of His own husbandry,
and sacrifice the lamb both evening and morning,
and thy works will meet with acceptance before Him.
Although that old altar upon which many sacrifices and oblations have
been previously offered was permitted to fall to the ground,
yet we should not be too much discouraged or lay it to heart;
the Most High dwelleth not in temples made with hands,
His worship will continue the same as before,
and the temple which He dedicates to Himself
will stand whilst a man stands upon the earth.
He never will leave Himself without a witness to celebrate His
praise and to speak well of His adorable name.
I feel the tendering impressions of best love at this time for thee, +++[+++and in it desire+++]+++
that thou mayst hold fast that which thou hast received,
and let no man or thing take thy crown,
which the Lord has crowned thee with in the day of thy espousals.

[.signed-section-signature]
John Conran.

--

Eleventh Month 17th,
First-day.--I had an open time to explain some of the mysteries of godliness
as they are hidden under the types and ordinances of the law of Moses,
which the natural man cannot explain, as he does not comprehend them,
being only and alone to be spiritually understood.
The Divine Being burying the body of Moses,
the place whereof was never found by the natural man, was opened to my view,
and expressed nearly after this manner,--that the spirituality of the law of
Moses was buried by God under the types and figures and ordinances,
which were no more than the patterns of the holy things
themselves which were shown unto him in the Mount,
("`see that thou make all things according to the pattern
shown unto thee in the Mount,`")--these were only the shadows,
the substance of them were reserved in heaven for Christ,
who was the Prophet that was to come,
to be a Lawgiver like unto Moses ("`Him shall ye
hear`")--the shadows did not profit them to whom,
they came; their bodies fell in the wilderness, save a few, a remnant.
But Christ being come a High Priest of good things,
by a greater and more perfect tabernacle not made with hands, through the eternal Spirit,
offered Himself without spot to God,
to purge our conscience from dead works to serve the living God.
I had an open time to declare of the majesty and infinite power of Almighty God,
displayed at Mount Sinai at the delivery of the law by Moses,
preceded by thunderings and lightnings, and the sound of the trumpet exceeding loud;
the mountain smoked as a furnace, because the Lord descended in fire,
and the mountain quaked greatly,
and the people trembled--that He is the same
today that He was in generations that are past,
His power the same, and can make the earthly-minded men to tremble,
if they will resist and refuse to receive the law at His hand,
and to cast their idols of silver and gold to the moles and the bats.

Fourth Month 17th, 1822.--My morning retirements of late have been barren and unfruitful,
I toil and row all the night, and do not catch anything,
yet I persevere through heights and through depths,
hoping when the Master comes I shall be instructed to
let down the net on the right side of the ship:
this state experimentally shows me that without Him I cannot do any thing that is good.
I am preparing to attend the Yearly Meeting in Dublin, perhaps by this baptism,
with other distressing assaults of the enemy, which cause me to cry out for help;
this seems sometimes long in coming,
and occasions me to call more than twice or thrice before it comes,
when my lips begin (spiritually) to tremble,
fearing lest my soul should not find rest in the day of trouble.
These may be necessary preparations for humility,
that we may not take any thing to ourselves but that which belongs to us,
shame and confusion of face.

Sixth Month 15th.--The Monthly Meeting held in Lurgan, a very small gathering,
and a poor low time; when the meeting for discipline was about closing,
under a painful exercise I felt on account of the meeting,
(about eight or nine men) I told them I remembered when there
were sixty-three families who were esteemed in membership,
and about sixty families not in membership, when I visited them,
the former in their houses, and the latter in three sittings, at convenient places--that,
before I had much or any expectation of being united to Friends,
in that meeting-house I received the first feelings
impressed on my mind that my Redeemer lived,
which produced joy and rejoicing in my heart, and broke me into many tears,
and I wept aloud--that in that meeting-house, about eight years after,
my mouth was first opened in a public testimony
for that Principle of light +++[+++and life from Him,+++]+++
which had formerly been experienced by me there, in these expressions, "`Oh!
Jerusalem, Jerusalem, thou that killest the prophets,`" etc.,
"`how often would I have gathered thy children,`" etc., "`and ye would not,
therefore your house is left unto you desolate!`"--desiring
Friends to see if this prophecy was not fulfilling,
or nearly so, and I believed others would be called in to fill their places.

25th.--This morning early, as I lay still,
some passages of Scripture were opened in my mind in a
clearer manner than I had seen them before,
they flowed gently on, so that I compared them to Shiloh`'s brook, which runs softly,
and at the same time waters and fertilizes the ground it passes through,
by increasing faith, which produces good fruits.
The wind which brought this state blew unexpectedly;
whence it cometh or whither it goeth, no man, as man, knoweth.
I was deeply humbled,
and poured out thanksgivings that such an one as I am should be thus favoured;
there were then, as on other similar occasions,
some of the secret things which belong to God communicated unto me,
which are not lawful to write at this time,
but are to be laid up in the treasury till the key of David
opens and brings them forth in the newness of life.
There is a treasury in the temple of our hearts where these gifts are to be cast in,
and not brought forth to such whose spiritual
ears have not been opened by the finger of God;
till then they would only be objects of curiosity to the vain mind,
which being satisfied, the remembrance of them would pass away,
and leave not a profitable trace behind:
therefore it requires the same watchful state in which
they were communicated to preserve them inviolate,
that we may not deck ourselves with our Lord`'s jewels,
or gratify the vain mind in others.

Ninth Month.--I attended the Quarterly Meeting at Grange, near Dungannon,
which was the largest, I think, I ever saw in this province.
Mary Watson was there, and had large service.
Just before the meeting closed, I stood up,
and said that I felt that which was better than words,
comparable to the dew descending upon the tender herb,
which would make it green and fruitful if it were permitted to rest upon it--
that I believed it was the love of God that was thus shed over the assembly,
for our encouragement, not to cast away our hope and confidence,
though we may feel in a state of desertion, but in order to quicken us to advance,
for that we are not forsaken--desiring that we may endeavour to carry
home to our families a share of what has been now dispensed to us,
as "`a piece of flesh and a flagon of wine,`"
that they also may be made partakers with us.
The meeting closed under a solemn covering, and I came home in peace.

[.offset]
+++[+++About this time he received a letter from John Kirkham, of Essex,
alluding so agreeably to the visit which they paid
together to the families of Friends in Dublin,
that an extract from it is here given+++]+++:--

[.embedded-content-document.letter]
--

[.letter-heading]
John Kirkham to John Conran.

[.signed-section-context-open]
Edinburgh, Ninth Month 28th, 1822.

"`I have often remembered our visit at Dublin,
and still feel considerable satisfaction in the remembrance of it;
for though it was attended with +++[+++deep+++]+++
exercise, yet, in abundant mercy, the end thereof was peace.
This thou canst say (with some others) is that which fully repays for all;
and I doubt not but thou wilt be pleased to hear that a
measure of this is at times the attendant of my mind,
in having now nearly finished my visit to the dear Friends of this land.
I have been as far as Kinmuck, and returned to this city on Fifth-day from Aberdeen.
Dear John and Elizabeth Wigham, of that city, are in tolerable health,
but are getting very infirm;
they cannot do much more in travelling but to and from their own meeting.
There are a few choice Friends both at Kinmuck, Aberdeen, and Glasgow,
amongst whom I was permitted to be comforted,
which I esteem a great favour from the holy Head of His own church and people.
My spirit salutes thee, dear friend, in kind love,
and herein I remain very affectionately thy sincere friend,

[.signed-section-signature]
John Kirkham.

--

Eleventh Month.--The approaching Quarterly Meeting brings to me its usual baptisms,
leanness and deeply-trying poverty.
These feelings accompany me mostly in the night season, when I lie for hours awake,
resigning myself up entirely to Divine disposal, who knows best what is fitting for me,
desiring nothing more than mercy,
and that He would be pleased to preserve my feet from falling into
any snare that would lessen my faith and confidence in Him,
whom I love above all things, and whose displeasure in the least degree I dread,
but at the same time that He would not spare any thing in me which should be done away.
Thus I am travelling on in the path which the vulture`'s eye hath not seen;
the wisdom of man will not walk therein,
but the wayfaring man (though a fool as to worldly wisdom) shall not err therein.
This I esteem to be the way cast up for the ransomed and redeemed to walk in;
it leads to that self-abasement which puts no confidence in the flesh.
This was the way Paul was travelling in to humble him,
lest he should be exalted above measure by his visions;
the Divine light shining in his heart,
and showing to him that in his flesh dwelleth no good thing,
and so mortifying was the view,
that instead of patiently dwelling under it till it produced its full effect upon him,
he cried out twice to be relieved from it: this was a necessary baptism,
preparing to place no manner of confidence in any thing
that is short of the assistance of the grace of God,
immediately revealed.
May it always be my blessed experience to be thus baptized
into a lively sense of my state and condition by nature,
in which I cannot do any good thing;
that in the Lord`'s own time I may be favoured with the renewings of His holy Spirit,
which will bring with them life and immortality to light,
to the strengthening and refreshing of my soul in God, through Jesus Christ my Lord.

In the First Month, 1823, the eldest son in this family, residing near Dublin,
was taken ill with a fever, in which he lay above forty days,
and was attended by three doctors;
the sorrowful tidings came here that the doctors had but little hopes of him,
which threw the family into deep distress.
That day I felt and sympathized with them very nearly,
and retiring with these impressions into my chamber,
I felt my spirit drawn forth in prayer, that if it was consistent with the Divine will,
he might be spared,
they being a family who had afforded me shelter when I had been turned out of two houses,
and had treated me kindly.
When I had ended, this language was clearly impressed on my mind,
"`Thy petition is granted.`"
My faith in it was severely tried before it was accomplished;
for about five weeks he was confined to his bed,
and once or twice was laid out as if he was going;
but last week he showed such favourable symptoms that the doctors were discharged,
and his mother returned home from attending him.

Second Month 6th, 1823.--Long before day-light,
I felt my mind impressed with the doctrine of perfection,
which we maintain as a religious Society,
and is opposed by other Christian professors as impossible and contrary to Scripture;
whereas Scripture declares man was made in the image of
God--the impression here received was holy,
harmless as to the other parts of the animal creation,
(his food being confined to the green herbs and fruits;)
he was a stranger to every sinful appetite,
worshipping God in spirit and in truth, not having any temples made with hands;
his union and communion was with God--he walked with Him, he knew His voice,
and followed it.
Here was a state of perfection, laid out for man during his residence here below,
had he obeyed the Divine command; God saw that this state was good, and blessed it.
From this by transgression he fell, and introduced sin in the place thereof,
and death to this blessed state through sin;
thereby losing the union and communion of the Holy Spirit.
In this state of darkness and dereliction, man found out many inventions,
and set up a form of worship, in imitation of that he had lost,
which being of his own invention, led him forth from God to the lower creation,
and he became so darkened, that he worshipped he knew not what;
he lost the dominion over that part of God`'s creation,
and instead of being their lord and master, he became their servant, and worshipped them;
he lost the dominion of himself, and became servant to sin and sin-pleasing pleasures,
and thereby loving darkness rather than the light, which condemned his evil deeds,
he found himself unable to overcome this state,
and on this ground it is that man denies an overcoming to be attainable:
whereas Christ came into the world to put an end to sin and finish
transgression in all those who are willing to deny the corrupt nature,
by daily taking up the cross and following his holy requirings.
Thus the natural man knows not the redeeming power of Jesus Christ,
because he is not of the willing and obedient who eat the good of the land;
whilst the truly spiritual man knows these things, yea the deep things of God;
and as the Divine Seed of light and life abideth in him, the temptation +++[+++to sin+++]+++
is seen in the light, and the life reduces it in obedience to the cross,
and thereby freedom from sin is obtained in proportion
to the measure of Divine grace afforded,
being a portion of that fulness which was found in our
dear and blessed Lord and Saviour Jesus Christ.
So that our freedom from spiritual Pharaoh may be obtained by
submission to Him who is a Prophet and Lawgiver like unto Moses,
that Moses declared unto Israel should be raised up, and whom they should hear.

Third Month 9th. First-day.--Meeting at Moyallen:
in this meeting I was enlarged more than usually,
which has been my comfortable experience for one or two years past,
now in the eighty-fourth year of my age, when the natural life manifests a decay,
yet the spiritual candle (or life) burns brighter; this was promised some time past,
when I was bemoaning my leanness after near forty years
in the exercise of the gift bestowed upon me.

15th.--The Monthly Meeting held in Moyallen was favoured.

18th.--Before day-light, a spring of Gospel ministry flowed in my mind for about an hour,
and many precious truths were opened before me, to my admiration,
in such a manner as man`'s wisdom never had done before to my understanding,
which caused me to praise and magnify the great
and holy Giver of every good and perfect gift;
for in Him dwelleth knowledge, and wisdom, and understanding,
which man in his best and first estate cannot comprehend nor understand.
The evening and night after the Monthly Meeting, I sat at the gate very much stripped,
for the meeting had been much favoured;
in that low estate I continued till after meeting the next day,
when this relief was afforded to me, "`I will never leave thee nor forsake thee.`"
The absence of Him whom my soul loveth is felt,
and leads to a jealousy lest I should have done something that occasioned it;
but when the clouds disperse, and the sun again breaks out,
though grief may be for a night, yet joy comes in the morning without clouds.

23rd.--First-day meeting at Moyallen. I had to contend in testimony with
that spirit of infidelity which had laid waste many in this quarter,
as well as in many other places, the remnant of which still is to be found hereaway;
they hide their heads now, but the sting is in their tails.
The doubt of a virgin bringing forth a son was cleared before me,
in the view of God`'s omnipotence, who at first created man from the dust of the earth,
and by His Word said, "`Let there be light, and there was light`"--in David, He said,
"`I will make my first-born higher than the kings of the earth`"--He
had the priority of every other creature,
being the first born of every creature, and the first born from the dead;
and was the Head of the church, which was named after Him the church of the first-born,
the image of the invisible God,
the fulness of whom dwelt in Him bodily--and "`to which
of the angels said He at any time,
Thou art my Son, this day have I begotten thee?
But to the Son he said, Thy throne, Oh God!--is forever and ever,`" etc.
If these, and many other portions of holy writ,
do not describe Him amply as the Son of God, and not +++[+++merely+++]+++
of man, to such as do not believe them, preaching is in vain.

After meeting, there was a funeral attended by a large gathering, +++[+++whom I reminded+++]+++
that the present opportunity bore testimony that man from the earth was taken,
and to the earth was to be returned, and the soul to God, who created it,
for a purpose of glorifying Himself--the uncertainty of our
time here should awaken us to the consideration how we are
prepared to appear before the judgment seat of Christ,
to render an account of the deeds done in our bodies--if we have done well,
the answer will be, "`Well done, enter thou into the joy of thy Lord;`" if the contrary,
"`Depart from me, ye workers of iniquity!`"
There was a solemnity over the large gathering, and peace was the covering of my mind.
After dinner, I walked into the garden, and as I walked musing, my lips were opened,
as if a hand had done it,
by the Spirit of prayer and supplication in vocal words of thanksgiving and praise,
and humble acknowledgments of manifold mercies and kindnesses
received from him who liveth and reigneth forever,
God blessed forever and ever.
Amen.

Fourth Month 9th.--My attention has lately been occupied by +++[+++the consideration+++]+++
of the rest which is prepared for the people of God: this is, I believe,
generally understood to be eternal in the heavens.
There is a rest to be found in this life, reserved only and alone for God`'s people,
those who are willing to enter therein,
resting from their own labours as God rested from His.
When our eyes are anointed and Divinely opened, we shall see in the light,
which then shines in our dark hearts, that our works of righteousness,
in which we have taken up our rest, and from which we hoped to reap eternal life,
were the works of man,
which never did or can produce the righteousness that God will accept.
Nothing can bring the soul of man to God but the Spirit of God;
our blessed Lord spoke positively that of ourselves we can do nothing,
and that without His Divine aid our own works will avail nothing.
The young man who came to Christ, pleading his righteousness from his youth up,
and asking what else he lacked, stumbled at the cross, would not follow Christ further,
but went away sorrowful.
And Paul, who was faultless in the observations of an outward profession of religion,
when the light from heaven shone around him,
he counted his former works of righteousness but as dross and dung,
which could not profit him, so that he might gain the spiritual knowledge of Christ.
These are some of the mysteries of godliness, which are hid with God,
and only can be revealed by His beloved Son, for whom are all things,
and in whom the fulness of wisdom dwells--"`the Lord our righteousness!`"
He worketh in us those things which we cannot do
for ourselves--if we be willing and obedient,
we shall eat the good of the land.

18th.--The Monthly Meeting being appointed to be held at Rathfriland,
and the weather very boisterous, discouraged me very much,
so that in my retirement I sought to be released from the concern to attend it,
pleading my old age, and the desire I felt to go to the ensuing Yearly Meeting,
in which I might be disappointed by taking cold now;
I was quickly answered in these expressions,
"`Let him who has two coats impart to him who has none,`" which immediately silenced me.
This meeting was raised up near eighty years since, or more, by convincement,
but is at present in a very low state, and their number very small.
After a deep exercise,
I was engaged in a close testimony--I hope in that love which flows
from the Fountain of all true love--endeavouring to stir them up from
that lukewarm state which shut them out from the Divine strength.
Through favour I got home safely,
and thankful that I was strengthened to go and
fulfill the requiring--He is strength in weakness,
and riches in poverty!

Sixth Month 27th.--I have been for some time past a mourner in Zion,
travelling heavily on,
bemoaning myself and my situation among a people of unclean lips--my dwelling in
the cottage in the vineyard--no fellow traveller to travel with me;
yet the language of my spirit has been "`Not my will, but thine, Oh Lord!--be done.`"
I was made willing to bear my portion of His righteous indignation,
as Ezekiel had to lie 390 days on one side for the +++[+++iniquity of the+++]+++
house of Israel, and forty days on the other side for the sin of Judah.

Seventh Month 4th.--"`Week-day meeting here, to me it was a night season; I rowed on,
but caught nothing--I rested on my oar, believing the Lord was present,
though I did not perceive Him: I came away in peace and not disconsolate.
In bed this night or early in the morning, as I lay awake,
I felt the Day-spring from on high to descend three times at intervals very unexpectedly,
which brought me into a reverend frame of silent waiting,
not feeling any communication to attend it; I bowed in thankfulness,
acknowledging the unmerited condescension of the great and good Giver!

13th.--First-day meeting at Moyallen; a very small beginning,
through faith increased to a favoured opportunity.
The promised increase is fulfilled beyond my expectation,
which is a comfort to my old age; my faith is strong in the Lord,
and my trust is in His might;
thankful I am that I am often favoured to feel the sentence of death in myself,
that I may not trust in myself, but in the living God who raiseth the dead,
and His own works praise Him.
There has been much labour bestowed on this meeting,
but with sorrow I say there is little or no visible signs even of the buddings of good,
much less of fruit after so much labour.
Zion, hereaway, if she is redeemed from the evil of her way,
it must be (I believe) through judgment,
for I apprehend from the increasing neglect of religious meetings,
and the low times experienced when the few meet together,
that there is rather a return to bondage than travelling on to the promised land.
I believe this to be my allotted place; therefore though I mourn, as Baruch did,
that the Lord hath seen meet to add grief to my sorrow,
yet I endeavour to confide in a similar promise to him--that my life
shall be given me for a prey in every land where I shall go.

[.embedded-content-document.letter]
--

[.letter-heading]
John Conran To Henry Hull.

[.signed-section-context-open]
Moyallen, Eighth Month, 1823.

[.salutation]
My Dear Friend,

I received thy agreeable favour of Sixth Month 2nd,
conveying comfortable intelligence of thyself and family,
which is truly satisfactory to me.
I do not doubt but it will be equally pleasing to thee to understand
by the present opportunity that I am still continued,
in the natural as well as in the spiritual struggling for life,
with which I humbly hope I am mercifully favoured.
I am now eighty-four years of age,
and my health and strength of body equal to attend some of our meetings in this province,
and I was at our last Yearly Meeting in Dublin,
which I think was acknowledged by our great and good Master.
I send thee a paper which will explain itself,
in order to shew thee that my thoughts are still engaged for Zion`'s prosperity,
and that my wish is that peace may be within her walls,
and prosperity within her palaces; this has been (I trust) my concern these fifty years,
that I have been engaged in His service.
I need not praise it to thee,
who has so often and to my knowledge experienced His bounty;
His faithful servants always bear this testimony, that He is the best of masters,
it is the idle and slothful who call Him "`an austere man.`"
He has not cast me off in my old age as not worthy of my food and raiment;
thanks be to Him, He gives me a sufficiency of both, which He was pleased to promise,
that my allowance should not be abridged in my latter days, and this is fulfilled,
with a hope that the end will crown all.

I have been at times tried in cloudy seasons, +++[+++with the query+++]+++
how we as a Society, could possibly be +++[+++of+++]+++
the church militant here on earth,
when I have painfully had to behold the impure mixture which compose it;
the doctrines are as high as men can bear--to believe in the Light, and to walk in it,
is to walk with God, as Enoch did of old--it translated him,
and would translate us from earth to heaven,
from being earthly-minded to be heavenly-minded.
These considerations at times have brought serious reflections
whether the church has not again retired into the wilderness,
and that we only hold the doctrines, the substance being gone;
but this has only occurred in my humiliations, under which I have kept silence,
and have not inquired after so many living evidences in myself,
as well as in other servants, "`Art thou he that should come, or look we for another?`"
But my bow abode in strength,
the arms of my hands were made strong through the mighty God of Jacob,
and therefore the armies of the aliens were put to flight;
and in compassion to my weakness, the enclosed was opened to me, as it may inform thee;
I send it, not to take anything to myself, but my desert, shame and confusion of face,
and my motive in sending it is that I believe it will gratify
thee to find thy former fellow-labourer is not standing idle,
looking on other men`'s labours, but is still endeavouring to fill up the day`'s work,
in order to get the penny at last.
My sight is much impaired, otherwise but little room to complain.
With affectionate regards to thyself, thy dear companion, and children,
I subscribe myself thy truly affectionate brother and friend,

[.signed-section-signature]
John Conran.

[.postscript]
I still lodge in Moyallen,
my son lives in the bounds of Moate meeting with his wife and children, a farmer.

--

Tenth Month 20th.--This day eighty-four years I was born in Dublin--
many trials and probations I have passed through since in order to
prove me and fashion me to the present shape I am formed into;
I may say I have passed from death to life, through the unsearchable mercies of God,
who plucked my feet out of the mire of sin, and the clay of worldly pursuits,
and has set them upon the Rock which followed Israel of old, and is the Rock of ages,
and of the just and righteous of the present generation;
and He has put a new song into my mouth,
to praise and magnify Him who liveth and reigneth forever and forevermore,
God blessed forever!
Amen.
